/* The page, built from the runs in data.js.
 *
 * Three rules this file follows, each learned by getting one of them wrong in this exercise:
 *
 *   1. No number is written in this file. Every figure comes from `M`, generated by
 *      tools/render_results.py from the tracked results/*.json. This exercise already shipped a
 *      document that claimed every figure was generated while fifteen were typed inside the
 *      renderer — and a page is the version of that failure the most people see.
 *   2. A mechanism figure is not a results chart. The shift is the central object here, so the
 *      page draws it: two rows of real token strings, offset by one. Results say what happened;
 *      mechanism says why it must.
 *   3. A failure goes in the opening tiles. A page that shows only its wins has not earned them.
 *
 * Sections carry `data-role`, so the spine is checkable without pinning any wording.
 */

const NS = 'http://www.w3.org/2000/svg';
const main = () => document.getElementById('main');

function el(tag, cls, text) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
}

function svg(tag, attrs = {}) {
  const n = document.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, String(v));
  return n;
}

function svgText(x, y, cls, text) {
  const t = svg('text', { x, y, class: cls });
  t.textContent = text;
  return t;
}

let sectionCount = 0;

/** A section whose eyebrow names its epistemic role, so a reader knows how to weigh it. */
function section(id, role, eyebrow, title, paras, rail) {
  const s = el('section');
  s.id = id;
  s.dataset.role = role;
  sectionCount += 1;
  s.dataset.n = String(sectionCount);
  s.dataset.title = (rail && rail.short) || title;
  if (rail && rail.sub) s.dataset.sub = rail.sub;
  s.append(el('p', 'role', eyebrow), el('h2', null, title));
  for (const p of [].concat(paras || [])) {
    const n = el('p', 'say');
    n.innerHTML = p;
    s.append(n);
  }
  main().append(s);
  return s;
}

let figureCount = 0;

/** A figure whose caption says what to conclude — never a bare label.
 *
 * **The number is counted, not passed.** It used to be an argument, and adding the ship figure at
 * the top of the page gave the page two Figure 1s — the new one and the mechanism plate, both
 * captioned "Figure 1", in the same document. A figure's number is a count of the figures before
 * it, which makes it exactly the kind of number this page derives everywhere else.
 */
function figure(node, caption) {
  figureCount += 1;
  const f = el('figure');
  f.append(node);
  const c = el('figcaption');
  c.innerHTML = `<b>Figure ${figureCount}.</b> ${caption}`;
  f.append(c);
  return f;
}

function table(head, rows, cls) {
  const wrap = el('div', 'tablewrap');
  const t = el('table', cls || 'grid');
  const thead = el('thead');
  const hr = el('tr');
  for (const h of head) {
    const th = el('th');
    th.innerHTML = h;
    hr.append(th);
  }
  thead.append(hr);
  t.append(thead);
  const tb = el('tbody');
  for (const row of rows) {
    const tr = el('tr');
    if (row.__mark) tr.className = row.__mark;
    for (const cell of row.cells) {
      const td = el('td');
      td.innerHTML = cell === null || cell === undefined ? '—' : cell;
      tr.append(td);
    }
    tb.append(tr);
  }
  t.append(tb);
  wrap.append(t);
  return wrap;
}

/* Counts are SPELLED from the data, never typed. A heading or a rail label that states a number
 * is stating a count of its own contents, so typing it is how a page comes to read "Three commands"
 * over four of them and "Nine words, each with a number" over four words — both of which this page
 * shipped. Ported from exercise 08, which introduced the helper for the same reason. */
const SPELLED = [
  'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
  'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen',
  'nineteen', 'twenty',
];
const spell = (n) => SPELLED[n] || String(n);
const Spell = (n) => {
  const w = spell(n);
  return w[0].toUpperCase() + w.slice(1);
};

const int = (n) => Math.round(n).toLocaleString('en-US');
const signed = (n, d = 4) => (n >= 0 ? '+' : '−') + Math.abs(n).toFixed(d);
const pct = (n, d = 1) => `${(n * 100).toFixed(d)}%`;
const mib = (bytes) => (bytes / (1024 * 1024)).toFixed(1);

/* How many decimals a measurement's own noise floor will support.
 *
 * **This page stated its precision rule and then broke it four times.** The results section says the
 * memory ratio is "quoted as about 9x and no finer" — and the opening tile said 9.1x, the glossary
 * said 9.1x, the ledger said 9.09x and the conclusion said 9.09x, one of them fourteen lines above
 * the rule. Every one of those was a `toFixed()` chosen at the call site, so the rule was a sentence
 * and the practice was five independent decisions.
 *
 * Deriving the precision from the spread makes the page unable to break it. A spread of 0.44 cannot
 * support a tenth, so the digit is not offered.
 */
const decimalsFor = (spread) => (spread >= 0.5 ? 0 : spread >= 0.05 ? 1 : 2);

/** A ratio quoted to the precision its own repeated measurement earns, never finer. */
const ratio = (value, spread) => `${value.toFixed(decimalsFor(spread))}×`;

/* ============================================================== 1 · thesis */

function chapterThesis(M) {
  const t = M.training.summary;
  const b = M.boundary;
  const s = section(
    'thesis',
    'thesis',
    'Two runs, one question',
    'Which of these would you ship?',
    [
      `Below are the loss curves of two models. Same architecture, same data, same seed, same
       ${int(t.total_steps)} steps. One of them is broken — its target shift is off by one, so it is
       being handed its own input as the answer and is learning to copy. <b>Pick the one you would
       ship, before scrolling.</b>`,
      `Almost everyone picks by the number going down, because that is how a training run is
       normally judged. It is also the only judgement this particular bug is invisible to.`,
    ],
    { short: 'The curve', sub: 'pick a run before you scroll' }
  );

  s.append(shipExplainer(M));

  const lesson = el('p', 'say');
  lesson.innerHTML = `<b>The point survives whether or not you played.</b> A lower loss is not
    evidence of a better model; it is evidence that the model found an easier question. Copying is
    easier than predicting, so the broken run reaches
    <b>${t.final_broken_shift.toFixed(2)}</b> while the correct one is still at
    <b>${t.final_correct_shift.toFixed(2)}</b> — and the only reliable check is to print the inputs
    and targets as text and read them, which is what the next section does.`;
  s.append(lesson);

  const tiles = el('div', 'tiles');
  for (const [v, k, mark] of [
    [
      t.final_broken_shift.toFixed(2),
      `the loss a <b>broken</b> model reaches, against ${t.final_correct_shift.toFixed(2)} for the
       correct one. It is counting copies, not predictions`,
      'watch',
    ],
    [
      int(b.boundary_crossings),
      `document boundary crossed in the packed example. <b>This page published
       ${int(b.mask_dropped_including_padding)}</b> until it was checked — that figure counts every
       pair the mask touches, most of them padding`,
      'bad',
    ],
    [
      ratio(M.memory.ratio, M.sensitivity.memory.spread),
      `less memory for an identical loss — but only because the projection happens inside the loop.
       Chunking the softmax alone, which is what the name usually means, is worth
       ${ratio(M.memory.softmax_only_ratio, M.sensitivity.memory.spread)}`,
      'watch',
    ],
    [
      pct(M.heads.head_share),
      `of this model is the output head — of head plus an <i>estimated</i> body. Against the trunk
       actually built it is ${pct(M.shapes.trunk_params ? M.heads.untied_params / (M.heads.untied_params + M.shapes.trunk_params) : 0)}`,
      'watch',
    ],
  ]) {
    const tile = el('div', `tile ${mark}`);
    const value = el('div', 'tile-v');
    value.innerHTML = v;
    const key = el('div', 'tile-k');
    key.innerHTML = k;
    tile.append(value, key);
    tiles.append(tile);
  }
  s.append(tiles);

  const note = el('p', 'say');
  note.innerHTML = `<b>Read those ${spell(4)} tiles as one sentence: check what the number is
    counting.</b> They are marked alike because they <i>are</i> alike — the red one is the only one
    this page published wrong, and none of the others is good news. Two of them are failures and one of the failures is ours, published on this page
    for weeks. That is the thread every section below is on — a loss counting copies, a count of
    dropped positions that counted the wrong positions, a memory ratio that belongs to a different
    technique than the one it is usually quoted for, and a percentage measured against a body
    nobody built. None of them is a bug in the arithmetic. All of them are a bug in the question.`;
  s.append(note);
}

/* -------------------------------------------------------- the one interaction on this page
 *
 * Family: Diff (EXPLAINER_PROMPT §10) — "these look equivalent and are not", inverted: they look
 * clearly UNequal and the obvious winner is the broken one. It is spent on the thesis rather than
 * on a widget because the page's whole claim is that the reader's default judgement is wrong, and
 * the cheapest way to establish that is to let them make it.
 *
 * The shape is docs/EXPLAINER_PATTERN.md §4 — pure `stateFor`, render-only `show`, a `guard` for
 * the state it cannot answer in. It does NOT vendor `_shared/explainer.js`: that skeleton is a
 * scrollytelling topology (states down the left, one pinned figure), and this is a single binary
 * choice. Borrowing it would mean building eleven states to hold one question.
 */
function shipExplainer(M) {
  /* 1. CONSTANTS — the two curves, from the run. Nothing here is typed. */
  const A = M.training.correctShift;
  const B = M.training.brokenShift;
  const steps = M.training.steps;
  const pairs = { correct: M.shift.correct_pairs, broken: M.shift.broken_pairs };

  /* 2. PURE HELPERS. */
  const lo = Math.min(...A, ...B);
  const hi = Math.max(...A, ...B);
  const W = 720;
  const H = 260;
  const PAD = { l: 46, r: 118, t: 18, b: 30 };
  const px = (i) => PAD.l + (i / (steps.length - 1)) * (W - PAD.l - PAD.r);
  const py = (v) => PAD.t + (1 - (v - lo) / (hi - lo || 1)) * (H - PAD.t - PAD.b);
  const path = (series) => series.map((v, i) => `${i ? 'L' : 'M'}${px(i)},${py(v)}`).join(' ');

  /* 3. STATE — the minimum that cannot be derived. */
  let chosen = null; // null | 'correct' | 'broken'

  const wrap = el('div', 'ship');

  const chart = svg('svg', {
    viewBox: `0 0 ${W} ${H}`,
    class: 'ship-chart',
    role: 'img',
    'aria-label': 'two training loss curves, unlabelled until a choice is made',
  });
  for (const [v, label] of [
    [hi, hi.toFixed(1)],
    [lo, lo.toFixed(1)],
  ]) {
    chart.append(svg('line', { x1: PAD.l, x2: W - PAD.r, y1: py(v), y2: py(v), class: 'ship-grid' }));
    chart.append(svgText(PAD.l - 8, py(v) + 4, 'ax', label));
  }
  chart.append(svgText(PAD.l - 8, py((lo + hi) / 2) + 4, 'ax mid', 'loss'));
  const lineA = svg('path', { d: path(A), class: 'ship-line a' });
  const lineB = svg('path', { d: path(B), class: 'ship-line b' });
  chart.append(lineA, lineB);
  const tagA = svgText(px(steps.length - 1) + 6, py(A[A.length - 1]) + 4, 'ship-tag a', 'A');
  const tagB = svgText(px(steps.length - 1) + 6, py(B[B.length - 1]) - 6, 'ship-tag b', 'B');
  tagA.setAttribute('text-anchor', 'start');
  tagB.setAttribute('text-anchor', 'start');
  chart.append(tagA, tagB);
  chart.append(svgText(PAD.l, H - 8, 'ax', '0'));
  chart.append(svgText(W - PAD.r - 34, H - 8, 'ax end', `${int(steps.length)} steps`));

  const controls = el('div', 'ship-controls');
  const ask = el('div', 'ship-ask', 'Which run would you ship?');
  const buttons = el('div', 'ship-btns');
  const btnA = el('button', 'ship-btn', 'Ship A');
  const btnB = el('button', 'ship-btn', 'Ship B');
  btnA.type = 'button';
  btnB.type = 'button';
  buttons.append(btnA, btnB);
  controls.append(ask, buttons);

  const verdict = el('div', 'ship-verdict');
  const readout = el('div', 'ship-read');

  /* guard() — the precondition. Before a choice there is no verdict to render, and rendering one
   * anyway is how a widget comes to answer a question nobody asked. */
  const guard = () => (chosen === null ? { note: 'Nothing is labelled yet. Pick one.' } : null);

  /* stateFor(pick) — PURE. Choice → everything the renderer needs. No DOM. */
  const stateFor = (pick) => {
    const shipped = pick === 'broken' ? 'B' : 'A';
    return {
      shipped,
      right: pick === 'correct',
      finalA: A[A.length - 1],
      finalB: B[B.length - 1],
      rows: pairs[pick].slice(0, 5),
      other: pick === 'correct' ? 'broken' : 'correct',
    };
  };

  /* show(pick) — RENDER ONLY. */
  const show = (pick) => {
    chosen = pick;
    btnA.classList.toggle('on', pick === 'correct');
    btnB.classList.toggle('on', pick === 'broken');
    const refused = guard();
    if (refused) {
      verdict.textContent = refused.note;
      verdict.className = 'ship-verdict';
      readout.replaceChildren();
      return;
    }
    const st = stateFor(pick);
    wrap.classList.add('revealed');
    tagA.textContent = 'A · correct shift';
    tagB.textContent = 'B · off by one';
    verdict.className = `ship-verdict ${st.right ? 'good' : 'bad'}`;
    verdict.innerHTML = st.right
      ? `<b>A is the correct model</b> — and it is the one with the <i>higher</i> loss, at
         ${st.finalA.toFixed(2)} against ${st.finalB.toFixed(2)}. If you picked it, you picked
         against the number.`
      : `<b>B is the broken model.</b> Its loss is lower — ${st.finalB.toFixed(2)} against
         ${st.finalA.toFixed(2)} — because it is not predicting anything. Here is what it was
         actually asked:`;

    const rows = st.rows.map((pair) => ({ cells: [`<code>${pair[0]}</code>`, `<code>${pair[1]}</code>`] }));
    readout.replaceChildren(
      table(
        [`given this token`, `predict this one — <b>${pick === 'correct' ? 'A' : 'B'}</b>`],
        rows,
        'grid tight'
      )
    );
    const foot = el('p', 'say small');
    foot.innerHTML =
      pick === 'correct'
        ? `That is a prediction: every target is the token that actually came next. Switch to B to
           see what the broken run was asked instead.`
        : `Every target is the token already in the input. The model is being graded on copying,
           which is why the curve looks like a triumph. Switch to A for the real task.`;
    readout.append(foot);
  };

  /* Three ways in — pointer, keyboard focus, and the print path. A reader who never clicks still
   * gets the labelled chart, because `playAll` forces the end state. */
  btnA.addEventListener('click', () => show('correct'));
  btnB.addEventListener('click', () => show('broken'));
  btnA.addEventListener('focus', () => {
    if (chosen === null) ask.classList.add('nudge');
  });
  wrap.playAll = () => show('broken');

  wrap.append(chart, controls, verdict, readout);
  show(null);
  return figure(
    wrap,
    `<b>Neither curve is labelled, and that is the argument.</b> Everything a training dashboard
     shows you about these two runs is on this figure already; if that is enough to tell them apart,
     this page has nothing to say. <b>What would refute it:</b> a broken run whose curve sat
     <i>above</i> the correct one. Then watching the number would be a sufficient check, which is
     exactly what most people believe it is.`
  );
}

/* ============================================================== 2 · glossary */

function chapterGlossary(M) {
  const c = M.config;
  /* The entries are built BEFORE the section, so the heading can count them. A heading that states
   * a number is stating a count of its own contents; typing it is how this page came to say "Eight
   * words" over a list that had grown. */
  const entries = [
    [
      'token',
      `A piece of text the model treats as one unit — often a word, often part of one. This page uses
       the tokenizer from exercise 02, which has ${int(c.vocab_size - 1)} of them.`,
    ],
    [
      'the loss',
      `One number saying how wrong the model's guesses were, averaged over the positions that count.
       Lower is better, and training is the process of making it smaller. A fresh model here scores
       ${M.perplexity.loss.toFixed(4)}.`,
    ],
    [
      'logits',
      `The raw score the model gives every token in the vocabulary, before any of them is turned into
       a probability. One per token, per position: a
       <code>${M.shapes.shapes[2][1].join(' × ')}</code> block for a single batch.`,
    ],
    [
      'the output head',
      `The final layer, turning the model's ${c.d_model}-number thought at each position into one
       score per token. It is <b>${int(M.heads.untied_params)}</b> numbers here — the one matrix in
       the model sized by the tokenizer rather than by the model.`,
    ],
    [
      'tying',
      `Reusing the input word list as the output head, instead of buying a second copy. It costs
       <b>${M.heads.tied_params}</b> extra parameters against
       <b>${int(M.heads.untied_params)}</b> for an untied head, and forces a token's input vector
       and its scoring direction to be the same thing.`,
    ],
    [
      'padding',
      `Filler added to short sequences so a batch is rectangular. It is not a prediction. In the
       example below, ${int(M.padding.dropped)} of ${int(M.padding.positions_before)} positions are
       padding — ${pct(M.padding.dropped / M.padding.positions_before, 0)} of the batch.`,
    ],
    [
      'masking',
      `Excluding positions from the loss. The mask is not the interesting part; the
       <b>contributing count</b> is, because a loss that moved tells you nothing until you know
       whether the set of positions under it moved too. In the padded example below it takes
       ${int(M.padding.positions_before)} positions down to
       <b>${int(M.padding.positions_after)}</b>.`,
    ],
    [
      'perplexity',
      `The loss read as a count: the size of the uniform menu the model behaves as though it were
       choosing from. This model starts at <b>${int(M.perplexity.perplexity)}</b> against a
       vocabulary of ${int(c.vocab_size)}.`,
    ],
    [
      'nats',
      `The unit every loss on this page is in — the natural-log version of bits. Nothing here is
       ever converted, so a gap of <b>${Math.abs(M.training.summary.gap).toFixed(2)}</b> between two
       heads means ${Math.abs(M.training.summary.gap).toFixed(2)} nats and never anything else.`,
    ],
    [
      'the trunk',
      `Everything before the output head: the ${c.n_layer} transformer blocks that turn tokens into
       a ${c.d_model}-number thought per position. <b>${int(M.shapes.trunk_params)}</b> parameters
       here, and it produces no scores at all — that is the head's job, which is why the two are
       priced separately.`,
    ],
    [
      'chunking',
      `Computing the loss a few hundred rows at a time instead of all at once. Which few hundred is
       the whole question: chunk the softmax over logits that already exist and you save the
       intermediates; project <i>inside</i> the loop and the full score tensor never exists, which
       is worth <b>${ratio(M.memory.ratio, M.sensitivity.memory.spread)}</b> here.`,
    ],
    [
      'packing',
      `Putting several documents end to end in one sequence so no row is mostly padding. It creates
       the one thing the loss must then be told to ignore: the <b>join</b> — at position
       ${int(M.boundary.join_position)} in the example below, and the source of the single crossing
       position section 7 costs at ${M.boundary.crossing_loss.toFixed(2)}.`,
    ],
    [
      'the projection',
      `The matmul from the model's ${c.d_model}-number thought to one score per token — the step that
       creates the ${int(M.shapes.shapes[2][1][0] * M.shapes.shapes[2][1][1])}-row scores tensor.
       Where it happens decides the memory: outside a loop the whole tensor exists at once, inside
       one it never does, and that is the difference between the two figures in section 7.`,
    ],
    [
      '▁ (the underscore)',
      `Not a character in the text. The tokenizer writes a leading space this way, so
       <code>▁of</code> is " of" and <code>of</code> is the "of" inside another word. It opens
       <b>${M.shift.correct_pairs.filter((pair) => pair[0].startsWith('▁')).length}</b> of the
       ${int(M.shift.correct_pairs.length)} tokens in the sequence the figures below draw, and is the
       single most confusing thing about reading tokens as strings.`,
    ],
  ];

  const s = section(
    'glossary',
    'glossary',
    'Before anything else',
    `${Spell(entries.length)} words you need, each carrying a number from this run`,
    [
      `Read this once and nothing below is jargon. Every entry carries a real figure from the runs
       on this page rather than a textbook gloss. <b>Every entry below carries a number</b>, which is
       a promise a test can keep; the page used to promise instead that every word in the tiles above
       was defined here, and that was false twice — first for <b>head</b>, <b>logits</b>,
       <b>output head</b> and <b>tokenizer</b>, and then, after those were added, for <b>packed</b>
       and <b>projection</b>. Both are entries now. The claim is gone because nothing could check
       it, and an unfalsifiable promise on a page about checking things is worse than no promise.`,
    ],
    { short: 'The words', sub: `${spell(entries.length)} terms, with our own figures` }
  );

  const dl = el('dl', 'gloss');
  for (const [term, def] of entries) {
    dl.append(el('dt', null, term));
    const dd = el('dd');
    dd.innerHTML = def;
    dl.append(dd);
  }
  s.append(dl);
}

/* ============================================================== 3 · the problem */

function chapterProblem(M) {
  const rows = problemRows(M);
  const s = section(
    'problem',
    'problem',
    'Three lines, four ways to be wrong',
    'The slice that manufactures every answer',
    [
      `Nobody labelled this text. The right answer is simply the next token, so the whole training
       signal is created by a slice. Three lines of code do it — and every one of the
       ${spell(rows.length)} failures below lives inside them.`,
      `<b>None raises an exception. Two of them make the loss look better.</b> That is what makes
       them expensive: they do not announce themselves, and the metric you would use to catch them
       is the metric they improve.`,
    ],
    { short: 'The slice', sub: `${spell(rows.length)} silent failures` }
  );

  s.append(table(['what goes wrong', 'why it is silent', 'what you would see'], rows, 'grid prose'));
  problemTail(M, s);
}

/** The four failures, as data, so the section that introduces them can count them. */
function problemRows(M) {
  return [
    {
      cells: [
        '<b>The shift goes the wrong way</b>',
        'The model is handed its own input as the answer and learns to copy.',
        `<span class="worse">loss falls to ${M.shift.loss_off_by_one ? M.training.summary.final_broken_shift.toFixed(2) : '—'}</span>`,
      ],
      __mark: 'bad',
    },
    {
      cells: [
        '<b>Padding is counted</b>',
        'Filler is trivially predictable, so scoring it rewards the model for nothing.',
        '<span class="worse">loss improves</span>',
      ],
      __mark: 'bad',
    },
    {
      cells: [
        '<b>A packed boundary is predicted across</b>',
        'Two documents joined in one sequence: the gradient asserts a continuation that does not exist.',
        'loss barely moves',
      ],
    },
    {
      cells: [
        '<b>The mean uses the wrong denominator</b>',
        'Dividing by every position rather than the ones that counted scales each batch by how much of it was real.',
        'loss drifts batch to batch',
      ],
    },
  ];
}

/** The paragraph that follows the table, kept beside it rather than inside the row data. */
function problemTail(M, s) {
  const note = el('p', 'say');
  note.innerHTML = `The third and fourth are the ones this exercise got wrong <i>while building the
    page you are reading</i> — the boundary mask kept every pair of padding positions, and a chunked
    loss divided by the wrong count. Both are in <a href="#negatives">the corrections</a>.`;
  s.append(note);
}

/* ============================================================== 4 · mechanism */

function shiftFigure(M) {
  const pairs = M.shift.correct_pairs;
  const broken = M.shift.broken_pairs;
  const n = Math.min(pairs.length, 7);

  /* Cell width is derived from the longest string the figure actually has to hold, not guessed.
   * The first version used a fixed 92px and the token text spilled out of five of seven boxes —
   * which no test caught, because `scrollWidth`/`clientWidth` mean nothing on an SVG <text> and a
   * viewBox check only sees the figure's outer edge. */
  const longest = Math.max(
    ...pairs.slice(0, n).flat().map((s) => s.length),
    ...broken.slice(0, n).flat().map((s) => s.length)
  );
  const cell = Math.max(76, longest * 9 + 26);
  const gap = 8;
  const pad = 18;
  const width = pad * 2 + cell * n;
  const node = svg('svg', {
    viewBox: `0 0 ${width} 348`,
    class: 'fig shiftfig',
    role: 'img',
    'aria-label':
      'Two rows of token strings offset by one, then the same rows with the broken shift, where ' +
      'every token is asked to predict itself',
  });

  const row = (y, items, cls) =>
    items.forEach((text, i) => {
      const x = pad + i * cell;
      node.append(svg('rect', { x, y, width: cell - gap, height: 34, rx: 6, class: `tok ${cls}` }));
      node.append(svgText(x + (cell - gap) / 2, y + 22, 'tok-t', text));
    });

  const label = (y, text) => node.append(svgText(pad, y, 'fig-lab', text));

  const inputs = pairs.slice(0, n).map((p) => p[0]);
  const targets = pairs.slice(0, n).map((p) => p[1]);

  /* The label sits ABOVE where the arrows start, not across them. The first version put it at the
   * midpoint of the gap and the arrows ran straight through the words. */
  label(24, 'correct — the model reads');
  row(34, inputs, 'tok-in');
  label(96, '…and must predict');
  row(130, targets, 'tok-out');

  /* The arrow runs straight down its own column: `targets[i]` is what `inputs[i]` must predict.
   * The offset lives in the DATA — targets is the sequence shifted by one — not in the geometry,
   * and an arrow drawn diagonally would say something the code does not do. */
  for (let i = 0; i < n; i += 1) {
    const x = pad + i * cell + (cell - gap) / 2;
    node.append(svg('path', { d: `M ${x} 106 L ${x} 126`, class: 'lead', 'marker-end': 'url(#arrow)' }));
  }

  const defs = svg('defs');
  const marker = svg('marker', {
    id: 'arrow',
    viewBox: '0 0 8 8',
    refX: 7,
    refY: 4,
    markerWidth: 5,
    markerHeight: 5,
    orient: 'auto',
  });
  marker.append(svg('path', { d: 'M 0 0 L 8 4 L 0 8 z', class: 'arrowhead' }));
  defs.append(marker);
  node.append(defs);

  node.append(
    svg('line', { x1: pad, x2: width - pad, y1: 196, y2: 196, class: 'fig-divide' })
  );

  label(226, 'the off-by-one — the model reads');
  row(236, broken.slice(0, n).map((p) => p[0]), 'tok-in');
  label(298, '…and must predict ITSELF');
  row(306, broken.slice(0, n).map((p) => p[1]), 'tok-bad');

  return node;
}


function chapterMechanism(M) {
  const s = section(
    'mechanism',
    'mechanism',
    'The central object, drawn',
    'Where a target actually comes from',
    [
      `A sequence of <i>T</i> tokens gives <i>T−1</i> supervised pairs at no cost: drop the last
       position, because nothing follows it; drop the first token, because nothing predicts it.
       Everything the model ever learns comes from that offset.`,
      `<b>Which is why an offset in the wrong direction is so expensive.</b> The bottom row of the
       figure is what the broken version asks for — and read as ids rather than as text, it is
       indistinguishable from the correct one.`,
    ],
    { short: 'The shift', sub: 'inputs, targets, and the off-by-one' }
  );

  s.append(
    figure(
      shiftFigure(M),
      `Above the rule: each box is a token the model reads, and the arrow points at what it must
       predict. Below it: <b>the same reading, with the shift reversed</b> — and every arrow would
       now point at the box it started from. <b>Every pair in the bottom half is a token predicting
       itself.</b> That is the entire bug. It is obvious in text and invisible in integers, which is
       why the check is to print the strings. A single pair down there that differed would mean the
       shift was correct after all.`
    )
  );

  /* **All three, because the page is titled after them.** It showed two — the slice — and never
   * wrote the third or named it, so the headline count was the one number on the page a reader
   * could not check against anything. The third is the line that turns the pair into a scalar, and
   * it is where the padding, the boundary mask and the denominator all live. */
  const code = el('pre', 'code');
  code.textContent =
    'inputs  = tokens[:, :-1]        # drop the last: nothing follows it\n' +
    'targets = tokens[:,  1:]        # drop the first: nothing predicts it\n' +
    'loss    = cross_entropy(logits, targets, ignore_index=-100)';
  s.append(code);

  const which = el('p', 'say');
  which.innerHTML = `<b>Those are the three lines, and one failure lives in each of the first two
    while two live in the third.</b> The slice can go the wrong way. It can also be the right way
    and still hand the loss padding to score. And the third line decides <i>which positions count</i>
    — so a mask that keeps the wrong ones, and a mean over the wrong denominator, are both
    <code>cross_entropy</code>'s arguments rather than anything you would see in a shape.`;
  s.append(which);
}

/* ============================================================== 5 · method */

function chapterMethod(M) {
  const c = M.config;
  const run = M.training.run;
  const s = section(
    'method',
    'method',
    'The apparatus',
    'Identical but for one slice',
    [
      `Everything below comes from code that runs top to bottom on a laptop CPU. The model is
       ${c.n_layer} pre-norm blocks at ${c.d_model} wide, scoring a vocabulary of
       ${int(c.vocab_size)}; the corpus is this repository's own conventions document, tokenized
       with exercise 02's tokenizer.`,
      `<b>The comparison holds everything constant except the slice.</b> Same initialisation, same
       batches, same optimiser, same order — so the only thing that differs between the two curves
       is which direction the text was shifted.`,
    ],
    { short: 'The apparatus', sub: 'shapes, seed, and what runs' }
  );

  s.append(
    table(
      ['setting', 'value'],
      [
        { cells: ['model', `${c.n_layer} blocks · ${c.d_model} wide · ${c.n_head} heads`] },
        { cells: ['vocabulary', `${int(c.vocab_size)} (exercise 02's, plus one padding row)`] },
        { cells: ['batch', `${c.batch_size} × ${c.seq_len} tokens`] },
        { cells: ['steps', `${int(run.steps)}, Adam at ${run.learning_rate}`] },
        {
          cells: [
            'corpus',
            `${int(M.training.corpus.corpus_tokens)} tokens, read <b>${M.training.corpus.epochs.toFixed(2)}
             times over</b>`,
          ],
          __mark: 'warn',
        },
      ]
    )
  );

  const caveat = el('p', 'say');
  caveat.innerHTML = `<b>That last row is a limit, not a detail.</b> A corpus read
    ${M.training.corpus.epochs.toFixed(1)} times means every loss on this page is a memorisation number.
    Both findings survive it — each compares two models trained <i>identically</i> on that same
    repeated text, so the repetition cancels — but no absolute value here transfers to a run on
    fresh data.`;
  s.append(caveat);
}

/* ============================================================== 6 · expected */

function chapterExpected(M) {
  const s = section(
    'expected',
    'expected',
    'Written down first',
    'What we expected, including where we were wrong',
    [
      `Writing the prediction down first is the only way a reader can tell a finding from a story
       told backwards — and it costs nothing when the prediction is wrong, which is when it is worth
       the most.`,
    ],
    { short: 'The predictions', sub: 'made before the run, not after' }
  );

  s.append(
    table(
      ['prediction', 'why', 'outcome'],
      [
        {
          cells: [
            'The broken shift will reach a <b>lower</b> loss',
            'Copying the input is trivial to learn; predicting the next token is not.',
            `<b>held</b> — ${M.training.summary.final_broken_shift.toFixed(2)} against
             ${M.training.summary.final_correct_shift.toFixed(2)}`,
          ],
          __mark: 'good',
        },
        {
          cells: [
            'A head predicting <b>t+2</b> will score worse than one predicting t+1',
            'Predicting two positions ahead is genuinely harder.',
            `<b>held</b> — higher on ${M.training.summary.steps_where_further_head_was_higher} of
             ${M.training.summary.total_steps} steps`,
          ],
          __mark: 'good',
        },
        {
          cells: [
            'A fresh model will score exactly <b>ln(V)</b>',
            'A model that knows nothing is uniform over the vocabulary.',
            `<b>did not hold</b> — it scores ${M.perplexity.loss.toFixed(4)} against
             ln(V) = ${M.perplexity.expected_loss.toFixed(4)}`,
          ],
          __mark: 'bad',
        },
      ]
    )
  );

  const note = el('p', 'say');
  note.innerHTML = `<b>The third one is the interesting failure.</b> Random weights are not uniform
    <i>output</i> — the model has arbitrary preferences before it has learned anything, and being
    confidently arbitrary is worse than being uniform. So a fresh model sits
    <b>${pct(M.perplexity.loss / M.perplexity.expected_loss - 1, 1)}</b> above ln(V), at
    ${M.perplexity.loss.toFixed(4)} against ${M.perplexity.expected_loss.toFixed(4)} nats. What
    would signal a real bug is starting far <b>below</b> it.`;
  s.append(note);

  const ratio = el('p', 'say small');
  ratio.innerHTML = `<b>Two ratios live here and they are not the same number, which is the
    section's own instance of this page's thread.</b> In nats the model is
    ${pct(M.perplexity.loss / M.perplexity.expected_loss - 1, 1)} above the uniform floor; read as
    perplexity — a count of menu items rather than a log — the same gap is
    <b>${M.perplexity.ratio_to_vocab.toFixed(3)}×</b> the vocabulary, because exponentiating turns
    a small additive gap into a large multiplicative one. This paragraph published the second figure
    under a sentence about the first, which made a ${pct(M.perplexity.loss / M.perplexity.expected_loss - 1, 1)}
    gap read as a ${pct(M.perplexity.ratio_to_vocab - 1, 1)} one.`;
  s.append(ratio);
}

/* ============================================================== 7 · results */

function curveFigure(M) {
  const correct = M.training.correctShift;
  const broken = M.training.brokenShift;
  const steps = M.training.steps;
  const w = 720;
  const h = 300;
  const padL = 46;
  const padB = 34;
  const padT = 16;
  const padR = 14;

  const all = correct.concat(broken);
  const hi = Math.max(...all);
  const lo = Math.min(...all);
  const x = (i) => padL + (i / (steps.length - 1)) * (w - padL - padR);
  const y = (v) => padT + ((hi - v) / (hi - lo)) * (h - padT - padB);

  const node = svg('svg', {
    viewBox: `0 0 ${w} ${h}`,
    class: 'fig curvefig',
    role: 'img',
    'aria-label':
      'Two training curves. The correctly shifted model levels off while the mis-shifted one falls far below it.',
  });

  for (let g = 0; g <= 4; g += 1) {
    const v = lo + ((hi - lo) * g) / 4;
    node.append(
      svg('line', { x1: padL, x2: w - padR, y1: y(v), y2: y(v), class: 'gridline' }),
      svgText(padL - 8, y(v) + 4, 'axis end', v.toFixed(1))
    );
  }
  node.append(svgText(padL, h - 8, 'axis', 'step 1'));
  node.append(svgText(w - padR, h - 8, 'axis end', `step ${int(steps[steps.length - 1])}`));

  const path = (series, cls) => {
    const d = series.map((v, i) => `${i ? 'L' : 'M'} ${x(i).toFixed(1)} ${y(v).toFixed(1)}`).join(' ');
    node.append(svg('path', { d, class: cls }));
  };
  path(correct, 'curve-correct');
  path(broken, 'curve-broken');

  /* Labels sit where the two curves are furthest apart and are offset AWAY from each other, not
   * at the last point with a 10px nudge — which put "correct shift" straight through its own
   * line. The gap is widest around two-thirds along, which is also where neither label can reach
   * the other curve. */
  const at = Math.floor(steps.length * 0.62);
  node.append(
    svgText(x(at), y(correct[at]) - 16, 'curve-lab correct', 'correct shift'),
    svgText(x(at), y(broken[at]) + 26, 'curve-lab broken', 'off-by-one')
  );
  return node;
}

function chapterResults(M) {
  const t = M.training.summary;
  const s = section(
    'results',
    'results',
    'The ledger',
    'The bug wins, on the only number anyone watches',
    [
      `Two models, identical in every respect but the direction of one slice. The mis-shifted one
       ends <b>${Math.abs(t.broken_shift_advantage).toFixed(2)} nats lower</b> — and it has learned
       nothing except to repeat its own input.`,
    ],
    { short: 'The ledger', sub: 'every number, and what it counts' }
  );

  s.append(
    figure(
      curveFigure(M),
      `The lower curve is the broken model. <b>Nothing about its shape says it is wrong</b> — it
       falls faster, settles lower, and would pass any review that consisted of looking at a loss
       curve. A run where the two curves crossed back, or converged, would mean copying was not
       actually easier than predicting.`
    )
  );

  const seven = [
    {
      cells: [
        '1 · shapes',
        `logits are <b>${M.shapes.logits_to_hidden_ratio.toFixed(1)}×</b> the hidden states that made them`,
      ],
    },
    {
      cells: [
        '2 · the shift',
        `broken trains to <b>${t.final_broken_shift.toFixed(4)}</b>, correct to
         <b>${t.final_correct_shift.toFixed(4)}</b>`,
      ],
      __mark: 'bad',
    },
    {
      cells: [
        '3 · padding',
        `<b>${int(M.padding.positions_after)}</b> of ${int(M.padding.positions_before)} positions
         contribute once padding is masked`,
      ],
    },
    {
      cells: [
        '4 · a packed boundary',
        `<b>${int(M.boundary.boundary_crossings)}</b> crossing of
         ${int(M.boundary.positions_contributing)}, scoring
         ${M.boundary.crossing_loss.toFixed(2)} against a ${M.boundary.loss_unmasked.toFixed(2)} mean`,
      ],
    },
    {
      cells: [
        '5 · perplexity',
        `<b>${int(M.perplexity.perplexity)}</b> against a vocabulary of ${int(M.config.vocab_size)}`,
      ],
    },
    {
      cells: [
        '6 · the head',
        `<b>${int(M.heads.untied_params)}</b> parameters untied, <b>${M.heads.tied_params}</b> tied`,
      ],
    },
    {
      cells: [
        '7 · memory',
        /* **The shape and the baseline belong beside the figure, on a page about what numbers
         * count.** It read "342.0 MiB against 37.6 MiB" and said nothing about what was scored or
         * what was subtracted — while `memory.py`'s own docstring argues that an interpreter with
         * torch loaded is a few hundred megabytes before any work happens, "and a report that did
         * not say so would attribute all of it to the loss". This page was that report. */
        `<b>${mib(M.memory.materialised_bytes)} MiB</b> against
         ${mib(M.memory.chunked_bytes)} MiB — ${ratio(M.memory.ratio, M.sensitivity.memory.spread)},
         losses ${M.memory.losses_agree ? 'identical' : 'DIFFERENT'}.
         <span class="dim">${int(M.memory.rows)} rows × ${int(M.memory.vocab_size)} vocabulary,
         chunked ${int(M.memory.chunk_size)} at a time; peak RSS of a fresh child process, less a
         ${mib(M.memory.baseline_bytes)} MiB baseline that loads torch and allocates nothing</span>`,
      ],
    },
  ];
  s.append(table(['measurement', 'result'], seven));

  const two = el('p', 'say');
  two.innerHTML = `<b>And the second head.</b> One trunk feeding two heads, one predicting the next
    token and one predicting two ahead: they end at ${t.final_by_horizon['1'].toFixed(4)} and
    ${t.final_by_horizon['2'].toFixed(4)}. The further head is worse on
    ${t.steps_where_further_head_was_higher} of ${t.total_steps} steps, by
    ${signed(t.gap)} at the end. The losses simply add — that is the whole of multi-token prediction
    as an objective, and its cost is ${int(M.heads.multi_head_params)} parameters against
    ${int(M.heads.untied_params)} for one head.`;
  s.append(two);

  const noise = el('p', 'say');
  const sens = M.sensitivity;
  noise.innerHTML = `<b>Both findings were checked against a different arbitrary choice.</b> The
    whole run was repeated at ${sens.by_steps.map((r) => int(r.steps)).join(', ')} steps — separate
    runs, not truncations. The gap grows monotonically
    (${sens.gap_grows_monotonically ? 'yes' : 'NO'}), and every run found both effects in the same
    direction. The memory ratio has a floor too: ${sens.memory.repeats} repetitions spread it from
    ${sens.memory.min.toFixed(2)}× to ${sens.memory.max.toFixed(2)}×, a spread of
    ${sens.memory.spread.toFixed(2)}, so it is quoted as
    ${ratio(M.memory.ratio, sens.memory.spread)} everywhere on this page and no finer — the digit
    after the point is not offered, because the spread cannot support it. <b>That was a sentence
    here and not a rule</b>: the tile, the glossary, the ledger and the corrections each chose their
    own precision and two of them quoted hundredths.`;
  s.append(noise);

  const varied = el('p', 'say small');
  varied.innerHTML = `<b>That sweep varies two things, not one, and there is a third it never
    touches.</b> Each step count reads a different amount of the corpus, so the three runs see it
    ${sens.by_steps.map((r) => r.epochs.toFixed(2)).join(', ')} times over — a sweep over steps is
    also a sweep over repetition, which was computed nowhere until it was asked for. And every run
    on this page uses <b>seed ${int(M.training.run.seed)}</b>. It has never been varied, so nothing
    here separates an effect from an initialisation, and the honest reading of "checked against a
    different arbitrary choice" is: one of them.`;
  s.append(varied);
}

/* ============================================================== 8 · negatives */

function chapterNegatives(M) {
  const rows = negativeRows(M);
  const s = section(
    'negatives',
    'negatives',
    'Corrections',
    `${Spell(rows.length)} things this page got wrong, and what each one is an instance of`,
    [
      `Every row here is the same failure as the thesis wearing different arithmetic: a number that
       was correct about a question nobody had asked. <b>None of them was a miscalculation</b>, and
       none of them raised. They are listed with the general shape beside each, because the specific
       bug is only useful if the shape transfers.`,
      `Some were found by writing the code and some by reading the finished work. The second kind
       are the ones worth reading: every one was <b>a claim that read as checked and was not</b>,
       which is the only kind that survives to publication.`,
    ],
    { short: 'The corrections', sub: 'each one an instance of the same thing' }
  );

  s.append(table(['what was wrong', 'the shape, and how it survived'], rows, 'grid prose'));
}

/** The corrections, as data, so the heading can count them. */
function negativeRows(M) {
  return [
    {
      cells: [
        `The boundary count published <b>${int(M.boundary.mask_dropped_including_padding)}</b>
         crossings where there is <b>${int(M.boundary.boundary_crossings)}</b>`,
        `<b class="shape">a right number answering an adjacent question</b> The harness computed the right number on one line and returned the mask's total drop on
         the next — which counts every pair the mask touches, nearly all of them padding pairs
         already removed. It inverted the finding: dozens of positions nudging a mean is a shrug,
         and <b>one</b> position scoring ${M.boundary.crossing_loss.toFixed(2)} against a
         ${M.boundary.loss_unmasked.toFixed(2)} mean is the point.`,
      ],
      __mark: 'bad',
    },
    {
      cells: [
        'The document-boundary mask kept <b>every</b> pair of padding positions',
        `<b class="shape">a guard that agreed with the bug because it shared its expression</b> Padding carries id <code>−1</code>, and <code>−1 == −1</code> is true — so a mask written as
         <code>source == destination</code> reads perfectly and drops nothing but the joins. On the
         published example, 68 of 125 "contributing" positions were padding predicting padding.
         <b>The guard agreed with the bug</b>: it asserted the dropped count equalled a count of
         transitions, which is the expression the implementation used.`,
      ],
      __mark: 'bad',
    },
    {
      cells: [
        'The results document claimed every figure was generated, and fifteen were typed',
        `<b class="shape">a check that could not see the thing it was checking</b> They were the sensitivity and noise-floor numbers — the two blocks the document leans on
         hardest to argue it should be believed. One printed <code>4.15</code> where the generated
         table above read <code>4.1447</code>. The byte-equality test could not see them, because
         they lived <i>inside</i> the template it compared against.`,
      ],
      __mark: 'bad',
    },
    {
      cells: [
        'The memory measurement would have shipped a fiction',
        `<b class="shape">an instrument blind to what it was pointed at</b> The first version used <code>tracemalloc</code>, which is blind to torch: it reported
         <b>429 bytes</b> for an <b>81,928,192-byte</b> logits tensor. Both paths would have come
         back as noise and the published ratio would have been the quotient of two noise figures.`,
      ],
      __mark: 'bad',
    },
    {
      cells: [
        'Chunked cross-entropy divided by the wrong count',
        `<b class="shape">the wrong denominator, invisible on the inputs anyone tested</b> It used the row count rather than the contributing count, so it disagreed with the unchunked
         loss on any masked input. Every test written on unmasked input passed either way, which is
         how it ships.`,
      ],
      __mark: 'bad',
    },
    {
      cells: [
        'Chunking a softmax is not chunking a projection',
        `<b class="shape">one technique's number quoted for another</b> Chunking logits that
         already exist saves only the intermediates —
         <b>${ratio(M.memory.softmax_only_ratio, M.sensitivity.memory.spread)}</b>. Projecting inside the loop, so the full
         tensor never exists, is worth ${ratio(M.memory.ratio, M.sensitivity.memory.spread)}. Quoting the first as the
         second understates the method
         ${(M.memory.ratio / M.memory.softmax_only_ratio).toFixed(1)}-fold. <b>This row itself
         carried a typed figure for weeks</b> — 1.9×, measured by nothing — under a heading about
         quoting the wrong number.`,
      ],
    },
    {
      cells: [
        'A test claimed the head was "most" of a narrow model',
        `<b class="shape">a claim whose subject moved underneath it</b> It is ${pct(M.heads.head_share)}. The test had also inherited whatever the layer count
         defaulted to, so it silently became a different claim when that default moved.`,
      ],
    },
    {
      cells: [
        'Every loss was measured against a file that changes weekly',
        `<b class="shape">a hash that was recorded rather than checked</b> The corpus was this repository's own conventions document, read live at run time, and the
         run recorded a sixteen-character digest that nothing recomputed. By the time anyone
         checked, the file had grown well past the
         <b>${int(M.training.corpus.source_bytes)} bytes</b> these losses were measured on — so
         re-running would have produced different numbers under unchanged documents, silently. That
         revision is frozen now and the digest is recomputed by a test.`,
      ],
      __mark: 'bad',
    },
  ];
}

/* ============================================================== 9 · conclusion */

function chapterConclusion(M) {
  const t = M.training.summary;

  /* One row per opening tile, plus the two the body adds. This is the page's through-line made
   * literal: every finding here is the same failure wearing different arithmetic. It closes the
   * tiles rather than leaving them orphaned -- the previous version of this section spoke to one
   * of four, and a reader who came for the head's share or the memory ratio never learned what
   * either had to do with the shift. */
  const closers = [
    {
      cells: [
        `<b>${t.final_broken_shift.toFixed(2)}</b> against ${t.final_correct_shift.toFixed(2)}`,
        'a better model',
        'an easier question — the broken run is graded on copying its input',
      ],
      __mark: 'bad',
    },
    {
      cells: [
        `<b>${int(M.boundary.mask_dropped_including_padding)}</b> dropped positions`,
        'how much the boundary mask changed',
        `every pair the mask touches. <b>${int(M.boundary.boundary_crossings)}</b> crosses the
         join — at a loss of ${M.boundary.crossing_loss.toFixed(2)}, against
         ${M.boundary.loss_unmasked.toFixed(2)} on average`,
      ],
      __mark: 'bad',
    },
    {
      cells: [
        `<b>${ratio(M.memory.ratio, M.sensitivity.memory.spread)}</b> memory`,
        'what chunking the loss saves',
        `what moving the <i>projection</i> inside the loop saves. The softmax alone:
         ${ratio(M.memory.softmax_only_ratio, M.sensitivity.memory.spread)}`,
      ],
    },
    {
      cells: [
        `<b>${pct(M.heads.head_share)}</b> of the parameters`,
        'how much of this model is the head',
        `how much of head plus an <i>estimated</i> body. Of the trunk actually built:
         ${pct(M.heads.untied_params / (M.heads.untied_params + M.shapes.trunk_params))}`,
      ],
    },
    {
      cells: [
        `<b>${M.perplexity.ratio_to_vocab.toFixed(3)}×</b> the vocabulary`,
        'how far above uniform an untrained model sits',
        `that gap in <i>perplexity</i>. In nats, the unit used everywhere else here:
         ${pct(M.perplexity.loss / M.perplexity.expected_loss - 1, 1)}`,
      ],
    },
  ];

  const s = section(
    'conclusion',
    'conclusion',
    'The verdict',
    'Check what the number is counting',
    [
      `The loss is the thing you are optimising, which makes it the worst available evidence that
       the optimisation is set up correctly. A target-alignment bug does not make it worse — it makes
       it <b>${Math.abs(t.broken_shift_advantage).toFixed(1)} nats better</b>.`,
      `<b>Not one of the ${spell(closers.length)} numbers below was miscalculated.</b> Every one of
       them is arithmetic anyone can check, answering a question nobody asked out loud. That is the
       failure mode worth carrying out of this page: a wrong number gets caught by a reader, and a
       <i>right</i> number answering an adjacent question does not.`,
    ],
    { short: 'The verdict', sub: 'check what the number counts' }
  );

  s.append(
    table(
      ['the number', 'what it looks like it counts', 'what it counts'],
      closers.map((r) => ({ cells: r.cells, __mark: r.__mark })),
      'grid prose'
    )
  );

  const box = el('div', 'takeaway');
  box.innerHTML = `<b>The check that works at step zero.</b> Print the inputs beside the targets as
    <i>strings</i> and read them. Every row should say "this piece is followed by that piece". No
    loss curve can tell you that, because at step zero the broken and correct models score the
    same — and by the time they differ, the broken one looks better. Every other row above has the
    same shape: read the denominator, read the units, read what was in the set.`;
  s.append(box);
}

/* ============================================================== 10 · limits */

function chapterLimits(M) {
  const run = M.training.run;
  const s = section(
    'limits',
    'limits',
    'In the open',
    'What this page cannot tell you',
    [
      `Stated in the open text rather than behind a disclosure, because a limitation a reader has to
       expand is a limitation the page is hiding.`,
    ],
    { short: 'The limits', sub: 'what a laptop run cannot settle' }
  );

  const ul = el('ul', 'limits');
  for (const item of [
    `<b>Nothing about which loss trains a better model.</b> The runs exist to show two specific
     effects. No result here is a quality comparison.`,
    `<b>Every loss is a memorisation number.</b> The corpus is ${int(M.training.corpus.corpus_tokens)}
     tokens read ${M.training.corpus.epochs.toFixed(2)} times over. Both findings survive that — each
     compares two models trained identically on the same repeated text — but the absolute values do
     not transfer to fresh data.`,
    `<b>${int(run.steps)} steps is not a training curve.</b> Both findings are bounded by that
     number, which is why it is stated beside them rather than chosen quietly.`,
    `<b>Perplexity is not comparable across tokenizers, and this page has one.</b> A tokenizer that
     splits more finely is asked an easier question at each step and scores better while being no
     better.`,
  ]) {
    const li = el('li');
    li.innerHTML = item;
    ul.append(li);
  }
  s.append(ul);
}

/* ============================================================== 11 · next */

function chapterNext() {
  const s = section(
    'next',
    'next',
    'The next number to distrust',
    'What the step around the loss does with this',
    [
      `Everything here stops at the scalar. The next exercise builds the step <i>around</i> it — and
       finds two of its own numbers flattering themselves.`,
    ],
    { short: 'What this opens', sub: 'the step around the loss' }
  );

  const ul = el('ul', 'limits');
  for (const item of [
    `<b>The gradient becomes checkable.</b> <code>backward()</code> reports a derivative, and a
     derivative is a claim about what happens when a weight moves — so you can move it and look.`,
    `<b>Gradient accumulation gets broken on purpose.</b> A bug of that shape lived inside every
     major training framework until 2024, because its error is <i>exactly zero</i> whenever the
     micro-batches happen to be the same length.`,
    `<b>Utilisation gets a denominator.</b> Which is where a figure of 39% turned out to be dividing
     one processor's work by another processor's capability.`,
  ]) {
    const li = el('li');
    li.innerHTML = item;
    ul.append(li);
  }
  s.append(ul);
}

/* ============================================================== 12 · reproduce */

/* This section used to be a shell transcript, and it was wrong in four ways at once: it was headed
 * "Three commands" over four of them, it promised a regeneration test that did not exist, it said
 * "the two JSON files" where three are rendered, and it belonged in the README rather than on a
 * page a stranger reads. What reproduces a result is not the command that produced it -- anybody can
 * type a command -- it is knowing which code, which text and which machine answered. So the section
 * shows that instead, and the commands live in the repository where someone who has cloned it is
 * already standing. */
function chapterReproduce(M) {
  const prov = M.sensitivity.provenance;
  const corpus = M.sensitivity.corpus;
  const env = prov.environment;
  const rows = [
    ['which settings', `<code>${prov.config_fingerprint}</code>`, 'every field of the configuration, hashed'],
    ['which code', `<code>${prov.code_digest.slice(0, 19)}…</code>`, 'every module the numbers depend on, in name order'],
    ['which commit', `<code>${prov.git_sha.slice(0, 12)}</code>`, 'the tree it ran from'],
    [
      'which text',
      `<code>${prov.corpus_digest.slice(0, 19)}…</code>`,
      `${int(corpus.corpus_tokens)} tokens, read ${corpus.epochs.toFixed(2)} times over`,
    ],
    ['which vocabulary', `<code>${prov.tokenizer_digest.slice(0, 19)}…</code>`, "exercise 02's frozen BPE"],
    [
      'which machine',
      `${env.platform.split('-').slice(0, 2).join(' ')}`,
      `python ${env.python} · torch ${env.torch} · ${env.torch_threads} threads · ${env.device}`,
    ],
  ];

  const s = section(
    'reproduce',
    'reproduce',
    'Every figure and its parent',
    `${Spell(rows.length)} things that had to be recorded for any of this to be checkable`,
    [
      `A number nobody can regenerate is not evidence, it is folklore. Every figure on this page is
       read from three tracked JSON files, and each of those files carries the block below —
       ${spell(rows.length)} fields naming what produced it. Writing one without them <b>raises</b>;
       it does not warn.`,
      `<b>The corpus is the one worth pausing on.</b> It used to be this repository's own conventions
       file, read live at run time — a file edited on most changes to the repository. Every loss here
       was therefore a function of a moving input, the run recorded a sixteen-character digest that
       nothing recomputed, and by the time anyone looked the file had grown by twelve percent. The
       exact revision is frozen now, so that hash can be <i>recomputed</i> from a clone rather than
       taken on trust.`,
    ],
    { short: 'The index', sub: 'what produced every number here' }
  );

  s.append(
    table(
      ['question', 'answer', 'what it covers'],
      rows.map((r) => ({ cells: [r[0], r[1], r[2]] })),
      'grid'
    )
  );

  const p = el('p', 'say small');
  p.innerHTML = `Digests are shown truncated to fit; the files carry them at full length, which is
    the point — a prefix cannot be checked. The commands that regenerate all of this are in the
    repository's own README, beside the code they run.
    <a href="https://github.com/pankajkr23/llm-pretraining-exercises/tree/main/src/exercises/09-loss-functions-output-heads">Code,
    tests and the full write-up</a>.`;
  s.append(p);
}

/* ============================================================== rail + footer */

function buildRail(root) {
  const rail = document.getElementById('rail');
  if (!rail) return;
  rail.replaceChildren();
  const inner = el('div', 'rail-inner');
  const head = el('div', 'rail-head');
  head.append(el('div', 'rail-title', 'On this page'));
  inner.append(head);
  const list = el('div', 'rail-list');
  const links = new Map();
  for (const sec of root.querySelectorAll('section')) {
    if (!sec.dataset.title) continue;
    const link = el('a', 'rail-link');
    link.href = `#${sec.id}`;
    const body = el('span', 'rail-body');
    body.append(el('span', 'rail-t', sec.dataset.title));
    if (sec.dataset.sub) body.append(el('span', 'rail-sub', sec.dataset.sub));
    /* `rail-n` and `rail-body` are SIBLINGS: `.rail-link` is a two-column grid, and nesting the
     * number inside the body squeezes every title into the 16px number column. */
    link.append(el('span', 'rail-n', sec.dataset.n), body);
    list.append(link);
    links.set(sec.id, link);
  }
  inner.append(list);
  rail.append(inner);
  markPosition(root, links);
}

/* The shared stylesheet has styled `.rail-link.on` since before any of these pages existed, and
 * only exercise 03 ever set it — so 05, 06 and 07 all ship a rail that never says where you are.
 * The observer is registered here, from the code that has already appended the sections, because
 * an IntersectionObserver on a detached node never fires and says nothing. */
function markPosition(root, links) {
  const sections = [...root.querySelectorAll('section')].filter((s) => links.has(s.id));
  if (!sections.length || typeof IntersectionObserver !== 'function') return;

  const visible = new Set();
  const observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) visible.add(entry.target.id);
        else visible.delete(entry.target.id);
      }
      const current = sections.find((s) => visible.has(s.id));
      for (const [id, link] of links) link.classList.toggle('on', Boolean(current) && id === current.id);
    },
    { rootMargin: '-10% 0px -70% 0px', threshold: 0 }
  );
  for (const s of sections) observer.observe(s);
}

function buildFooter() {
  const f = document.getElementById('foot');
  if (!f) return;
  const p = el('p', 'say small');
  p.innerHTML =
    // No count. The heading above the reproduce section was fixed after it read "Three commands"
    // over four of them; this line kept the same wrong number for as long, one screen further down,
    // because nothing connects a footer to the section it summarises.
    'Written for whoever arrives first: the argument is in plain words, and every number behind it ' +
    'is regenerated by the commands in the repository, beside the code they run. ' +
    '<a href="https://github.com/pankajkr23/llm-pretraining-exercises/tree/main/src/exercises/09-loss-functions-output-heads">Code, tests and the full write-up</a>.';
  f.append(p);
}

export function buildPage(M) {
  chapterThesis(M);
  chapterGlossary(M);
  chapterProblem(M);
  chapterMechanism(M);
  chapterMethod(M);
  chapterExpected(M);
  chapterResults(M);
  chapterNegatives(M);
  chapterConclusion(M);
  chapterLimits(M);
  chapterNext();
  chapterReproduce(M);
  buildRail(main());
  buildFooter();
}
