/* Generated by `uv run python -m mixture` — do not edit.
 * Every figure the page renders, precomputed at build time. See export.write_web for
 * why this is a module rather than a JSON file the page fetches. */
export const BUNDLE = Object.freeze({
 "config": {
  "run_tokens": 2000000000000.0,
  "indic_floor": 0.12,
  "agentic_floor": 0.02,
  "protected_ceiling": 0.2,
  "worth_ceiling": 16.4,
  "epochs_near_free": 4,
  "epochs_worthless": 40,
  "repetition_decay": 15.4,
  "fingerprint": "cf555d4cb965",
  "tokenizer": "era5-s2-10k"
 },
 "lanes": [
  {
   "key": "web",
   "name": "General web",
   "share": 0.32,
   "session_share": 0.34,
   "because": "the only lane with real surplus \u2014 4.691T against 640B, 0.14 epochs \u2014 so it funds the two points going to Indic and reasoning. It stays largest because breadth of world knowledge is what MMLU and HLE measure, and nothing else supplies it",
   "schedule_only": false,
   "raw_supply": 4691000000000.0,
   "supply": 4691000000000.0,
   "epochs": 0.13643146450650182,
   "verdict": "surplus",
   "ceiling": 76932400000000.0,
   "funded_by": [
    "DCLM-Baseline",
    "FineWeb-Edu",
    "D2 Web-Diverse",
    "D1 Web-Foundation"
   ],
   "benchmarks": [
    "Humanity's Last Exam",
    "MMLU"
   ],
   "corrections": [],
   "supply_provenance": "estimated"
  },
  {
   "key": "code",
   "name": "Code",
   "share": 0.28,
   "session_share": 0.24,
   "because": "half the stated target capability, and it absorbs the retired long-context slot \u2014 60B of which was repo-packed code from these same corpora. At 560B against 1.103T it runs at 0.51 epochs, so the increase costs no repetition",
   "schedule_only": false,
   "raw_supply": 1103000000000.0,
   "supply": 1103000000000.0,
   "epochs": 0.5077062556663645,
   "verdict": "covered",
   "ceiling": 18089200000000.0,
   "funded_by": [
    "The Stack v2",
    "D3 Code",
    "CommitPack / CommitPackFT"
   ],
   "benchmarks": [
    "SWE-bench Verified",
    "SWE-bench Live / Pro",
    "LiveCodeBench",
    "Aider Polyglot",
    "Codeforces"
   ],
   "corrections": [],
   "supply_provenance": "estimated"
  },
  {
   "key": "indic",
   "name": "Indic",
   "share": 0.18,
   "session_share": 0.16,
   "because": "the differentiator, and the reason the project exists. Two points above the session default buys headroom over the 12% floor rather than sitting on it, at 1.33 epochs \u2014 inside the band where repetition is near-free",
   "schedule_only": false,
   "raw_supply": 270900000000.0,
   "supply": 270900000000.0,
   "epochs": 1.3289036544850499,
   "verdict": "repeat",
   "ceiling": 4442760000000.0,
   "funded_by": [
    "Sangraha (verified)",
    "Sangraha (unverified)",
    "Sangraha (synthetic)",
    "IndicCorpV2",
    "Samanantar",
    "BPCC (parallel)"
   ],
   "benchmarks": [
    "MILU",
    "IndicGenBench"
   ],
   "corrections": [],
   "supply_provenance": "unknown"
  },
  {
   "key": "stem",
   "name": "STEM / math",
   "share": 0.12,
   "session_share": 0.12,
   "because": "unchanged, but on 146B of itemised supply rather than the 250B the session's supply check quotes. That moves it from 0.96 epochs to 1.64 \u2014 still fundable, with no margin left to give away",
   "schedule_only": false,
   "raw_supply": 146000000000.0,
   "supply": 146000000000.0,
   "epochs": 1.643835616438356,
   "verdict": "repeat",
   "ceiling": 2394400000000.0,
   "funded_by": [
    "D4 STEM",
    "peS2o",
    "proof-pile-2"
   ],
   "benchmarks": [
    "AIME 2024 / 2025",
    "FrontierMath",
    "GPQA Diamond",
    "Humanity's Last Exam",
    "MMLU"
   ],
   "corrections": [],
   "supply_provenance": "estimated"
  },
  {
   "key": "reasoning",
   "name": "Reasoning traces",
   "share": 0.08,
   "session_share": 0.06,
   "because": "up two points because this lane reserves a *distribution* of trace lengths, not a quantity. 85.1B is the thinnest real pool in the mixture and 92% of it sits in one V4-lineage dataset, so the band structure has to be bought deliberately",
   "schedule_only": false,
   "raw_supply": 85100000000.0,
   "supply": 85100000000.0,
   "epochs": 1.8801410105757932,
   "verdict": "repeat",
   "ceiling": 1395640000000.0,
   "funded_by": [
    "AON",
    "OpenMathReasoning",
    "OpenThoughts2",
    "NuminaMath",
    "OpenR1-Math"
   ],
   "benchmarks": [
    "LiveCodeBench",
    "Codeforces",
    "AIME 2024 / 2025",
    "FrontierMath",
    "GPQA Diamond",
    "Humanity's Last Exam"
   ],
   "corrections": [],
   "supply_provenance": "estimated"
  },
  {
   "key": "agentic",
   "name": "Agentic / tool-use",
   "share": 0.02,
   "session_share": 0.02,
   "because": "held at the session's floor although supply cannot fund it: 40B against 627M is 3.9x more than infinite repetition could be worth. The share commits to *building* the data, not to holding it \u2014 priced in \u00a78",
   "schedule_only": false,
   "raw_supply": 627000000.0,
   "supply": 67925000.0,
   "epochs": 588.8847994111152,
   "verdict": "impossible",
   "ceiling": 1113970000.0,
   "funded_by": [
    "SWE-Gym",
    "SWE-smith",
    "OpenHands rollouts",
    "ToolBench",
    "ToolACE",
    "Glaive function-calling v2",
    "Nexus / NexusRaven",
    "xLAM / APIGen",
    "Hermes function-calling"
   ],
   "benchmarks": [
    "SWE-bench Verified",
    "SWE-bench Live / Pro",
    "Terminal-Bench",
    "tau-bench / tau2-bench",
    "BFCL v3",
    "GAIA",
    "BrowseComp",
    "WebArena / WorkArena",
    "OSWorld"
   ],
   "corrections": [
    {
     "kind": "supervision",
     "factor": 0.10833333333333334,
     "because": "only the assistant's own tokens are supervised (\u00a76); at 0.3%-10.8% supervised per trajectory, derived from the token-per-sample counts of SWE-smith, OpenHands rollouts, SWE-Gym against the session's 'few hundred supervised tokens'. The generous end is applied, and the lane is impossible without the discount anyway",
     "provenance": "estimated"
    }
   ],
   "supply_provenance": "estimated"
  },
  {
   "key": "long_context",
   "name": "Long-context",
   "share": 0.0,
   "session_share": 0.06,
   "because": "retired as a lane, kept as a capability. 60 of its 100B is repo-packed code already counted under code, so a 6% share would double-count it. It becomes a sequence-length schedule over code, books and web \u2014 its own benchmark, no budget",
   "schedule_only": true,
   "raw_supply": 100000000000.0,
   "supply": 40000000000.0,
   "epochs": 0.0,
   "verdict": "surplus",
   "ceiling": 656000000000.0,
   "funded_by": [
    "Repo-packed code (32K+)",
    "Book-length corpora (packed)"
   ],
   "benchmarks": [
    "GAIA",
    "BrowseComp",
    "long-eval"
   ],
   "corrections": [
    {
     "kind": "double-count",
     "factor": 0.4,
     "because": "60B of the slot's 100B is repo-packed code, which the inventory says is packed from the code corpora already counted in the code lane; only the 40B of packed books is text no other lane holds",
     "provenance": "derived"
    }
   ],
   "supply_provenance": "estimated"
  }
 ],
 "floor": {
  "per_lane": {
   "indic": 0.12,
   "agentic": 0.02
  },
  "total": 0.13999999999999999,
  "ceiling": 0.2
 },
 "indic_tiers": [
  {
   "tier": "A",
   "name": "verified native",
   "share": 0.45,
   "supply": 64000000000.0,
   "rows": [
    "Sangraha (verified)"
   ]
  },
  {
   "tier": "B",
   "name": "unverified crawl",
   "share": 0.2,
   "supply": 44900000000.0,
   "rows": [
    "Sangraha (unverified)",
    "IndicCorpV2"
   ]
  },
  {
   "tier": "C",
   "name": "translated",
   "share": 0.2,
   "supply": 167100000000.0,
   "rows": [
    "Sangraha (synthetic)",
    "Samanantar",
    "BPCC (parallel)"
   ]
  },
  {
   "tier": "D",
   "name": "synthetic",
   "share": 0.15,
   "supply": 0.0,
   "rows": []
  }
 ],
 "tier_dispute": "The inventory's largest Indic row is named \"Sangraha (synthetic)\" and tagged tier **C**, which is\nthe *translated* tier. The name and the tag cannot both be honoured, and which one wins decides\nwhich tier is fundable.\n\nFiled as **translated** (what this spec does): C holds 167.1B against a 72B demand and is covered;\nD holds nothing against 54B, so 54B of Indic must be generated.\n\nFiled as **synthetic**: D holds 162B and is covered; C holds only the 5.1B residual of Samanantar\nand BPCC against 72B, so ~67B of translated Indic must be produced instead.\n\nEither way a hole of roughly the same size opens; filing it under the name rather than the tag\nmoves the hole, it does not fill it. The tag is followed because the tier ladder asks *how was this\ntext produced*, and AI4Bharat's own description of that component is machine translation and\ntransliteration of existing Wikimedia content \u2014 a translation pipeline, not a generative one.\nTier D is reserved for model-generated novel text, of which the inventory lists none.\n",
 "reserve": {
  "total": 39892000000.0,
  "share_of_run": 0.019946,
  "per_lane": {
   "agentic": 627000000.0,
   "indic": 19200000000.0,
   "reasoning": 12765000000.0,
   "stem": 7300000000.0
  }
 },
 "generation_bill": [
  {
   "lane": "indic-D",
   "tokens": 54000000000.0,
   "because": "the synthetic Indic tier has no supply at all: the inventory's one row named 'synthetic' is tagged as translated and is counted in tier C. Tier D is the long-tail language coverage no native corpus provides, so it is generated or the tier is dropped"
  },
  {
   "lane": "agentic",
   "tokens": 38886030000.0,
   "because": "627M of real trajectories cap at 1.1B under infinite repetition, against a 40B share. The existing pool is committed whole to the anneal reserve (627M), so the pre-training share is a commitment to synthesise trajectories and verify them with executable checks"
  }
 ],
 "inventory": [
  {
   "name": "The Stack v2",
   "source": "BigCode / Software Heritage",
   "lane": "code",
   "samples": 600000000.0,
   "tokens": 900000000000.0,
   "licence": "permissive + opt-out",
   "tier": "B",
   "provenance": "approximate"
  },
  {
   "name": "D3 Code",
   "source": "V4 run (confirmed)",
   "lane": "code",
   "samples": 250000000.0,
   "tokens": 199000000000.0,
   "licence": "V4 lineage",
   "tier": null,
   "provenance": "confirmed"
  },
  {
   "name": "CommitPack / CommitPackFT",
   "source": "BigCode",
   "lane": "code",
   "samples": 4000000.0,
   "tokens": 4000000000.0,
   "licence": "mixed / permissive",
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "ToolBench",
   "source": "OpenBMB",
   "lane": "agentic",
   "samples": 120000.0,
   "tokens": 80000000.0,
   "licence": "Apache-2.0",
   "tier": "D",
   "provenance": "approximate"
  },
  {
   "name": "Glaive function-calling v2",
   "source": "Glaive",
   "lane": "agentic",
   "samples": 113000.0,
   "tokens": 50000000.0,
   "licence": null,
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "ToolACE",
   "source": "ToolACE",
   "lane": "agentic",
   "samples": 110000.0,
   "tokens": 60000000.0,
   "licence": null,
   "tier": "A/D",
   "provenance": "approximate"
  },
  {
   "name": "xLAM / APIGen",
   "source": "Salesforce",
   "lane": "agentic",
   "samples": 60000.0,
   "tokens": 25000000.0,
   "licence": "CC-BY (mixed)",
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "Nexus / NexusRaven",
   "source": "Nexusflow",
   "lane": "agentic",
   "samples": 40000.0,
   "tokens": 30000000.0,
   "licence": "CC-BY-4.0",
   "tier": "A",
   "provenance": "approximate"
  },
  {
   "name": "SWE-smith",
   "source": "SWE-smith",
   "lane": "agentic",
   "samples": 26000.0,
   "tokens": 120000000.0,
   "licence": "task licenses",
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "Hermes function-calling",
   "source": "NousResearch",
   "lane": "agentic",
   "samples": 15000.0,
   "tokens": 22000000.0,
   "licence": null,
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "OpenHands rollouts",
   "source": "All-Hands / OpenHands",
   "lane": "agentic",
   "samples": 10000.0,
   "tokens": 90000000.0,
   "licence": "mixed",
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "SWE-Gym",
   "source": "SWE-Gym",
   "lane": "agentic",
   "samples": 2400.0,
   "tokens": 150000000.0,
   "licence": null,
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "AON",
   "source": "V4 corpus",
   "lane": "reasoning",
   "samples": 40000000.0,
   "tokens": 78000000000.0,
   "licence": null,
   "tier": null,
   "provenance": "confirmed"
  },
  {
   "name": "OpenMathReasoning",
   "source": "NVIDIA",
   "lane": "reasoning",
   "samples": 3200000.0,
   "tokens": 2000000000.0,
   "licence": null,
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "OpenThoughts2",
   "source": "OpenThoughts",
   "lane": "reasoning",
   "samples": 1100000.0,
   "tokens": 3000000000.0,
   "licence": null,
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "NuminaMath",
   "source": "Numina",
   "lane": "reasoning",
   "samples": 860000.0,
   "tokens": 500000000.0,
   "licence": "Apache / CC-BY",
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "OpenR1-Math",
   "source": "Hugging Face",
   "lane": "reasoning",
   "samples": 220000.0,
   "tokens": 1600000000.0,
   "licence": null,
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "Repo-packed code (32K+)",
   "source": "packed from code corpora",
   "lane": "long_context",
   "samples": 1500000.0,
   "tokens": 60000000000.0,
   "licence": "permissive",
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "Book-length corpora (packed)",
   "source": "books + long docs",
   "lane": "long_context",
   "samples": 400000.0,
   "tokens": 40000000000.0,
   "licence": "mixed / public-domain",
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "Sangraha (synthetic)",
   "source": "AI4Bharat",
   "lane": "indic",
   "samples": null,
   "tokens": 162000000000.0,
   "licence": null,
   "tier": "C",
   "provenance": "confirmed"
  },
  {
   "name": "Samanantar",
   "source": "AI4Bharat",
   "lane": "indic",
   "samples": 49700000.0,
   "tokens": null,
   "licence": "CC0 / CC-BY",
   "tier": null,
   "provenance": "unstated"
  },
  {
   "name": "Sangraha (verified)",
   "source": "AI4Bharat",
   "lane": "indic",
   "samples": null,
   "tokens": 64000000000.0,
   "licence": null,
   "tier": null,
   "provenance": "confirmed"
  },
  {
   "name": "BPCC (parallel)",
   "source": "AI4Bharat",
   "lane": "indic",
   "samples": null,
   "tokens": null,
   "licence": null,
   "tier": null,
   "provenance": "unstated"
  },
  {
   "name": "Sangraha (unverified)",
   "source": "AI4Bharat",
   "lane": "indic",
   "samples": 15000000.0,
   "tokens": 24000000000.0,
   "licence": null,
   "tier": null,
   "provenance": "confirmed"
  },
  {
   "name": "IndicCorpV2",
   "source": "AI4Bharat",
   "lane": "indic",
   "samples": 10000000.0,
   "tokens": 20900000000.0,
   "licence": "CC-BY / mixed",
   "tier": null,
   "provenance": "confirmed"
  },
  {
   "name": "DCLM-Baseline",
   "source": "DataComp-LM",
   "lane": "web",
   "samples": 2600000000.0,
   "tokens": 2600000000000.0,
   "licence": "mixed / CommonCrawl",
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "FineWeb-Edu",
   "source": "FineWeb-Edu",
   "lane": "web",
   "samples": 1300000000.0,
   "tokens": 1300000000000.0,
   "licence": "ODC-By",
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "D2 Web-Diverse",
   "source": "V4 corpus",
   "lane": "web",
   "samples": 780000000.0,
   "tokens": 627000000000.0,
   "licence": null,
   "tier": null,
   "provenance": "confirmed"
  },
  {
   "name": "D1 Web-Foundation",
   "source": "V4 corpus",
   "lane": "web",
   "samples": 200000000.0,
   "tokens": 164000000000.0,
   "licence": null,
   "tier": null,
   "provenance": "confirmed"
  },
  {
   "name": "D4 STEM",
   "source": "V4 corpus",
   "lane": "stem",
   "samples": null,
   "tokens": 49000000000.0,
   "licence": null,
   "tier": null,
   "provenance": "confirmed"
  },
  {
   "name": "peS2o",
   "source": "AI2",
   "lane": "stem",
   "samples": null,
   "tokens": 42000000000.0,
   "licence": null,
   "tier": null,
   "provenance": "approximate"
  },
  {
   "name": "proof-pile-2",
   "source": "EleutherAI",
   "lane": "stem",
   "samples": 5000000.0,
   "tokens": 55000000000.0,
   "licence": null,
   "tier": null,
   "provenance": "approximate"
  }
 ],
 "headline_disagreements": [
  {
   "lane": "web",
   "itemised": 4691000000000.0,
   "supply_check": 4500000000000.0,
   "slot_headline": null,
   "gap": 191000000000.0,
   "relative": 0.042444444444444444
  },
  {
   "lane": "stem",
   "itemised": 146000000000.0,
   "supply_check": 250000000000.0,
   "slot_headline": null,
   "gap": -104000000000.0,
   "relative": -0.416
  }
 ],
 "supply_check": {
  "code": 1100000000000.0,
  "agentic": 630000000.0,
  "reasoning": 85000000000.0,
  "long_context": 100000000000.0,
  "indic": 276000000000.0,
  "web": 4500000000000.0,
  "stem": 250000000000.0
 },
 "experiment": {
  "device": "mps:apple-silicon",
  "steps": 500,
  "seeds": [
   0,
   1,
   2,
   3,
   4
  ],
  "model": {
   "vocab_size": 10000,
   "context": 256,
   "layers": 4,
   "heads": 4,
   "width": 256,
   "seed": 0
  },
  "corpus": {
   "web": {
    "lane": "web",
    "train_tokens": 100661,
    "heldout_tokens": 10331,
    "heldout_bytes": 59861,
    "unk_share": 0.0,
    "tokenizer": "ours/s02-bpe-10000",
    "content_hash": "aaa7527ab35baea5",
    "sources": [
     "src/exercises/02-tokenization/corpus/v2/en.faithful.txt"
    ]
   },
   "indic": {
    "lane": "indic",
    "train_tokens": 70574,
    "heldout_tokens": 8228,
    "heldout_bytes": 66427,
    "unk_share": 0.0,
    "tokenizer": "ours/s02-bpe-10000",
    "content_hash": "3c2a6a1f3049ff13",
    "sources": [
     "src/exercises/02-tokenization/corpus/v2/hi.faithful.txt",
     "src/exercises/02-tokenization/corpus/v2/te.faithful.txt",
     "src/exercises/02-tokenization/corpus/v2/mai.faithful.txt"
    ]
   },
   "code": {
    "lane": "code",
    "train_tokens": 352415,
    "heldout_tokens": 37162,
    "heldout_bytes": 77843,
    "unk_share": 0.00169157830159378,
    "tokenizer": "ours/s02-bpe-10000",
    "content_hash": "f0b22a2b61027740",
    "sources": [
     "src/exercises/01-introductions/node_modules/flatted/python/flatted.py",
     "src/exercises/01-introductions/tests/test_web_bundle.py",
     "src/exercises/02-tokenization/src/tokenization/__init__.py",
     "src/exercises/02-tokenization/src/tokenization/__main__.py",
     "src/exercises/02-tokenization/src/tokenization/ablate.py",
     "src/exercises/02-tokenization/src/tokenization/bpe_scratch.py",
     "src/exercises/02-tokenization/src/tokenization/config.py",
     "src/exercises/02-tokenization/src/tokenization/corpus.py",
     "src/exercises/02-tokenization/src/tokenization/explainer.py",
     "src/exercises/02-tokenization/src/tokenization/faithfulness.py",
     "src/exercises/02-tokenization/src/tokenization/fourth_language.py",
     "src/exercises/02-tokenization/src/tokenization/holdout.py",
     "src/exercises/02-tokenization/src/tokenization/metrics.py",
     "src/exercises/02-tokenization/src/tokenization/tokenizer.py",
     "src/exercises/02-tokenization/src/tokenization/widget.py",
     "src/exercises/02-tokenization/tests/test_ablate.py",
     "src/exercises/02-tokenization/tests/test_bpe_scratch.py",
     "src/exercises/02-tokenization/tests/test_corpus_paths.py",
     "src/exercises/02-tokenization/tests/test_faithfulness.py",
     "src/exercises/02-tokenization/tests/test_js_encoder.py",
     "src/exercises/02-tokenization/tests/test_metrics.py",
     "src/exercises/02-tokenization/tests/test_submission.py",
     "src/exercises/02-tokenization/tests/test_tokenizer.py",
     "src/exercises/02-tokenization/tests/test_v1_retained.py",
     "src/exercises/02-tokenization/tests/test_widget_render.py",
     "src/exercises/03-data-collection-framework/src/dataframework/__init__.py",
     "src/exercises/03-data-collection-framework/src/dataframework/__main__.py",
     "src/exercises/03-data-collection-framework/src/dataframework/catalog.py",
     "src/exercises/03-data-collection-framework/src/dataframework/config.py",
     "src/exercises/03-data-collection-framework/src/dataframework/coverage.py",
     "src/exercises/03-data-collection-framework/src/dataframework/export.py",
     "src/exercises/03-data-collection-framework/src/dataframework/fertility.py",
     "src/exercises/03-data-collection-framework/src/dataframework/fetch_benchmarks.py",
     "src/exercises/03-data-collection-framework/src/dataframework/gotchas.py",
     "src/exercises/03-data-collection-framework/src/dataframework/grade.py",
     "src/exercises/03-data-collection-framework/src/dataframework/ingest.py",
     "src/exercises/03-data-collection-framework/src/dataframework/measure_fertility.py",
     "src/exercises/03-data-collection-framework/src/dataframework/milestones.py",
     "src/exercises/03-data-collection-framework/src/dataframework/mix.py",
     "src/exercises/03-data-collection-framework/src/dataframework/modalities.py",
     "src/exercises/03-data-collection-framework/src/dataframework/models.py",
     "src/exercises/03-data-collection-framework/src/dataframework/orphans.py",
     "src/exercises/03-data-collection-framework/src/dataframework/run_cost.py",
     "src/exercises/03-data-collection-framework/src/dataframework/shingles.py",
     "src/exercises/03-data-collection-framework/src/dataframework/sourcing.py",
     "src/exercises/03-data-collection-framework/src/dataframework/vocab_sweep.py",
     "src/exercises/03-data-collection-framework/src/dataframework/vocab_trade.py",
     "src/exercises/03-data-collection-framework/tests/test_catalog.py",
     "src/exercises/03-data-collection-framework/tests/test_compute.py",
     "src/exercises/03-data-collection-framework/tests/test_config.py",
     "src/exercises/03-data-collection-framework/tests/test_gotchas.py",
     "src/exercises/03-data-collection-framework/tests/test_ingest.py",
     "src/exercises/03-data-collection-framework/tests/test_invariants.py",
     "src/exercises/03-data-collection-framework/tests/test_models.py",
     "src/exercises/03-data-collection-framework/tests/test_render.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/__init__.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/__main__.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/config.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/corpus.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/decontaminate.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/dedup.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/export.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/fetch.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/formats.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/langid.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/manifest.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/normalize.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/pii.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/pipeline.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/quality.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/records.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/sources.py",
     "src/exercises/04-data-cleaning-dedup/src/datacleaning/tokens.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_agreement.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_bundle.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_decontaminate.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_dedup.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_formats.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_langid.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_normalize.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_notebook.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_page_render.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_pii.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_publication_invariants.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_quality.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_tokens.py",
     "src/exercises/04-data-cleaning-dedup/tests/test_wiring.py"
    ]
   },
   "stem": {
    "lane": "stem",
    "train_tokens": 239401,
    "heldout_tokens": 26532,
    "heldout_bytes": 62545,
    "unk_share": 0.00010153009615276142,
    "tokenizer": "ours/s02-bpe-10000",
    "content_hash": "3bf15d5dfad50f60",
    "sources": [
     "data/proxy/stem.txt"
    ]
   },
   "reasoning": {
    "lane": "reasoning",
    "train_tokens": 558783,
    "heldout_tokens": 61787,
    "heldout_bytes": 138835,
    "unk_share": 0.0020320061105211507,
    "tokenizer": "ours/s02-bpe-10000",
    "content_hash": "e94ee3b9f57bb84a",
    "sources": [
     "data/proxy/reasoning.txt"
    ]
   },
   "agentic": {
    "lane": "agentic",
    "train_tokens": 462378,
    "heldout_tokens": 50273,
    "heldout_bytes": 117411,
    "unk_share": 0.00011118696966741441,
    "tokenizer": "ours/s02-bpe-10000",
    "content_hash": "2fdbbefe6cda6b87",
    "sources": [
     "data/proxy/agentic.txt"
    ]
   }
  },
  "arms": {
   "A": {
    "name": "V5 candidate",
    "effective_shares": {
     "web": 0.32,
     "code": 0.28,
     "indic": 0.18,
     "stem": 0.12,
     "reasoning": 0.08,
     "agentic": 0.02
    },
    "dropped_lanes": [],
    "per_seed": {
     "0": {
      "web": 1.8100504898975072,
      "indic": 1.3417770825627302,
      "code": 3.42611584817298,
      "stem": 3.257834416634853,
      "reasoning": 3.3124211386800795,
      "agentic": 3.1777734457719164
     },
     "1": {
      "web": 1.8128415517366445,
      "indic": 1.3456441675855106,
      "code": 3.432842058070126,
      "stem": 3.2653903619892355,
      "reasoning": 3.3300157786452753,
      "agentic": 3.1926339409718203
     },
     "2": {
      "web": 1.8179532807420828,
      "indic": 1.3278672705884418,
      "code": 3.426395385386095,
      "stem": 3.255488860838764,
      "reasoning": 3.3406406441122183,
      "agentic": 3.180011127529798
     },
     "3": {
      "web": 1.8061182037301566,
      "indic": 1.33243104347266,
      "code": 3.4121890243358837,
      "stem": 3.2575447966188955,
      "reasoning": 3.2957376908253697,
      "agentic": 3.165308945394381
     },
     "4": {
      "web": 1.815249801823518,
      "indic": 1.3316702364688826,
      "code": 3.4338843682961473,
      "stem": 3.2444317165242653,
      "reasoning": 3.314243595840565,
      "agentic": 3.1735056311576866
     }
    },
    "weighted": {
     "0": 2.4995377591229553,
     "1": 2.5056218075305203,
     "2": 2.5016620038317177,
     "3": 2.491078909600961,
     "4": 2.5000096085441568
    }
   },
   "B": {
    "name": "Naive web-heavy",
    "effective_shares": {
     "web": 0.7,
     "code": 0.2,
     "stem": 0.05,
     "indic": 0.03,
     "reasoning": 0.02
    },
    "dropped_lanes": [],
    "per_seed": {
     "0": {
      "web": 1.7887830784704013,
      "indic": 1.4504801643627105,
      "code": 3.5617667453240927,
      "stem": 3.5575731572019875,
      "reasoning": 3.669595271211853,
      "agentic": 3.33267528251124
     },
     "1": {
      "web": 1.7777568008023978,
      "indic": 1.4410888217738418,
      "code": 3.5692266706563363,
      "stem": 3.515669003300362,
      "reasoning": 3.696844428685611,
      "agentic": 3.3329191862386653
     },
     "2": {
      "web": 1.7903993091118213,
      "indic": 1.44039022895029,
      "code": 3.565458931922957,
      "stem": 3.54052820859942,
      "reasoning": 3.641306726310666,
      "agentic": 3.350552779018526
     },
     "3": {
      "web": 1.768663818393679,
      "indic": 1.436947715838558,
      "code": 3.517956896809564,
      "stem": 3.5404921877153286,
      "reasoning": 3.6273542651175714,
      "agentic": 3.302090324631512
     },
     "4": {
      "web": 1.7679641920965525,
      "indic": 1.4366852605780835,
      "code": 3.531408519064637,
      "stem": 3.5162591629327076,
      "reasoning": 3.6116966569685527,
      "agentic": 3.311256944159862
     }
    },
    "weighted": {
     "0": 2.617921609597974,
     "1": 2.6119478503754987,
     "2": 2.613705499782417,
     "3": 2.5907401520714712,
     "4": 2.5902582447056566
    }
   },
   "C": {
    "name": "No protected floor",
    "effective_shares": {
     "indic": 0.04,
     "web": 0.384,
     "code": 0.336,
     "stem": 0.144,
     "reasoning": 0.096
    },
    "dropped_lanes": [],
    "per_seed": {
     "0": {
      "web": 1.8265669232195632,
      "indic": 1.4330988439504246,
      "code": 3.4173343378542227,
      "stem": 3.223669495748988,
      "reasoning": 3.2809495984175654,
      "agentic": 3.249663112260853
     },
     "1": {
      "web": 1.821096529216781,
      "indic": 1.4390250909434863,
      "code": 3.3982514238208075,
      "stem": 3.207387459193881,
      "reasoning": 3.294405021861099,
      "agentic": 3.255675007535542
     },
     "2": {
      "web": 1.8145968465037505,
      "indic": 1.4182586462259317,
      "code": 3.370063228524527,
      "stem": 3.2102695973409356,
      "reasoning": 3.2723229457961316,
      "agentic": 3.2415022233337862
     },
     "3": {
      "web": 1.8153474876933922,
      "indic": 1.4229197233023194,
      "code": 3.385774919112633,
      "stem": 3.198541462164138,
      "reasoning": 3.2676981982087936,
      "agentic": 3.2389918233827704
     },
     "4": {
      "web": 1.8100389600610731,
      "indic": 1.425904304467091,
      "code": 3.368226193092934,
      "stem": 3.1693196033622835,
      "reasoning": 3.2579855295148477,
      "agentic": 3.234934927357591
     }
    },
    "weighted": {
     "0": 2.51362239154902,
     "1": 2.506838201391888,
     "2": 2.491423483000014,
     "3": 2.4950743913918956,
     "4": 2.4846344694014553
    }
   },
   "D": {
    "name": "Indic halved",
    "effective_shares": {
     "indic": 0.09,
     "web": 0.356,
     "code": 0.3115,
     "stem": 0.1335,
     "reasoning": 0.089,
     "agentic": 0.02
    },
    "dropped_lanes": [],
    "per_seed": {
     "0": {
      "web": 1.8161077758168607,
      "indic": 1.3878305147031944,
      "code": 3.39415182194841,
      "stem": 3.214558271817917,
      "reasoning": 3.2764075924625033,
      "agentic": 3.1618387484903585
     },
     "1": {
      "web": 1.8210876986977567,
      "indic": 1.3988434798221367,
      "code": 3.416404860196115,
      "stem": 3.231671566475525,
      "reasoning": 3.3094887076711825,
      "agentic": 3.1868703068437596
     },
     "2": {
      "web": 1.8143586681500405,
      "indic": 1.3712883963848383,
      "code": 3.3953506679117877,
      "stem": 3.231191461660825,
      "reasoning": 3.2976950746684723,
      "agentic": 3.163960999888603
     },
     "3": {
      "web": 1.8041124329016869,
      "indic": 1.37860421713046,
      "code": 3.3864899028402733,
      "stem": 3.211658639220766,
      "reasoning": 3.2668144386491846,
      "agentic": 3.146007291294476
     },
     "4": {
      "web": 1.8108648438041213,
      "indic": 1.377854494566988,
      "code": 3.403356413530029,
      "stem": 3.208694843411905,
      "reasoning": 3.2813669725823016,
      "agentic": 3.1602996157796612
     }
    },
    "weighted": {
     "0": 2.4924228660384826,
     "1": 2.5074303415338117,
     "2": 2.492962673543133,
     "3": 2.4833462480316153,
     "4": 2.4911890861593906
    }
   }
  },
  "comparisons": [
   {
    "key": "H1",
    "claim": "arm A beats arm B on run-weighted held-out bits-per-byte",
    "lane": "weighted",
    "baseline": 2.499582017726062,
    "challenger": 2.6049146713066036,
    "effect": 0.042140106959308914,
    "threshold": 0.02,
    "noise": 0.01106719631367942,
    "verdict": "supported",
    "note": "the challenger is 4.21% worse, past the declared 2%",
    "secondary": null
   },
   {
    "key": "H2",
    "claim": "removing the protected floor makes Indic materially worse",
    "lane": "indic",
    "baseline": 1.3358779601356452,
    "challenger": 1.4278413217778507,
    "effect": 0.06884113997424403,
    "threshold": 0.05,
    "noise": 0.015545166053526323,
    "verdict": "supported",
    "note": "the challenger is 6.88% worse, past the declared 5%",
    "secondary": null
   },
   {
    "key": "H3",
    "claim": "halving Indic costs Indic more than it gains the other lanes",
    "lane": "indic",
    "baseline": 1.3358779601356452,
    "challenger": 1.3828842205215235,
    "effect": 0.03518754091961011,
    "threshold": 0.03,
    "noise": 0.020626946666969827,
    "verdict": "refuted",
    "note": "the primary effect holds (+3.52%), but stem gains 1.12%, past the 1% the refutation condition names, and that gain clears its own seed spread. The condition was declared before the run as: arm D's Indic bits-per-byte is within 3% of arm A's, or the other lanes gain more than 1%. Then 18% is over-provisioned and the share should fall toward the 12% floor.",
    "secondary": {
     "lane": "stem",
     "gain": 0.011235111552675522,
     "noise": 0.007056433986596737,
     "threshold": 0.01,
     "triggered": true,
     "clears_noise": true
    }
   }
  ]
 },
 "followups": {
  "repetition": {
   "reading": {
    "noise_bpb": 0.01578,
    "reference_epochs": 1.15,
    "rungs": [
     {
      "epochs": 18.37,
      "unique_tokens": 111509,
      "excess_bpb_pct": 6.789,
      "beyond_noise": true
     },
     {
      "epochs": 9.18,
      "unique_tokens": 223023,
      "excess_bpb_pct": 5.047,
      "beyond_noise": true
     },
     {
      "epochs": 4.59,
      "unique_tokens": 446050,
      "excess_bpb_pct": 2.86,
      "beyond_noise": true
     },
     {
      "epochs": 2.3,
      "unique_tokens": 892104,
      "excess_bpb_pct": 3.442,
      "beyond_noise": true
     }
    ],
    "inversions": [
     {
      "between_epochs": [
       4.59,
       2.3
      ],
      "gap_bpb": 0.01458,
      "clears_noise": false
     }
    ],
    "shape": "not monotone \u2014 1 adjacent pair(s) run the wrong way, but by less than the seed spread, so the grid is finer than this experiment can resolve there",
    "verdict": "repetition measurably costs held-out loss at this scale",
    "caveat": "Fixed compute, shrinking unique pool. This measures the price of re-reading in this regime; it cannot refute a constant fitted far above it."
   },
   "seeds": [
    0,
    1,
    2
   ]
  },
  "seam": {
   "reading": {
    "claim": "a stage seam with a warmup band spikes gradient norm less than one without",
    "peak_ratio_hard": 1.5189,
    "peak_ratio_banded": 1.4054,
    "noise": 0.1753,
    "verdict": "inconclusive",
    "note": "the +0.114 difference in peak ratio sits inside the 0.175 spread the conditions show against themselves, so this cannot rank them. The difference points the band's way, which is worth nothing on its own and is reported only so the next run knows which way to look.\n\n**More seeds would not settle this**, and that is a property of the rule rather than of the budget: the comparison is against the *sample spread*, which does not shrink with n, not against a standard error, which does. That rule is deliberately conservative and is used everywhere in this repository. Resolving this would need a lower-variance statistic \u2014 the peak is a maximum over a window, which is about the noisiest summary available \u2014 and swapping the statistic after seeing the result would be changing the test rather than gathering more evidence for it. So it stands as inconclusive.",
    "caveat": "Not V4's 150x: different scale, no frozen embeddings, and a band sized to be measurable at 400 steps rather than scaled from the specification's ~0.15% of run."
   },
   "seeds": [
    0,
    1,
    2,
    3,
    4
   ]
  },
  "scale": {
   "reading": {
    "rankings": {
     "1709568": [
      "D",
      "C",
      "A",
      "B"
     ],
     "5785088": [
      "D",
      "A",
      "C",
      "B"
     ],
     "14585856": [
      "D",
      "A",
      "C",
      "B"
     ],
     "30471168": [
      "D",
      "C",
      "A",
      "B"
     ]
    },
    "swapped_pairs": [],
    "real_inversions": [],
    "winner_changed": false,
    "verdict": "assumption survives",
    "note": "no pair reverses between the smallest and largest model, which is the falsifier \u00a77 actually names. The ordering is **not** identical all the way through: 2 intermediate size(s) (5,785,088, 14,585,856) rank the middle of the field differently before it returns. The endpoints agreeing is what was tested; a monotone ranking at every scale is not what was observed",
    "caveat": "A fixed small corpus means larger models overfit sooner; compare final_train_loss against weighted_mean before reading an inversion as a fact about scale."
   },
   "seeds": [
    0,
    1,
    2
   ]
  }
 },
 "sensitivity": {
  "stem_stand_in": "math-ai/StackMathQA (cc-by-4.0)",
  "comparisons": [
   {
    "key": "H3",
    "claim": "halving Indic costs Indic more than it gains the other lanes",
    "lane": "indic",
    "baseline": 1.330642400572209,
    "challenger": 1.3805214465644045,
    "effect": 0.03748493657705945,
    "threshold": 0.03,
    "noise": 0.020499679763793077,
    "verdict": "refuted",
    "note": "the primary effect holds (+3.75%), but stem gains 1.72%, past the 1% the refutation condition names, and that gain clears its own seed spread. The condition was declared before the run as: arm D's Indic bits-per-byte is within 3% of arm A's, or the other lanes gain more than 1%. Then 18% is over-provisioned and the share should fall toward the 12% floor.",
    "secondary": {
     "lane": "stem",
     "gain": 0.017156772874345208,
     "noise": 0.015235553228882504,
     "threshold": 0.01,
     "triggered": true,
     "clears_noise": true
    }
   }
  ]
 }
});
