/* The page, built from the run in data.js.
 *
 * Three rules this file follows:
 *
 *   1. No number is written here. Every figure comes from `M`, generated by
 *      tools/render_results.py from results/run.json. Exercise 09 shipped a document claiming
 *      every figure was generated while fifteen were typed inside the renderer; a page is the
 *      version of that failure the most people see.
 *   2. A mechanism figure is not a results chart. The accumulation bug is the central object here,
 *      so the page draws the two reductions side by side with their real weights — results say what
 *      happened, mechanism says why it must.
 *   3. A failure goes in the opening tiles. This page has three to choose from and it leads with
 *      the worst one.
 *
 * Sections carry `data-role`, so the spine is checkable without pinning any wording.
 */

const NS = 'http://www.w3.org/2000/svg';
const main = () => document.getElementById('main');

function el(tag, cls, text) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
}

function svg(tag, attrs = {}) {
  const n = document.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, String(v));
  return n;
}

function svgText(x, y, cls, text) {
  const t = svg('text', { x, y, class: cls });
  t.textContent = text;
  return t;
}

let sectionCount = 0;

/** A section whose eyebrow names its epistemic role, so a reader knows how to weigh it. */
function section(id, role, eyebrow, title, paras, rail) {
  const s = el('section');
  s.id = id;
  s.dataset.role = role;
  sectionCount += 1;
  s.dataset.n = String(sectionCount);
  s.dataset.title = (rail && rail.short) || title;
  if (rail && rail.sub) s.dataset.sub = rail.sub;
  s.append(el('p', 'role', eyebrow), el('h2', null, title));
  for (const p of [].concat(paras || [])) {
    const n = el('p', 'say');
    n.innerHTML = p;
    s.append(n);
  }
  main().append(s);
  return s;
}

/** A figure whose caption says what to conclude — never a bare label. */
function figure(node, num, caption) {
  const f = el('figure');
  f.append(node);
  const c = el('figcaption');
  c.innerHTML = `<b>Figure ${num}.</b> ${caption}`;
  f.append(c);
  return f;
}

function table(head, rows, cls) {
  const wrap = el('div', 'tablewrap');
  const t = el('table', cls || 'grid');
  const thead = el('thead');
  const hr = el('tr');
  for (const h of head) {
    const th = el('th');
    th.innerHTML = h;
    hr.append(th);
  }
  thead.append(hr);
  t.append(thead);
  const tb = el('tbody');
  for (const row of rows) {
    const tr = el('tr');
    if (row.__mark) tr.className = row.__mark;
    for (const cell of row.cells) {
      const td = el('td');
      td.innerHTML = cell === null || cell === undefined ? '—' : cell;
      tr.append(td);
    }
    tb.append(tr);
  }
  t.append(tb);
  wrap.append(t);
  return wrap;
}

const int = (n) => Math.round(n).toLocaleString('en-US');
const signed = (n, d = 4) => (n >= 0 ? '+' : '−') + Math.abs(n).toFixed(d);
const pct = (n, d = 1) => `${(n * 100).toFixed(d)}%`;

/* ============================================================== 1 · thesis */

function chapterThesis(M) {
  const five = M.item_5_mfu;
  const two = M.item_2_gradient;
  const three = M.item_3_accumulation;
  const s = section(
    'thesis',
    'thesis',
    'The claim',
    'Every number here had to be argued with first',
    [
      `Six checks on a real training loop, and <b>not one of them rewards a low loss</b>. Each is a
       measurement of the loop or a deliberate breakage of it.`,
      `Three of the numbers below were wrong before they were right, and none of the three was
       caught by a failing test. <b>Two were flattering themselves</b> — one in the denominator of a
       ratio, one in its numerator — and the third was a bug in code whose test passed because it
       drove exactly one value.`,
    ],
    { short: 'The claim', sub: 'three numbers argued with' }
  );

  const tiles = el('div', 'tiles');
  for (const [v, k, mark] of [
    [
      '30%',
      'of fp8 inputs came back <b>exactly twice too large</b> from a function whose test passed',
      'bad',
    ],
    [
      pct(five.mfu, 2),
      `utilisation — after a first answer of 39.13% that divided one processor's work by another's capability`,
      'bad',
    ],
    [
      `${two.best_matching_digits.toFixed(1)}`,
      'decimal digits where autograd and hand-computed arithmetic agree, at the best nudge size',
      'good',
    ],
    [
      pct(three.relative_gap),
      'wrong, from a reduction that looks right and is exactly correct whenever you test it casually',
      'good',
    ],
  ]) {
    const tile = el('div', `tile ${mark}`);
    const value = el('div', 'tile-v');
    value.innerHTML = v;
    const key = el('div', 'tile-k');
    key.innerHTML = k;
    tile.append(value, key);
    tiles.append(tile);
  }
  s.append(tiles);

  const note = el('p', 'say small');
  note.innerHTML = `The first two tiles are failures of this page's own work, and they are first
    deliberately. A page that shows only its wins has not earned the ones it shows — and both of
    these were found by asking what a number was actually counting, which is the only technique on
    offer here.`;
  s.append(note);
}

/* ============================================================== 2 · glossary */

function chapterGlossary(M) {
  const facts = M.facts;
  const s = section(
    'glossary',
    'glossary',
    'Vocabulary',
    'Nine words, each with a number from this run',
    [
      `Read this once and nothing below is jargon. Every entry carries a real figure from the run on
       this page rather than a textbook gloss.`,
    ],
    { short: 'Vocabulary', sub: 'nine words, defined once' }
  );

  const entries = [
    [
      'the loss',
      `One number saying how wrong the model's guesses were. Lower is better, and <i>training</i> is
       the process of nudging the model's numbers to make it smaller. This run takes
       ${int(facts.steps)} such nudges.`,
    ],
    [
      'a step',
      `One nudge: read a batch of text, score it, work out which direction each number should move,
       move it. Everything on this page is about a single one of those.`,
    ],
    [
      'the trunk and the head',
      `The model splits in two. The <b>trunk</b> turns text into a vector per position
       (${int(facts.trunk_parameters)} numbers); the <b>head</b> turns each vector into a score for
       every token (${int(facts.head_parameters)}). The split decides which parameters get priced
       in the utilisation figure.`,
    ],
    [
      'a gradient',
      `How much the loss would move if one number moved. <code>backward()</code> computes them all
       at once — and a gradient is a <i>claim</i>, so it can be checked by moving the number and
       looking.`,
    ],
    [
      'the gradient norm',
      `All the gradients as one number: how hard the optimiser is pushing right now. Unlike the
       loss it is not an average over a batch, which is why it moves first.`,
    ],
    [
      'a micro-batch',
      `When the batch you want will not fit in memory, you split it. Each piece is a micro-batch,
       and combining their losses correctly is <a href="#mechanism">the whole of section 4</a>.`,
    ],
    [
      'clipping',
      `Capping the gradient's size so one strange batch cannot throw the model. This run clips at
       ${facts.grad_clip} — and logs the norm <b>before</b> clipping, because a post-clip trace
       flattens at the cap and hides the spikes it exists to show.`,
    ],
    [
      'FLOPs',
      `Floating-point operations — a count of arithmetic. Used here to ask what fraction of the
       machine's capability the run actually used.`,
    ],
    [
      'exponent and mantissa',
      `How a float divides its bits: the <b>exponent</b> fixes the magnitude, the <b>mantissa</b>
       picks the value within it. Exponent bits buy range, mantissa bits buy precision, and more of
       one is always less of the other.`,
    ],
  ];
  const dl = el('dl', 'gloss');
  for (const [term, def] of entries) {
    dl.append(el('dt', null, term));
    const dd = el('dd');
    dd.innerHTML = def;
    dl.append(dd);
  }
  s.append(dl);
}

/* ============================================================== 3 · the problem */

function chapterProblem() {
  const s = section(
    'problem',
    'problem',
    'The problem',
    'The loss is the worst evidence that the loss is set up right',
    [
      `It is the thing being optimised, so it is the one number guaranteed to look better over time
       whether or not anything is correct. Every failure on this page is invisible to it.`,
      `So the six checks below all do the same thing in different clothes: <b>look at an
       intermediate state rather than the outcome</b>. Shapes with their dimensions named. A
       gradient checked against arithmetic. Two reductions run side by side. A norm logged beside
       the loss. A utilisation figure with every input stated. Bit patterns built by hand.`,
    ],
    { short: 'The problem', sub: 'the loss cannot audit itself' }
  );

  s.append(
    table(
      ['the check', 'what it looks at instead of the loss'],
      [
        { cells: ['1 · shapes', 'every tensor in the step, with what each dimension means'] },
        { cells: ['2 · one gradient', 'the same derivative computed two entirely different ways'] },
        { cells: ['3 · accumulation', 'two reductions of identical data, run side by side'] },
        { cells: ['4 · the grad norm', 'a signal that moves before the loss does'] },
        { cells: ['5 · utilisation', 'the arithmetic the step needed against what the machine could do'] },
        { cells: ['6 · float formats', 'the bits themselves'] },
      ]
    )
  );
}

/* ============================================================== 4 · mechanism */

function accumulationFigure(M) {
  const three = M.item_3_accumulation;
  const counts = three.token_counts;
  const losses = three.losses;
  const n = counts.length;

  const w = 640;
  const h = 300;
  const pad = 24;
  /* A gutter the bars never enter, because the sum labels live in it. The first version let the
   * bars run the full width and "= 3.0000" was drawn straight through the third one. */
  const gutter = 96;
  const colw = (w - pad * 2 - gutter) / n;
  const maxTokens = Math.max(...counts);

  const node = svg('svg', {
    viewBox: `0 0 ${w} ${h}`,
    class: 'fig accfig',
    role: 'img',
    'aria-label':
      'Three micro-batches of different sizes, and the two ways of combining their losses — one ' +
      'weighting each by its token count, one giving all three an equal vote',
  });

  node.append(svgText(pad, 22, 'fig-lab', 'three micro-batches, different sizes'));

  counts.forEach((tokens, i) => {
    const x = pad + i * colw;
    const bw = colw - 16;
    /* Width is proportional to the token count, so the short micro-batch LOOKS short. That is the
     * whole mechanism: the wrong reduction gives this narrow box the same vote as the wide ones. */
    const scaled = bw * (tokens / maxTokens);
    node.append(
      svg('rect', { x, y: 36, width: scaled, height: 44, rx: 6, class: 'acc-box' }),
      svgText(x + scaled / 2, 63, 'acc-t', `${tokens} tokens`),
      svgText(x + scaled / 2, 98, 'acc-loss', `loss ${losses[i].toFixed(1)}`)
    );
  });

  node.append(svgText(pad, 140, 'fig-lab', 'correct — every token weighs the same'));
  counts.forEach((tokens, i) => {
    const x = pad + i * colw;
    const bw = (colw - 16) * (tokens / maxTokens);
    node.append(svg('rect', { x, y: 150, width: bw, height: 18, rx: 4, class: 'acc-vote good' }));
  });
  node.append(svgText(w - pad, 164, 'acc-sum end good', `= ${three.correct.toFixed(4)}`));

  node.append(svgText(pad, 206, 'fig-lab', 'wrong — every micro-batch weighs the same'));
  counts.forEach((_, i) => {
    const x = pad + i * colw;
    node.append(
      svg('rect', { x, y: 216, width: colw - 16, height: 18, rx: 4, class: 'acc-vote bad' })
    );
  });
  node.append(svgText(w - pad, 230, 'acc-sum end bad', `= ${three.wrong.toFixed(4)}`));

  node.append(
    svgText(pad, 272, 'acc-gap', `the short batch gets a full vote  →  ${pct(three.relative_gap)} wrong`)
  );

  return node;
}

function chapterMechanism(M) {
  const three = M.item_3_accumulation;
  const s = section(
    'mechanism',
    'mechanism',
    'How it works',
    'Averaging the averages, and why it hid for years',
    [
      `When the batch you want will not fit in memory, you split it into micro-batches, combine
       their losses, and take one step. <b>The combination has to weight each piece by how many real
       tokens it holds.</b>`,
      `Averaging the averages instead gives a micro-batch with ${Math.min(...three.token_counts)}
       tokens exactly the same vote as one with ${Math.max(...three.token_counts)}. On the three
       below that is <b>${pct(three.relative_gap)}</b> wrong.`,
    ],
    { short: 'How it works', sub: 'the bug, drawn' }
  );

  s.append(
    figure(
      accumulationFigure(M),
      1,
      `Each bar's width is its real token count, so the short micro-batch <i>looks</i> short. In the
       correct reduction the bars keep those widths; in the wrong one they are all made equal, and
       the narrow one is handed a vote it did not earn. <b>The error is exactly zero when the three
       bars are already the same width</b> — which is what a hand-built test case almost always
       looks like, and why a bug of this shape lived inside every major training framework until
       2024.`
    )
  );

  const note = el('p', 'say');
  note.innerHTML = `That last sentence is the reason this exercise's configuration is uneven
    <b>by decision</b>, and why the comparison <b>refuses</b> an even one rather than returning a
    gap of zero. A zero here would say the experiment was blind, not that the code is right.`;
  s.append(note);
}

/* ============================================================== 5 · method */

function chapterMethod(M) {
  const f = M.facts;
  const s = section(
    'method',
    'method',
    'How it was measured',
    'One small model, on a laptop, in fp32',
    [
      `Everything here comes from code that runs top to bottom in about half a minute. The model is
       exercise 09's — imported rather than restated, so the two exercises cannot disagree about
       what a loss is.`,
    ],
    { short: 'How it was measured', sub: 'one small model' }
  );

  s.append(
    table(
      ['setting', 'value'],
      [
        { cells: ['model', `${f.n_layer} blocks · ${f.d_model} wide · vocabulary ${int(f.vocab_size)}`] },
        { cells: ['batch', `${f.batch_size} × ${f.seq_len} tokens`] },
        { cells: ['steps', `${int(f.steps)}, Adam at ${f.learning_rate}, clipped at ${f.grad_clip}`] },
        {
          cells: [
            'parameters',
            `${int(f.parameters)} total — <b>${int(f.non_embedding_parameters)}</b> priced for
             utilisation, because ${int(f.embedding_parameters)} of them are embedding tables and a
             lookup does no arithmetic`,
          ],
          __mark: 'warn',
        },
        { cells: ['corpus', f.corpus] },
      ]
    )
  );

  const note = el('p', 'say');
  note.innerHTML = `<b>That highlighted row is section 7's whole argument.</b> An embedding lookup
    reads one stored row per token and performs no arithmetic at all, so counting those parameters
    inflates the work the step supposedly did — by 45%, in the first version of this page's own
    figure.`;
  s.append(note);
}

/* ============================================================== 6 · expected */

function chapterExpected(M) {
  const two = M.item_2_gradient;
  const four = M.item_4_grad_norm;
  const s = section(
    'expected',
    'expected',
    'Stated before running',
    'What we thought would happen',
    [
      `Writing the prediction down first is the only way a reader can tell a finding from a story
       told backwards — and it costs nothing when the prediction is wrong, which is when it is worth
       the most.`,
    ],
    { short: 'Stated first', sub: 'the predictions' }
  );

  s.append(
    table(
      ['prediction', 'outcome'],
      [
        {
          cells: [
            'Autograd and a hand-computed difference will agree to <b>several decimals</b>',
            `<b>held</b> — ${two.best_matching_digits.toFixed(1)} digits at the best nudge size`,
          ],
          __mark: 'good',
        },
        {
          cells: [
            'Agreement will get worse at <b>both</b> ends of the nudge sweep',
            '<b>held</b> — and it took two attempts to measure, because the first test drove a function a difference is <i>exact</i> for',
          ],
          __mark: 'good',
        },
        {
          cells: [
            'There will be a step where the gradient moved and the loss followed later',
            `<b>held, barely</b> — ${four.count} of ${int(M.facts.steps)} steps qualify, and none at all at the strictest threshold`,
          ],
          __mark: 'warn',
        },
        {
          cells: [
            'MFU will be <b>well below</b> 40%',
            `<b>held on the second try</b> — the first answer was 39.13% and was comparing two different processors`,
          ],
          __mark: 'bad',
        },
      ]
    )
  );
}

/* ============================================================== 7 · results */

function sweepFigure(M) {
  const sweep = M.item_2_gradient.sweep;
  const w = 660;
  const h = 300;
  const padL = 54;
  const padB = 46;
  const padT = 34;
  const padR = 20;

  const digits = sweep.map((r) => (r.matching_digits === null ? 16 : r.matching_digits));
  /* The axis spans the data with a margin, not 0..max. Anchoring at zero left the lower half of
   * the chart empty and flattened the very shape the figure exists to show — and this is a count
   * of matching digits, where zero is not a meaningful baseline anyone reads against. */
  const lo = Math.floor(Math.min(...digits)) - 1;
  const hi = Math.ceil(Math.max(...digits)) + 1;
  const x = (i) => padL + (i / (sweep.length - 1)) * (w - padL - padR);
  const y = (v) => padT + ((hi - v) / (hi - lo)) * (h - padT - padB);

  const node = svg('svg', {
    viewBox: `0 0 ${w} ${h}`,
    class: 'fig sweepfig',
    role: 'img',
    'aria-label':
      'Matching decimal digits against nudge size: agreement rises, peaks, then falls again',
  });

  for (let g = 0; g <= 4; g += 1) {
    const v = lo + ((hi - lo) * g) / 4;
    node.append(
      svg('line', { x1: padL, x2: w - padR, y1: y(v), y2: y(v), class: 'gridline' }),
      svgText(padL - 10, y(v) + 4, 'axis end', v.toFixed(0))
    );
  }
  node.append(svgText(padL - 10, padT - 4, 'axis end', 'digits'));

  const d = digits.map((v, i) => `${i ? 'L' : 'M'} ${x(i).toFixed(1)} ${y(v).toFixed(1)}`).join(' ');
  node.append(svg('path', { d, class: 'sweep-line' }));

  const best = digits.indexOf(Math.max(...digits));
  digits.forEach((v, i) => {
    node.append(
      svg('circle', { cx: x(i), cy: y(v), r: i === best ? 6 : 4, class: i === best ? 'dot best' : 'dot' })
    );
    node.append(svgText(x(i), h - padB + 20, 'axis mid', `1e${Math.round(Math.log10(sweep[i].epsilon))}`));
  });
  node.append(svgText(w / 2, h - 8, 'axis mid', 'nudge size'));
  /* Above the point, but inside the padding reserved for it — the first version put it 16px above
   * a peak that was already at the top of the plot, and it rendered clipped by the viewBox. */
  node.append(
    svgText(x(best), Math.max(y(digits[best]) - 16, 16), 'sweep-lab mid',
      `${digits[best].toFixed(1)} digits`)
  );
  node.append(svgText(padL + 4, y(digits[0]) + 22, 'sweep-side', 'too big: a straight line across a curve'));
  node.append(
    svgText(w - padR - 4, y(digits[digits.length - 1]) + 22, 'sweep-side end', 'too small: rounding noise')
  );

  return node;
}

function chapterResults(M) {
  const two = M.item_2_gradient;
  const three = M.item_3_accumulation;
  const four = M.item_4_grad_norm;
  const five = M.item_5_mfu;
  const six = M.item_6_floats;
  const curves = three.curves;

  const s = section(
    'results',
    'results',
    'What happened',
    'Six numbers, and the two that had to be corrected',
    [
      `Every figure below is read from <code>results/run.json</code>. Nothing on this page is typed,
       and a test regenerates the page's data and fails if the tracked copy differs.`,
    ],
    { short: 'What happened', sub: 'six numbers' }
  );

  s.append(
    figure(
      sweepFigure(M),
      2,
      `<b>The shape is the finding, not the peak.</b> A hand-computed derivative draws a straight
       line across a curve — the wider you draw it the less it matches — so agreement improves as
       the nudge shrinks. Then it gets <i>worse</i>, because the two losses being subtracted stop
       differing in bits the float type keeps. There is a <b>window</b>, not a best value, and a
       check that agreed at exactly one nudge size would have been fitted rather than verified.`
    )
  );

  s.append(
    table(
      ['measurement', 'result'],
      [
        {
          cells: [
            '1 · every shape in the step',
            'the loss has <b>no dimensions at all</b> — which is why a mistake anywhere before it changes training without changing a shape',
          ],
        },
        {
          cells: [
            '2 · one gradient, by hand',
            `autograd <b>${two.analytic.toFixed(9)}</b> against <b>${two.numeric.toFixed(9)}</b> — ${two.best_matching_digits.toFixed(1)} matching digits`,
          ],
        },
        {
          cells: [
            '3 · accumulation, broken',
            `<b>${three.correct.toFixed(4)}</b> correct against <b>${three.wrong.toFixed(4)}</b> wrong — ${pct(three.relative_gap)} out`,
          ],
        },
        {
          cells: [
            '4 · the grad norm leading',
            `<b>${four.count}</b> of ${int(M.facts.steps)} steps qualify`,
          ],
          __mark: 'warn',
        },
        {
          cells: [
            '5 · utilisation',
            `<b>${pct(five.mfu, 2)}</b> of ${(five.device_peak_flops / 1e12).toFixed(3)} TFLOP/s measured on this machine`,
          ],
        },
        {
          cells: [
            '6 · 0.1 in three formats',
            `fp32 <code>${six.fp32.hex}</code> · bf16 <code>${six.bf16.hex}</code> · fp8 E4M3 <code>${six['fp8 E4M3'].hex}</code>`,
          ],
        },
      ]
    )
  );

  const acc = el('p', 'say');
  acc.innerHTML = `<b>And the same two reductions driving a real run.</b> Over
    ${int(curves.total_steps)} steps, everything held identical but the reduction, the wrong one
    ends ${signed(curves.final_gap)} away. But the sign is not constant — it reads lower at
    <b>${curves.steps_where_wrong_read_lower}</b> of those steps — so the signed mean
    (${signed(curves.mean_signed_gap)}) is the number that carries a direction, and the endpoint
    alone would be whichever step the run happened to stop on.`;
  s.append(acc);

  const norm = el('p', 'say');
  norm.innerHTML = `<b>The gradient-norm result is the weakest thing on this page and is reported
    that way.</b> A step qualifies only if the norm moved sharply, the loss did not, <i>and</i> the
    loss then followed — the third condition is what makes it a claim about <i>before</i> rather
    than a same-step size comparison. ${four.count} of ${int(M.facts.steps)} steps clear that bar,
    and at the strictest threshold none do.`;
  s.append(norm);
}

/* ============================================================== 8 · negatives */

function chapterNegatives(M) {
  const five = M.item_5_mfu;
  const s = section(
    'negatives',
    'negatives',
    'What did not work',
    'Three numbers that were wrong, and how each survived',
    [
      `None of these was caught by a failing test. Each was caught by asking what a number was
       actually counting — which is the only technique this page has to offer.`,
    ],
    { short: 'What did not work', sub: 'three wrong numbers' }
  );

  s.append(
    table(
      ['what was wrong', 'how it survived'],
      [
        {
          cells: [
            'A float decomposition was correct at <b>0.1</b> and wrong nearly everywhere else',
            `An overflow flag computed from the <i>value's</i> field width rather than a fixed one
             made it return numbers <b>exactly twice too large</b> — on 3.7% of bf16 inputs and 30%
             of fp8 E4M3 inputs, and raise an error on others. <b>0.1 was the whole test</b>, and
             0.1 is one of the values where the bug cannot fire. The check now sweeps 2,000 values
             per format, which immediately found a second limit nobody had reasoned about.`,
          ],
          __mark: 'bad',
        },
        {
          cells: [
            'Utilisation divided one processor’s work by another’s capability',
            `It reported <b>39.13%</b>, which looked excellent. The numerator was measured on the
             CPU and the denominator was a GPU's advertised peak. It is measured now, on the same
             device and dtype as the run, which reports a <i>worse</i> number — the honest direction
             to be wrong in. The current figure is ${pct(five.mfu, 2)}.`,
          ],
          __mark: 'bad',
        },
        {
          cells: [
            'The same figure also counted parameters that do no arithmetic',
            `An embedding lookup is a gather. Counting those tables made the numerator <b>45%
             larger than it should have been</b> — equivalently, removing them cut it by 31%. Both
             describe the same correction, and quoting the wrong one of the pair is how a right
             number ends up answering a different question.`,
          ],
          __mark: 'bad',
        },
        {
          cells: [
            'A heading claimed a lead in time; the measurement was a size comparison',
            `"The gradient moved <i>before</i> the loss" was measured as "the gradient moved a lot
             and the loss moved a little, at the same step". Requiring the loss to actually follow
             cut the count from nine steps to one.`,
          ],
        },
        {
          cells: [
            'Two guards could not fail on the bugs they named',
            `One asserted the accumulation gap's direction at six steps, where the sign is negative
             several times — a coin flip that landed right. The other checked a utilisation ceiling
             against a made-up numerator orders of magnitude below any plausible peak, so it could
             not have failed on the 39.13% defect it was written for.`,
          ],
        },
      ]
    )
  );
}

/* ============================================================== 9 · conclusion */

function chapterConclusion(M) {
  const s = section(
    'conclusion',
    'conclusion',
    'What to take away',
    'Ask what each half of a ratio is counting',
    [
      `Every correction on this page came from the same question, asked about a different number.
       Not "is this arithmetic right" — it was, every time — but <b>"is this quantity the one the
       sentence claims"</b>.`,
      `A wrong number gets caught by a reader. A right number answering an adjacent question does
       not, and it is more convincing precisely <i>because</i> the arithmetic checks out.`,
    ],
    { short: 'What to take away', sub: 'ask what it counts' }
  );

  const box = el('div', 'takeaway');
  box.innerHTML = `<b>The cheapest version of this check.</b> Before quoting a derived figure, say
    out loud what question it answers — then check that it is the question you asked. Utilisation
    of <i>what</i>, on <i>which</i> machine, over <i>which</i> parameters. A decomposition verified
    at how <i>many</i> values. A gradient that moved before the loss, or merely more than it.`;
  s.append(box);
}

/* ============================================================== 10 · limits */

function chapterLimits(M) {
  const five = M.item_5_mfu;
  const s = section(
    'limits',
    'limits',
    'What this cannot establish',
    'Five things this page does not show',
    [
      `In the open text rather than behind a disclosure, because a limitation a reader has to expand
       is a limitation the page is hiding.`,
    ],
    { short: 'What it cannot show', sub: 'five limits' }
  );

  const ul = el('ul', 'limits');
  for (const item of [
    `<b>Nothing about whether the model is any good.</b> Every item measures the loop, not what it
     produced. The losses are incidental.`,
    `<b>${pct(five.mfu, 2)} on a laptop CPU in fp32 is not utilisation on training hardware</b>, and
     comparing it to a published bf16 figure would compare two different quantities.`,
    `<b>The FLOPs estimate is a convention.</b> It excludes attention's quadratic term and treats
     every non-embedding parameter as two forward and four backward operations per token.`,
    `<b>The gradient check verifies one weight</b> — the one with the largest gradient in the head.
     It is evidence about autograd <i>there</i>, not a proof about the whole graph.`,
    `<b>The leading-step count is one reading of an arbitrary threshold.</b> The count at four other
     thresholds is published beside it for exactly that reason, and at the strictest one it is zero.`,
  ]) {
    const li = el('li');
    li.innerHTML = item;
    ul.append(li);
  }
  s.append(ul);
}

/* ============================================================== 11 · next */

function chapterNext() {
  const s = section(
    'next',
    'next',
    'Where this goes',
    'What a real run needs that this does not have',
    [
      `Everything here fits on one machine and finishes in half a minute. Three things change when
       neither is true.`,
    ],
    { short: 'Where this goes', sub: 'what a real run adds' }
  );

  const ul = el('ul', 'limits');
  for (const item of [
    `<b>bf16, and the reason it won.</b> It keeps fp32's eight exponent bits and spends the whole
     saving out of the mantissa — so a gradient that would underflow to zero in fp16 survives, and
     none of fp16's loss-scaling machinery is needed. Gradient descent tolerates imprecision far
     better than it tolerates zeros.`,
    `<b>Sixteen bytes per weight, not four.</b> A finished model needs its weights; training one
     needs the weights, their gradients, a full-precision copy, and the optimiser's two running
     numbers. That arithmetic is why one accelerator stops being enough sooner than most people
     expect.`,
    `<b>Telemetry that survives weeks.</b> A trace worth keeping is one where a spike three days in
     can be traced to the batch that caused it — which the grad-norm log here is the smallest
     possible version of.`,
  ]) {
    const li = el('li');
    li.innerHTML = item;
    ul.append(li);
  }
  s.append(ul);
}

/* ============================================================== 12 · reproduce */

function chapterReproduce() {
  const s = section(
    'reproduce',
    'reproduce',
    'Run it yourself',
    'Two commands',
    [
      `Every figure on this page is generated from the file the first command writes. A test
       regenerates the page's data and fails if the tracked copy differs.`,
    ],
    { short: 'Run it yourself', sub: 'two commands' }
  );

  const pre = el('pre', 'code');
  pre.textContent =
    'uv sync --all-packages --extra train\n' +
    '\n' +
    'uv run python -m trainloop.harness      # all six items -> results/run.json\n' +
    'uv run python src/exercises/10-training-loop/tools/render_results.py';
  s.append(pre);

  const p = el('p', 'say small');
  p.innerHTML =
    'About thirty seconds on a laptop. The notebook runs the same code cell by cell, with the ' +
    'plots. ' +
    '<a href="https://github.com/pankajkr23/llm-pretraining-exercises/tree/main/src/exercises/10-training-loop">Code, tests and the full write-up</a>.';
  s.append(p);
}

/* ============================================================== rail + footer */

function buildRail(root) {
  const rail = document.getElementById('rail');
  if (!rail) return;
  rail.replaceChildren();
  const inner = el('div', 'rail-inner');
  const head = el('div', 'rail-head');
  head.append(el('div', 'rail-title', 'On this page'));
  inner.append(head);
  const list = el('div', 'rail-list');
  const links = new Map();
  for (const sec of root.querySelectorAll('section')) {
    if (!sec.dataset.title) continue;
    const link = el('a', 'rail-link');
    link.href = `#${sec.id}`;
    const body = el('span', 'rail-body');
    body.append(el('span', 'rail-t', sec.dataset.title));
    if (sec.dataset.sub) body.append(el('span', 'rail-sub', sec.dataset.sub));
    link.append(el('span', 'rail-n', sec.dataset.n), body);
    list.append(link);
    links.set(sec.id, link);
  }
  inner.append(list);
  rail.append(inner);
  markPosition(root, links);
}

/* Registered from the code that has already appended the sections: an IntersectionObserver on a
 * detached node never fires and reports nothing, which is how three of exercise 08's plates
 * shipped without ever animating. */
function markPosition(root, links) {
  const sections = [...root.querySelectorAll('section')].filter((s) => links.has(s.id));
  if (!sections.length || typeof IntersectionObserver !== 'function') return;

  const visible = new Set();
  const observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) visible.add(entry.target.id);
        else visible.delete(entry.target.id);
      }
      const current = sections.find((s) => visible.has(s.id));
      for (const [id, link] of links) {
        link.classList.toggle('on', Boolean(current) && id === current.id);
      }
    },
    { rootMargin: '-10% 0px -70% 0px', threshold: 0 }
  );
  for (const s of sections) observer.observe(s);
}

function buildFooter() {
  const f = document.getElementById('foot');
  if (!f) return;
  const p = el('p', 'say small');
  p.innerHTML =
    'Written for whoever arrives first: the argument is in plain words, and every number behind it ' +
    'is two commands away. ' +
    '<a href="https://github.com/pankajkr23/llm-pretraining-exercises/tree/main/src/exercises/10-training-loop">Code, tests and the full write-up</a>.';
  f.append(p);
}

export function buildPage(M) {
  chapterThesis(M);
  chapterGlossary(M);
  chapterProblem();
  chapterMechanism(M);
  chapterMethod(M);
  chapterExpected(M);
  chapterResults(M);
  chapterNegatives(M);
  chapterConclusion(M);
  chapterLimits(M);
  chapterNext();
  chapterReproduce();
  buildRail(main());
  buildFooter();
}
