/* GENERATED by tools/render_results.py. Do not edit.
 *
 * Every number the page draws is in here, read from results/zero.json or computed
 * from it by zerosim.formulas. `chapters.js` holds none of its own.
 */
export const M = {
  "config": {
    "beta1": 0.9,
    "beta2": 0.95,
    "card_bytes": 80000000000,
    "device_flops": 400000000000000.0,
    "eps": 1e-08,
    "inter_node_bandwidth": 50000000000.0,
    "intra_node_bandwidth": 450000000000.0,
    "ladder_params": 30000000000,
    "ladder_world_sizes": [
      8,
      16,
      32,
      64
    ],
    "learning_rate": 0.001,
    "mode": "bf16-mixed",
    "model": {
      "batch_size": 1,
      "chunk_size": 128,
      "d_model": 32,
      "horizons": [
        1,
        2
      ],
      "ignore_index": -100,
      "label_smoothing": 0.0,
      "n_head": 2,
      "n_layer": 2,
      "pad_id": 10000,
      "reference_d_model": 4096,
      "reference_vocab_size": 131072,
      "seq_len": 32,
      "vocab_size": 10001,
      "z_loss_weight": 0.0
    },
    "nodes": 4,
    "seed": 12,
    "steps": 4,
    "weight_decay": 0.1,
    "world_size": 32
  },
  "corpus": {
    "corpus_tokens": 35941,
    "epochs": 0.11396455301744526,
    "source_bytes": 92021,
    "source_digest": "sha256:19f24ce7db26e4f3dde1b3663b6edb19019d887f0188bdaca16ffad7087b0261",
    "tokens_consumed": 4096
  },
  "equivalence": {
    "fp32_grad_step1_max_abs": 1.210719347000122e-08,
    "fp32_grad_step1_scale": 0.0269184373319149,
    "fp32_loss_max_rel": 5.73753076463996e-08,
    "fp32_weights_max_abs_except_key_bias": 6.0051679611206055e-06,
    "fp32_weights_max_abs_key_bias": 2.0398572814883664e-05,
    "key_bias_elements": 64,
    "key_bias_grad_step1_max_abs": 1.1459633242338896e-10,
    "mixed_loss_max_rel": 5.3845497589247885e-05,
    "mixed_update_cosine": 0.9998611211776733,
    "mixed_weights_max_abs": 0.003894335590302944,
    "reference_losses": [
      9.344925880432129,
      9.373157501220703,
      9.335187911987305,
      9.349698066711426
    ],
    "update_rms": 0.002597557147964835
  },
  "generated_by": "src/exercises/12-distributed-training/tools/run_zero.py",
  "ladder": {
    "card_bytes": 80000000000,
    "card_gib": 74.50580596923828,
    "params": 30000000000,
    "payload_bytes": 60000000000,
    "rows": [
      {
        "bytes": 480000000000.0,
        "bytes_per_weight": 16.0,
        "comm_bytes_per_step": 105000000000.0,
        "comm_seconds_per_step": 0.23333333333333334,
        "fits": false,
        "floor_bytes": 480000000000.0,
        "gib": 447.0348358154297,
        "never_fits": true,
        "stage": 0,
        "world_size": 8
      },
      {
        "bytes": 480000000000.0,
        "bytes_per_weight": 16.0,
        "comm_bytes_per_step": 112500000000.0,
        "comm_seconds_per_step": 2.25,
        "fits": false,
        "floor_bytes": 480000000000.0,
        "gib": 447.0348358154297,
        "never_fits": true,
        "stage": 0,
        "world_size": 16
      },
      {
        "bytes": 480000000000.0,
        "bytes_per_weight": 16.0,
        "comm_bytes_per_step": 116250000000.0,
        "comm_seconds_per_step": 2.325,
        "fits": false,
        "floor_bytes": 480000000000.0,
        "gib": 447.0348358154297,
        "never_fits": true,
        "stage": 0,
        "world_size": 32
      },
      {
        "bytes": 480000000000.0,
        "bytes_per_weight": 16.0,
        "comm_bytes_per_step": 118125000000.0,
        "comm_seconds_per_step": 2.3625,
        "fits": false,
        "floor_bytes": 480000000000.0,
        "gib": 447.0348358154297,
        "never_fits": true,
        "stage": 0,
        "world_size": 64
      },
      {
        "bytes": 165000000000.0,
        "bytes_per_weight": 5.5,
        "comm_bytes_per_step": 105000000000.0,
        "comm_seconds_per_step": 0.23333333333333334,
        "fits": false,
        "floor_bytes": 120000000000.0,
        "gib": 153.66822481155396,
        "never_fits": true,
        "stage": 1,
        "world_size": 8
      },
      {
        "bytes": 142500000000.0,
        "bytes_per_weight": 4.75,
        "comm_bytes_per_step": 112500000000.0,
        "comm_seconds_per_step": 2.25,
        "fits": false,
        "floor_bytes": 120000000000.0,
        "gib": 132.7134668827057,
        "never_fits": true,
        "stage": 1,
        "world_size": 16
      },
      {
        "bytes": 131250000000.0,
        "bytes_per_weight": 4.375,
        "comm_bytes_per_step": 116250000000.0,
        "comm_seconds_per_step": 2.325,
        "fits": false,
        "floor_bytes": 120000000000.0,
        "gib": 122.23608791828156,
        "never_fits": true,
        "stage": 1,
        "world_size": 32
      },
      {
        "bytes": 125625000000.0,
        "bytes_per_weight": 4.1875,
        "comm_bytes_per_step": 118125000000.0,
        "comm_seconds_per_step": 2.3625,
        "fits": false,
        "floor_bytes": 120000000000.0,
        "gib": 116.99739843606949,
        "never_fits": true,
        "stage": 1,
        "world_size": 64
      },
      {
        "bytes": 112500000000.0,
        "bytes_per_weight": 3.75,
        "comm_bytes_per_step": 105000000000.0,
        "comm_seconds_per_step": 0.23333333333333334,
        "fits": false,
        "floor_bytes": 60000000000.0,
        "gib": 104.77378964424133,
        "never_fits": false,
        "stage": 2,
        "world_size": 8
      },
      {
        "bytes": 86250000000.0,
        "bytes_per_weight": 2.875,
        "comm_bytes_per_step": 112500000000.0,
        "comm_seconds_per_step": 2.25,
        "fits": false,
        "floor_bytes": 60000000000.0,
        "gib": 80.32657206058502,
        "never_fits": false,
        "stage": 2,
        "world_size": 16
      },
      {
        "bytes": 73125000000.0,
        "bytes_per_weight": 2.4375,
        "comm_bytes_per_step": 116250000000.0,
        "comm_seconds_per_step": 2.325,
        "fits": true,
        "floor_bytes": 60000000000.0,
        "gib": 68.10296326875687,
        "never_fits": false,
        "stage": 2,
        "world_size": 32
      },
      {
        "bytes": 66562500000.0,
        "bytes_per_weight": 2.21875,
        "comm_bytes_per_step": 118125000000.0,
        "comm_seconds_per_step": 2.3625,
        "fits": true,
        "floor_bytes": 60000000000.0,
        "gib": 61.99115887284279,
        "never_fits": false,
        "stage": 2,
        "world_size": 64
      },
      {
        "bytes": 60000000000.0,
        "bytes_per_weight": 2.0,
        "comm_bytes_per_step": 157500000000.0,
        "comm_seconds_per_step": 0.35,
        "fits": true,
        "floor_bytes": 0.0,
        "gib": 55.87935447692871,
        "never_fits": false,
        "stage": 3,
        "world_size": 8
      },
      {
        "bytes": 30000000000.0,
        "bytes_per_weight": 1.0,
        "comm_bytes_per_step": 168750000000.0,
        "comm_seconds_per_step": 3.375,
        "fits": true,
        "floor_bytes": 0.0,
        "gib": 27.939677238464355,
        "never_fits": false,
        "stage": 3,
        "world_size": 16
      },
      {
        "bytes": 15000000000.0,
        "bytes_per_weight": 0.5,
        "comm_bytes_per_step": 174375000000.0,
        "comm_seconds_per_step": 3.4875000000000003,
        "fits": true,
        "floor_bytes": 0.0,
        "gib": 13.969838619232178,
        "never_fits": false,
        "stage": 3,
        "world_size": 32
      },
      {
        "bytes": 7500000000.0,
        "bytes_per_weight": 0.25,
        "comm_bytes_per_step": 177187500000.0,
        "comm_seconds_per_step": 3.5437499999999997,
        "fits": true,
        "floor_bytes": 0.0,
        "gib": 6.984919309616089,
        "never_fits": false,
        "stage": 3,
        "world_size": 64
      }
    ]
  },
  "main_mode": "bf16-mixed",
  "model": {
    "padded": 666560,
    "params": 666560,
    "units": [
      {
        "name": "embed",
        "numel": 321056,
        "padded": 321056,
        "padding": 0,
        "shard": 10033
      },
      {
        "name": "block0",
        "numel": 12704,
        "padded": 12704,
        "padding": 0,
        "shard": 397
      },
      {
        "name": "block1",
        "numel": 12704,
        "padded": 12704,
        "padding": 0,
        "shard": 397
      },
      {
        "name": "head",
        "numel": 320096,
        "padded": 320096,
        "padding": 0,
        "shard": 10003
      }
    ]
  },
  "modes": {
    "bf16-mixed": {
      "0": {
        "communication": {
          "collectives_per_step": 8,
          "comm_seconds_per_step": 5.16584e-05,
          "every_step_identical": true,
          "payload_bytes": 1333120,
          "per_step_link_bytes": {
            "inter": 10331680,
            "intra": 72321760
          },
          "per_step_sent": {
            "all_gather": 1291460,
            "reduce_scatter": 1291460,
            "total": 2582920
          },
          "predicted": {
            "all_gather": 1291460.0,
            "reduce_scatter": 1291460.0,
            "total": 2582920.0
          },
          "ranks_identical": true,
          "sent_by_step": [
            2582920,
            2582920,
            2582920,
            2582920
          ]
        },
        "compute": {
          "backward_flops": 42731392,
          "compute_seconds_per_step": 2.3865296e-07,
          "flops_ranks_identical": true,
          "forward_flops": 21365696,
          "model_flops": 85462784,
          "optimizer_elements": 666560,
          "optimizer_elements_ranks_identical": true,
          "optimizer_flops": 9998400,
          "recompute_flops": 21365696
        },
        "compute_weights_vs_dp": 0.0,
        "losses": [
          9.34492713212967,
          9.373662203550339,
          9.33479768037796,
          9.349654167890549
        ],
        "max_abs_vs_dp": 0.0,
        "memory": {
          "bytes_per_weight": {
            "measured_padded": 16.0,
            "measured_real": 16.0,
            "predicted": 16.0
          },
          "largest_unit_bytes": {
            "grads": 642112,
            "params": 642112
          },
          "measured": {
            "adam_m": 2666240,
            "adam_v": 2666240,
            "grads": 1333120,
            "master": 2666240,
            "params": 1333120,
            "total": 10664960
          },
          "peak_total": 10664960,
          "predicted": {
            "adam_m": 2666240,
            "adam_v": 2666240,
            "grads": 1333120,
            "master": 2666240,
            "params": 1333120,
            "total": 10664960
          },
          "ranks_identical": true,
          "transient_peak": {
            "gathered_params": 0,
            "grad_bucket": 0
          }
        },
        "name": "DP (stage 0)",
        "time_model": {
          "comm_seconds": 5.16584e-05,
          "compute_seconds": 2.3865296e-07,
          "total_seconds": 5.189705296e-05
        }
      },
      "1": {
        "communication": {
          "collectives_per_step": 8,
          "comm_seconds_per_step": 5.16584e-05,
          "every_step_identical": true,
          "payload_bytes": 1333120,
          "per_step_link_bytes": {
            "inter": 10331680,
            "intra": 72321760
          },
          "per_step_sent": {
            "all_gather": 1291460,
            "reduce_scatter": 1291460,
            "total": 2582920
          },
          "predicted": {
            "all_gather": 1291460.0,
            "reduce_scatter": 1291460.0,
            "total": 2582920.0
          },
          "ranks_identical": true,
          "sent_by_step": [
            2582920,
            2582920,
            2582920,
            2582920
          ]
        },
        "compute": {
          "backward_flops": 42731392,
          "compute_seconds_per_step": 2.14438085e-07,
          "flops_ranks_identical": true,
          "forward_flops": 21365696,
          "model_flops": 85462784,
          "optimizer_elements": 20830,
          "optimizer_elements_ranks_identical": true,
          "optimizer_flops": 312450,
          "recompute_flops": 21365696
        },
        "compute_weights_vs_dp": 0.0,
        "losses": [
          9.34492713212967,
          9.373662203550339,
          9.33479768037796,
          9.349654167890549
        ],
        "max_abs_vs_dp": 0.0,
        "memory": {
          "bytes_per_weight": {
            "measured_padded": 4.375,
            "measured_real": 4.375,
            "predicted": 4.375
          },
          "largest_unit_bytes": {
            "grads": 642112,
            "params": 642112
          },
          "measured": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 1333120,
            "master": 83320,
            "params": 1333120,
            "total": 2916200
          },
          "peak_total": 2916200,
          "predicted": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 1333120,
            "master": 83320,
            "params": 1333120,
            "total": 2916200
          },
          "ranks_identical": true,
          "transient_peak": {
            "gathered_params": 0,
            "grad_bucket": 0
          }
        },
        "name": "ZeRO-1",
        "time_model": {
          "comm_seconds": 5.16584e-05,
          "compute_seconds": 2.14438085e-07,
          "total_seconds": 5.1872838085e-05
        }
      },
      "2": {
        "communication": {
          "collectives_per_step": 8,
          "comm_seconds_per_step": 5.16584e-05,
          "every_step_identical": true,
          "payload_bytes": 1333120,
          "per_step_link_bytes": {
            "inter": 10331680,
            "intra": 72321760
          },
          "per_step_sent": {
            "all_gather": 1291460,
            "reduce_scatter": 1291460,
            "total": 2582920
          },
          "predicted": {
            "all_gather": 1291460.0,
            "reduce_scatter": 1291460.0,
            "total": 2582920.0
          },
          "ranks_identical": true,
          "sent_by_step": [
            2582920,
            2582920,
            2582920,
            2582920
          ]
        },
        "compute": {
          "backward_flops": 42731392,
          "compute_seconds_per_step": 2.14438085e-07,
          "flops_ranks_identical": true,
          "forward_flops": 21365696,
          "model_flops": 85462784,
          "optimizer_elements": 20830,
          "optimizer_elements_ranks_identical": true,
          "optimizer_flops": 312450,
          "recompute_flops": 21365696
        },
        "compute_weights_vs_dp": 0.0,
        "losses": [
          9.34492713212967,
          9.373662203550339,
          9.33479768037796,
          9.349654167890549
        ],
        "max_abs_vs_dp": 0.0,
        "memory": {
          "bytes_per_weight": {
            "measured_padded": 2.4375,
            "measured_real": 2.4375,
            "predicted": 2.4375
          },
          "largest_unit_bytes": {
            "grads": 642112,
            "params": 642112
          },
          "measured": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 41660,
            "master": 83320,
            "params": 1333120,
            "total": 1624740
          },
          "peak_total": 2266852,
          "predicted": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 41660,
            "master": 83320,
            "params": 1333120,
            "total": 1624740
          },
          "ranks_identical": true,
          "transient_peak": {
            "gathered_params": 0,
            "grad_bucket": 642112
          }
        },
        "name": "ZeRO-2",
        "time_model": {
          "comm_seconds": 5.16584e-05,
          "compute_seconds": 2.14438085e-07,
          "total_seconds": 5.1872838085e-05
        }
      },
      "3": {
        "communication": {
          "collectives_per_step": 12,
          "comm_seconds_per_step": 7.74876e-05,
          "every_step_identical": true,
          "payload_bytes": 1333120,
          "per_step_link_bytes": {
            "inter": 15497520,
            "intra": 108482640
          },
          "per_step_sent": {
            "all_gather": 2582920,
            "reduce_scatter": 1291460,
            "total": 3874380
          },
          "predicted": {
            "all_gather": 2582920.0,
            "reduce_scatter": 1291460.0,
            "total": 3874380.0
          },
          "ranks_identical": true,
          "sent_by_step": [
            3874380,
            3874380,
            3874380,
            3874380
          ]
        },
        "compute": {
          "backward_flops": 42731392,
          "compute_seconds_per_step": 2.14438085e-07,
          "flops_ranks_identical": true,
          "forward_flops": 21365696,
          "model_flops": 85462784,
          "optimizer_elements": 20830,
          "optimizer_elements_ranks_identical": true,
          "optimizer_flops": 312450,
          "recompute_flops": 21365696
        },
        "compute_weights_vs_dp": 0.0,
        "losses": [
          9.34492713212967,
          9.373662203550339,
          9.33479768037796,
          9.349654167890549
        ],
        "max_abs_vs_dp": 0.0,
        "memory": {
          "bytes_per_weight": {
            "measured_padded": 0.5,
            "measured_real": 0.5,
            "predicted": 0.5
          },
          "largest_unit_bytes": {
            "grads": 642112,
            "params": 642112
          },
          "measured": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 41660,
            "master": 83320,
            "params": 41660,
            "total": 333280
          },
          "peak_total": 975392,
          "predicted": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 41660,
            "master": 83320,
            "params": 41660,
            "total": 333280
          },
          "ranks_identical": true,
          "transient_peak": {
            "gathered_params": 642112,
            "grad_bucket": 642112
          }
        },
        "name": "ZeRO-3",
        "time_model": {
          "comm_seconds": 7.74876e-05,
          "compute_seconds": 2.14438085e-07,
          "total_seconds": 7.770203808499999e-05
        }
      }
    },
    "fp32": {
      "0": {
        "communication": {
          "collectives_per_step": 8,
          "comm_seconds_per_step": 0.0001033168,
          "every_step_identical": true,
          "payload_bytes": 2666240,
          "per_step_link_bytes": {
            "inter": 20663360,
            "intra": 144643520
          },
          "per_step_sent": {
            "all_gather": 2582920,
            "reduce_scatter": 2582920,
            "total": 5165840
          },
          "predicted": {
            "all_gather": 2582920.0,
            "reduce_scatter": 2582920.0,
            "total": 5165840.0
          },
          "ranks_identical": true,
          "sent_by_step": [
            5165840,
            5165840,
            5165840,
            5165840
          ]
        },
        "compute_weights_vs_dp": 0.0,
        "losses": [
          9.344925940036774,
          9.373157232999802,
          9.335187792778015,
          9.349697530269623
        ],
        "max_abs_vs_dp": 0.0,
        "memory": {
          "bytes_per_weight": {
            "measured_padded": 16.0,
            "measured_real": 16.0,
            "predicted": 16.0
          },
          "largest_unit_bytes": {
            "grads": 1284224,
            "params": 1284224
          },
          "measured": {
            "adam_m": 2666240,
            "adam_v": 2666240,
            "grads": 2666240,
            "master": 0,
            "params": 2666240,
            "total": 10664960
          },
          "peak_total": 10664960,
          "predicted": {
            "adam_m": 2666240,
            "adam_v": 2666240,
            "grads": 2666240,
            "master": 0,
            "params": 2666240,
            "total": 10664960
          },
          "ranks_identical": true,
          "transient_peak": {
            "gathered_params": 0,
            "grad_bucket": 0
          }
        },
        "name": "DP (stage 0)"
      },
      "1": {
        "communication": {
          "collectives_per_step": 8,
          "comm_seconds_per_step": 0.0001033168,
          "every_step_identical": true,
          "payload_bytes": 2666240,
          "per_step_link_bytes": {
            "inter": 20663360,
            "intra": 144643520
          },
          "per_step_sent": {
            "all_gather": 2582920,
            "reduce_scatter": 2582920,
            "total": 5165840
          },
          "predicted": {
            "all_gather": 2582920.0,
            "reduce_scatter": 2582920.0,
            "total": 5165840.0
          },
          "ranks_identical": true,
          "sent_by_step": [
            5165840,
            5165840,
            5165840,
            5165840
          ]
        },
        "compute_weights_vs_dp": 0.0,
        "losses": [
          9.344925940036774,
          9.373157232999802,
          9.335187792778015,
          9.349697530269623
        ],
        "max_abs_vs_dp": 0.0,
        "memory": {
          "bytes_per_weight": {
            "measured_padded": 8.25,
            "measured_real": 8.25,
            "predicted": 8.25
          },
          "largest_unit_bytes": {
            "grads": 1284224,
            "params": 1284224
          },
          "measured": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 2666240,
            "master": 0,
            "params": 2666240,
            "total": 5499120
          },
          "peak_total": 5499120,
          "predicted": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 2666240,
            "master": 0,
            "params": 2666240,
            "total": 5499120
          },
          "ranks_identical": true,
          "transient_peak": {
            "gathered_params": 0,
            "grad_bucket": 0
          }
        },
        "name": "ZeRO-1"
      },
      "2": {
        "communication": {
          "collectives_per_step": 8,
          "comm_seconds_per_step": 0.0001033168,
          "every_step_identical": true,
          "payload_bytes": 2666240,
          "per_step_link_bytes": {
            "inter": 20663360,
            "intra": 144643520
          },
          "per_step_sent": {
            "all_gather": 2582920,
            "reduce_scatter": 2582920,
            "total": 5165840
          },
          "predicted": {
            "all_gather": 2582920.0,
            "reduce_scatter": 2582920.0,
            "total": 5165840.0
          },
          "ranks_identical": true,
          "sent_by_step": [
            5165840,
            5165840,
            5165840,
            5165840
          ]
        },
        "compute_weights_vs_dp": 0.0,
        "losses": [
          9.344925940036774,
          9.373157232999802,
          9.335187792778015,
          9.349697530269623
        ],
        "max_abs_vs_dp": 0.0,
        "memory": {
          "bytes_per_weight": {
            "measured_padded": 4.375,
            "measured_real": 4.375,
            "predicted": 4.375
          },
          "largest_unit_bytes": {
            "grads": 1284224,
            "params": 1284224
          },
          "measured": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 83320,
            "master": 0,
            "params": 2666240,
            "total": 2916200
          },
          "peak_total": 4200424,
          "predicted": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 83320,
            "master": 0,
            "params": 2666240,
            "total": 2916200
          },
          "ranks_identical": true,
          "transient_peak": {
            "gathered_params": 0,
            "grad_bucket": 1284224
          }
        },
        "name": "ZeRO-2"
      },
      "3": {
        "communication": {
          "collectives_per_step": 12,
          "comm_seconds_per_step": 0.0001549752,
          "every_step_identical": true,
          "payload_bytes": 2666240,
          "per_step_link_bytes": {
            "inter": 30995040,
            "intra": 216965280
          },
          "per_step_sent": {
            "all_gather": 5165840,
            "reduce_scatter": 2582920,
            "total": 7748760
          },
          "predicted": {
            "all_gather": 5165840.0,
            "reduce_scatter": 2582920.0,
            "total": 7748760.0
          },
          "ranks_identical": true,
          "sent_by_step": [
            7748760,
            7748760,
            7748760,
            7748760
          ]
        },
        "compute_weights_vs_dp": 0.0,
        "losses": [
          9.344925940036774,
          9.373157232999802,
          9.335187792778015,
          9.349697530269623
        ],
        "max_abs_vs_dp": 0.0,
        "memory": {
          "bytes_per_weight": {
            "measured_padded": 0.5,
            "measured_real": 0.5,
            "predicted": 0.5
          },
          "largest_unit_bytes": {
            "grads": 1284224,
            "params": 1284224
          },
          "measured": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 83320,
            "master": 0,
            "params": 83320,
            "total": 333280
          },
          "peak_total": 1617504,
          "predicted": {
            "adam_m": 83320,
            "adam_v": 83320,
            "grads": 83320,
            "master": 0,
            "params": 83320,
            "total": 333280
          },
          "ranks_identical": true,
          "transient_peak": {
            "gathered_params": 1284224,
            "grad_bucket": 1284224
          }
        },
        "name": "ZeRO-3"
      }
    }
  },
  "page": {
    "all_comm_equal": true,
    "all_identical_to_dp": true,
    "all_memory_equal": true,
    "all_ranks_identical": true,
    "comm_multiple": {
      "bf16-mixed": {
        "0": 2.0,
        "1": 2.0,
        "2": 2.0,
        "3": 3.0
      },
      "fp32": {
        "0": 2.0,
        "1": 2.0,
        "2": 2.0,
        "3": 3.0
      }
    },
    "dp_bytes_over_zero3": 32.0,
    "formula": {
      "bf16-mixed": {
        "0": {
          "at_world": {
            "adam_m": 4.0,
            "adam_v": 4.0,
            "grads": 2.0,
            "master": 4.0,
            "params": 2.0,
            "total": 16.0
          },
          "floor": 16.0,
          "grad_slice_only": false,
          "sharded": {
            "adam_m": false,
            "adam_v": false,
            "grads": false,
            "master": false,
            "params": false
          }
        },
        "1": {
          "at_world": {
            "adam_m": 0.125,
            "adam_v": 0.125,
            "grads": 2.0,
            "master": 0.125,
            "params": 2.0,
            "total": 4.375
          },
          "floor": 4.0,
          "grad_slice_only": true,
          "sharded": {
            "adam_m": true,
            "adam_v": true,
            "grads": false,
            "master": true,
            "params": false
          }
        },
        "2": {
          "at_world": {
            "adam_m": 0.125,
            "adam_v": 0.125,
            "grads": 0.0625,
            "master": 0.125,
            "params": 2.0,
            "total": 2.4375
          },
          "floor": 2.0,
          "grad_slice_only": false,
          "sharded": {
            "adam_m": true,
            "adam_v": true,
            "grads": true,
            "master": true,
            "params": false
          }
        },
        "3": {
          "at_world": {
            "adam_m": 0.125,
            "adam_v": 0.125,
            "grads": 0.0625,
            "master": 0.125,
            "params": 0.0625,
            "total": 0.5
          },
          "floor": 0.0,
          "grad_slice_only": false,
          "sharded": {
            "adam_m": true,
            "adam_v": true,
            "grads": true,
            "master": true,
            "params": true
          }
        }
      },
      "fp32": {
        "0": {
          "at_world": {
            "adam_m": 4.0,
            "adam_v": 4.0,
            "grads": 4.0,
            "master": 0.0,
            "params": 4.0,
            "total": 16.0
          },
          "floor": 16.0,
          "grad_slice_only": false,
          "sharded": {
            "adam_m": false,
            "adam_v": false,
            "grads": false,
            "master": false,
            "params": false
          }
        },
        "1": {
          "at_world": {
            "adam_m": 0.125,
            "adam_v": 0.125,
            "grads": 4.0,
            "master": 0.0,
            "params": 4.0,
            "total": 8.25
          },
          "floor": 8.0,
          "grad_slice_only": true,
          "sharded": {
            "adam_m": true,
            "adam_v": true,
            "grads": false,
            "master": true,
            "params": false
          }
        },
        "2": {
          "at_world": {
            "adam_m": 0.125,
            "adam_v": 0.125,
            "grads": 0.125,
            "master": 0.0,
            "params": 4.0,
            "total": 4.375
          },
          "floor": 4.0,
          "grad_slice_only": false,
          "sharded": {
            "adam_m": true,
            "adam_v": true,
            "grads": true,
            "master": true,
            "params": false
          }
        },
        "3": {
          "at_world": {
            "adam_m": 0.125,
            "adam_v": 0.125,
            "grads": 0.125,
            "master": 0.0,
            "params": 0.125,
            "total": 0.5
          },
          "floor": 0.0,
          "grad_slice_only": false,
          "sharded": {
            "adam_m": true,
            "adam_v": true,
            "grads": true,
            "master": true,
            "params": true
          }
        }
      }
    },
    "identical_to_dp": {
      "bf16-mixed": {
        "0": true,
        "1": true,
        "2": true,
        "3": true
      },
      "fp32": {
        "0": true,
        "1": true,
        "2": true,
        "3": true
      }
    },
    "key_bias_drifted_further": true,
    "key_bias_ratio": 3.396836349449442,
    "max_abs_vs_dp": 0.0,
    "memory_equal": {
      "bf16-mixed": {
        "0": {
          "adam_m": true,
          "adam_v": true,
          "grads": true,
          "master": true,
          "params": true,
          "total": true
        },
        "1": {
          "adam_m": true,
          "adam_v": true,
          "grads": true,
          "master": true,
          "params": true,
          "total": true
        },
        "2": {
          "adam_m": true,
          "adam_v": true,
          "grads": true,
          "master": true,
          "params": true,
          "total": true
        },
        "3": {
          "adam_m": true,
          "adam_v": true,
          "grads": true,
          "master": true,
          "params": true,
          "total": true
        }
      },
      "fp32": {
        "0": {
          "adam_m": true,
          "adam_v": true,
          "grads": true,
          "master": true,
          "params": true,
          "total": true
        },
        "1": {
          "adam_m": true,
          "adam_v": true,
          "grads": true,
          "master": true,
          "params": true,
          "total": true
        },
        "2": {
          "adam_m": true,
          "adam_v": true,
          "grads": true,
          "master": true,
          "params": true,
          "total": true
        },
        "3": {
          "adam_m": true,
          "adam_v": true,
          "grads": true,
          "master": true,
          "params": true,
          "total": true
        }
      }
    },
    "optimizer_fewer": {
      "0": 1.0,
      "1": 32.0,
      "2": 32.0,
      "3": 32.0
    },
    "padded_world_sizes": [
      3
    ],
    "passes_per_unit": {
      "0": 2.0,
      "1": 2.0,
      "2": 2.0,
      "3": 3.0
    },
    "per_weight": {
      "bf16-mixed": {
        "0": {
          "adam_m": 4.0,
          "adam_v": 4.0,
          "grads": 2.0,
          "master": 4.0,
          "params": 2.0,
          "total": 16.0
        },
        "1": {
          "adam_m": 0.125,
          "adam_v": 0.125,
          "grads": 2.0,
          "master": 0.125,
          "params": 2.0,
          "total": 4.375
        },
        "2": {
          "adam_m": 0.125,
          "adam_v": 0.125,
          "grads": 0.0625,
          "master": 0.125,
          "params": 2.0,
          "total": 2.4375
        },
        "3": {
          "adam_m": 0.125,
          "adam_v": 0.125,
          "grads": 0.0625,
          "master": 0.125,
          "params": 0.0625,
          "total": 0.5
        }
      },
      "fp32": {
        "0": {
          "adam_m": 4.0,
          "adam_v": 4.0,
          "grads": 4.0,
          "master": 0.0,
          "params": 4.0,
          "total": 16.0
        },
        "1": {
          "adam_m": 0.125,
          "adam_v": 0.125,
          "grads": 4.0,
          "master": 0.0,
          "params": 4.0,
          "total": 8.25
        },
        "2": {
          "adam_m": 0.125,
          "adam_v": 0.125,
          "grads": 0.125,
          "master": 0.0,
          "params": 4.0,
          "total": 4.375
        },
        "3": {
          "adam_m": 0.125,
          "adam_v": 0.125,
          "grads": 0.125,
          "master": 0.0,
          "params": 0.125,
          "total": 0.5
        }
      }
    },
    "reference_differs": true,
    "ring": {
      "chunk_bytes": 333280,
      "padding": 0,
      "payload_bytes": 1333120,
      "phase_bytes": 999840,
      "units": 4,
      "world_size": 4
    },
    "scaling_all_match": true,
    "slider": {
      "exact_fill": {
        "0": false,
        "1": false,
        "2": true,
        "3": true
      },
      "first_fit": {
        "0": null,
        "1": null,
        "2": 21,
        "3": 6
      },
      "first_headroom": {
        "0": null,
        "1": null,
        "2": 22,
        "3": 7
      },
      "fits": {
        "0": [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false
        ],
        "1": [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false
        ],
        "2": [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true
        ],
        "3": [
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true
        ]
      },
      "floor_gib": {
        "0": 447.0348358154297,
        "1": 111.75870895385742,
        "2": 55.87935447692871,
        "3": 0.0
      },
      "gib": {
        "0": [
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03,
          447.03
        ],
        "1": [
          447.03,
          279.4,
          223.52,
          195.58,
          178.81,
          167.64,
          159.66,
          153.67,
          149.01,
          145.29,
          142.24,
          139.7,
          137.55,
          135.71,
          134.11,
          132.71,
          131.48,
          130.39,
          129.4,
          128.52,
          127.72,
          127.0,
          126.34,
          125.73,
          125.17,
          124.65,
          124.18,
          123.73,
          123.32,
          122.93,
          122.57,
          122.24,
          121.92,
          121.62,
          121.34,
          121.07,
          120.82,
          120.58,
          120.36,
          120.14,
          119.94,
          119.74,
          119.56,
          119.38,
          119.21,
          119.05,
          118.89,
          118.74,
          118.6,
          118.46,
          118.33,
          118.21,
          118.08,
          117.97,
          117.85,
          117.75,
          117.64,
          117.54,
          117.44,
          117.35,
          117.26,
          117.17,
          117.08,
          117.0
        ],
        "2": [
          447.03,
          251.46,
          186.26,
          153.67,
          134.11,
          121.07,
          111.76,
          104.77,
          99.341,
          94.995,
          91.439,
          88.476,
          85.968,
          83.819,
          81.956,
          80.327,
          78.889,
          77.61,
          76.466,
          75.437,
          74.506,
          73.659,
          72.886,
          72.177,
          71.526,
          70.924,
          70.367,
          69.849,
          69.367,
          68.918,
          68.497,
          68.103,
          67.733,
          67.384,
          67.055,
          66.745,
          66.451,
          66.173,
          65.909,
          65.658,
          65.42,
          65.193,
          64.976,
          64.769,
          64.572,
          64.383,
          64.202,
          64.028,
          63.862,
          63.702,
          63.549,
          63.402,
          63.26,
          63.123,
          62.991,
          62.864,
          62.742,
          62.623,
          62.509,
          62.399,
          62.292,
          62.188,
          62.088,
          61.991
        ],
        "3": [
          447.03,
          223.52,
          149.01,
          111.76,
          89.407,
          74.506,
          63.862,
          55.879,
          49.671,
          44.703,
          40.64,
          37.253,
          34.387,
          31.931,
          29.802,
          27.94,
          26.296,
          24.835,
          23.528,
          22.352,
          21.287,
          20.32,
          19.436,
          18.626,
          17.881,
          17.194,
          16.557,
          15.966,
          15.415,
          14.901,
          14.42,
          13.97,
          13.547,
          13.148,
          12.772,
          12.418,
          12.082,
          11.764,
          11.462,
          11.176,
          10.903,
          10.644,
          10.396,
          10.16,
          9.9341,
          9.7181,
          9.5114,
          9.3132,
          9.1232,
          8.9407,
          8.7654,
          8.5968,
          8.4346,
          8.2784,
          8.1279,
          7.9828,
          7.8427,
          7.7075,
          7.5769,
          7.4506,
          7.3284,
          7.2102,
          7.0958,
          6.9849
        ]
      },
      "never_fits": {
        "0": true,
        "1": true,
        "2": false,
        "3": false
      },
      "world_sizes": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64
      ]
    },
    "transient_extra": {
      "bf16-mixed": {
        "0": 0,
        "1": 0,
        "2": 642112,
        "3": 642112
      },
      "fp32": {
        "0": 0,
        "1": 0,
        "2": 1284224,
        "3": 1284224
      }
    },
    "transient_together": {
      "bf16-mixed": {
        "0": false,
        "1": false,
        "2": false,
        "3": false
      },
      "fp32": {
        "0": false,
        "1": false,
        "2": false,
        "3": false
      }
    },
    "zero12_send_same_as_dp": true,
    "zero3_sent_over_dp": 1.5,
    "zero_runs_compared": 6
  },
  "provenance": {
    "code_digest": "sha256:c38e0377ef8cf92117a81d1a9c328f660529d0dbf14e1f1785018ddd00704cc0",
    "config_fingerprint": "e3eb27cdbbc0",
    "corpus_digest": "sha256:19f24ce7db26e4f3dde1b3663b6edb19019d887f0188bdaca16ffad7087b0261",
    "environment": {
      "device": "cpu",
      "machine": "arm64",
      "omp_num_threads": "unset",
      "platform": "macOS-26.6.2-arm64-arm-64bit",
      "python": "3.12.13",
      "torch": "2.13.0",
      "torch_threads": 12
    },
    "git_sha": "2b5834228056d7c1adceb5a4c77af28cd425ed50",
    "tokenizer_digest": "sha256:b2c4905dc61645931cd545e86c503fd34671a9a31719f3dd1bce0a7f8ea129ae"
  },
  "scaling": {
    "rows": [
      {
        "measured": 16.0,
        "measured_real": 16.0,
        "predicted": 16.0,
        "stage": 0,
        "world_size": 1
      },
      {
        "measured": 16.0,
        "measured_real": 16.0,
        "predicted": 16.0,
        "stage": 1,
        "world_size": 1
      },
      {
        "measured": 16.0,
        "measured_real": 16.0,
        "predicted": 16.0,
        "stage": 2,
        "world_size": 1
      },
      {
        "measured": 16.0,
        "measured_real": 16.0,
        "predicted": 16.0,
        "stage": 3,
        "world_size": 1
      },
      {
        "measured": 16.0,
        "measured_real": 16.0,
        "predicted": 16.0,
        "stage": 0,
        "world_size": 2
      },
      {
        "measured": 10.0,
        "measured_real": 10.0,
        "predicted": 10.0,
        "stage": 1,
        "world_size": 2
      },
      {
        "measured": 9.0,
        "measured_real": 9.0,
        "predicted": 9.0,
        "stage": 2,
        "world_size": 2
      },
      {
        "measured": 8.0,
        "measured_real": 8.0,
        "predicted": 8.0,
        "stage": 3,
        "world_size": 2
      },
      {
        "measured": 16.0,
        "measured_real": 16.00009601536246,
        "predicted": 16.0,
        "stage": 0,
        "world_size": 3
      },
      {
        "measured": 8.0,
        "measured_real": 8.00004800768123,
        "predicted": 8.0,
        "stage": 1,
        "world_size": 3
      },
      {
        "measured": 6.666666666666667,
        "measured_real": 6.666706673067691,
        "predicted": 6.666666666666667,
        "stage": 2,
        "world_size": 3
      },
      {
        "measured": 5.333333333333333,
        "measured_real": 5.333365338454152,
        "predicted": 5.333333333333333,
        "stage": 3,
        "world_size": 3
      },
      {
        "measured": 16.0,
        "measured_real": 16.0,
        "predicted": 16.0,
        "stage": 0,
        "world_size": 4
      },
      {
        "measured": 7.0,
        "measured_real": 7.0,
        "predicted": 7.0,
        "stage": 1,
        "world_size": 4
      },
      {
        "measured": 5.5,
        "measured_real": 5.5,
        "predicted": 5.5,
        "stage": 2,
        "world_size": 4
      },
      {
        "measured": 4.0,
        "measured_real": 4.0,
        "predicted": 4.0,
        "stage": 3,
        "world_size": 4
      },
      {
        "measured": 16.0,
        "measured_real": 16.0,
        "predicted": 16.0,
        "stage": 0,
        "world_size": 8
      },
      {
        "measured": 5.5,
        "measured_real": 5.5,
        "predicted": 5.5,
        "stage": 1,
        "world_size": 8
      },
      {
        "measured": 3.75,
        "measured_real": 3.75,
        "predicted": 3.75,
        "stage": 2,
        "world_size": 8
      },
      {
        "measured": 2.0,
        "measured_real": 2.0,
        "predicted": 2.0,
        "stage": 3,
        "world_size": 8
      },
      {
        "measured": 16.0,
        "measured_real": 16.0,
        "predicted": 16.0,
        "stage": 0,
        "world_size": 16
      },
      {
        "measured": 4.75,
        "measured_real": 4.75,
        "predicted": 4.75,
        "stage": 1,
        "world_size": 16
      },
      {
        "measured": 2.875,
        "measured_real": 2.875,
        "predicted": 2.875,
        "stage": 2,
        "world_size": 16
      },
      {
        "measured": 1.0,
        "measured_real": 1.0,
        "predicted": 1.0,
        "stage": 3,
        "world_size": 16
      },
      {
        "measured": 16.0,
        "measured_real": 16.0,
        "predicted": 16.0,
        "stage": 0,
        "world_size": 32
      },
      {
        "measured": 4.375,
        "measured_real": 4.375,
        "predicted": 4.375,
        "stage": 1,
        "world_size": 32
      },
      {
        "measured": 2.4375,
        "measured_real": 2.4375,
        "predicted": 2.4375,
        "stage": 2,
        "world_size": 32
      },
      {
        "measured": 0.5,
        "measured_real": 0.5,
        "predicted": 0.5,
        "stage": 3,
        "world_size": 32
      }
    ],
    "world_sizes": [
      1,
      2,
      3,
      4,
      8,
      16,
      32
    ]
  },
  "topology": {
    "devices_per_node": 8,
    "nodes": 4,
    "ring_links": {
      "inter": 4,
      "intra": 28
    },
    "world_size": 32
  }
};
