// GENERATED by tools/build_web_data.py from results/mechanisms.json — do not edit by hand.
//
// Every date, trade-off and citation on this page comes from the tracked catalogue, and every
// derived figure comes from the same functions the tests exercise. Editing this file directly
// would let the page disagree with the evidence that produced it; regenerate instead:
//
//     uv run python src/exercises/08-modern-attention-variants/tools/build_web_data.py

export const M = Object.freeze({
  "mechanisms": [
    {
      "key": "bahdanau_attention",
      "name": "Additive (Bahdanau) attention",
      "aka": [
        "soft alignment",
        "RNN attention"
      ],
      "date": "2014-09-01",
      "year": 2014,
      "bill": "origin",
      "taught": false,
      "bonus": true,
      "whatExisted": "Encoder-decoder translation squeezed a whole source sentence into one fixed-length vector.",
      "problem": "That single vector was a bottleneck: the longer the sentence, the more the decoder had already forgotten by the time it needed the beginning.",
      "mechanism": "Let the decoder compute a weighted average over every encoder state at each output step, with the weights learned from a small alignment network.",
      "whatItFixed": "Long sentences stopped degrading, because nothing had to be remembered through a bottleneck any more.",
      "newTradeoff": "Cost became a product of the two sequence lengths rather than a constant, and the recurrence it sat on top of still forced sequential computation.",
      "buys": "Direct access to every input position, so distance stops causing forgetting.",
      "givesUp": "A constant-size interface, in exchange for one that grows with the input.",
      "whenToChoose": "Historical. It matters because it is the origin: attention existed for three years before anyone removed the recurrence around it.",
      "glyph": {
        "kind": "field",
        "params": {
          "causal": false
        },
        "scale": "schematic",
        "source": "Cross-attention over a source sentence: every target position may see every source position, so there is no mask. Shape from the paper's description; grid size is ours."
      },
      "source": {
        "kind": "paper",
        "title": "Neural Machine Translation by Jointly Learning to Align and Translate",
        "url": "https://arxiv.org/abs/1409.0473",
        "arxiv": "1409.0473",
        "quoted": "[v1] Mon, 1 Sep 2014 16:33:02 UTC (83 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Seven versions; v7 is 19 May 2016, twenty months after v1. Quote v1."
      }
    },
    {
      "key": "learned_absolute",
      "name": "Learned absolute position embeddings",
      "aka": [],
      "date": "2017-05-08",
      "year": 2017,
      "bill": "position",
      "taught": false,
      "bonus": false,
      "whatExisted": "Recurrent and convolutional encoders got word order for free from their own structure.",
      "problem": "A model that mixes tokens by content alone cannot tell which token came first; 'dog bites man' and 'man bites dog' look identical.",
      "mechanism": "Keep one learned vector per absolute position and add it to the token embedding before the first layer.",
      "whatItFixed": "Order became available to an architecture that had no inherent notion of it.",
      "newTradeoff": "The table has a fixed number of rows, so the model has no representation at all for a position it never trained on - a hard wall rather than a graceful decline.",
      "buys": "Order information at almost no compute cost, learned rather than designed.",
      "givesUp": "Any ability to run past the trained length, and parameters that scale with the maximum context.",
      "whenToChoose": "When the context length is fixed and known in advance, and you would rather the model learn positional structure than be told it.",
      "glyph": {
        "kind": "bands",
        "params": {
          "rows": 6,
          "hardEdge": true
        },
        "scale": "schematic",
        "source": "One learned row per position, with nothing beyond the trained length. Band count is illustrative."
      },
      "source": {
        "kind": "paper",
        "title": "Convolutional Sequence to Sequence Learning",
        "url": "https://arxiv.org/abs/1705.03122",
        "arxiv": "1705.03122",
        "quoted": "[v1] Mon, 8 May 2017 23:25:30 UTC (1,489 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Attribution is contested and the honest answer is a range. This is the source 'Attention Is All You Need' itself cites as [9] for learned positional encodings. The same authors used them six months earlier in arXiv:1611.02344 (v1 7 Nov 2016), which in turn credits Sukhbaatar et al. 2015 - a lead we did not open and therefore do not assert."
      }
    },
    {
      "key": "sinusoidal",
      "name": "Sinusoidal positional encoding",
      "aka": [],
      "date": "2017-06-12",
      "year": 2017,
      "bill": "position",
      "taught": true,
      "bonus": false,
      "whatExisted": "Learned absolute position tables, with a hard limit at the trained length.",
      "problem": "The table cannot answer a question about a position it never saw, and it spends parameters on something that might be computable instead.",
      "mechanism": "Replace the table with fixed sine and cosine functions of different frequencies, one pair per embedding dimension.",
      "whatItFixed": "Positions became defined at any index without training or parameters, and nearby positions got similar encodings by construction.",
      "newTradeoff": "Defined is not the same as learned: the function returns a value past the trained length, but the model has never been taught what to do with it, so quality still falls away.",
      "buys": "Positions at any length, for zero parameters.",
      "givesUp": "The chance to learn a positional structure that suits the data, and any guarantee that extrapolation actually works.",
      "whenToChoose": "When you want a simple, parameter-free baseline, or a fixed encoding you can reason about analytically.",
      "glyph": {
        "kind": "bands",
        "params": {
          "rows": 6,
          "hardEdge": false,
          "continues": true
        },
        "scale": "schematic",
        "source": "Fixed sine and cosine bands at different frequencies, defined past the trained length. Band count is illustrative."
      },
      "source": {
        "kind": "paper",
        "title": "Attention Is All You Need",
        "url": "https://arxiv.org/abs/1706.03762",
        "arxiv": "1706.03762",
        "quoted": "[v1] Mon, 12 Jun 2017 17:57:34 UTC (1,102 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Same paper and same date as standard_attention - introduced in section 3.5, not in the abstract. It is not a separate release and must not be given a separate date."
      }
    },
    {
      "key": "standard_attention",
      "name": "Scaled dot-product attention",
      "aka": [
        "vanilla attention",
        "softmax attention",
        "MHA"
      ],
      "date": "2017-06-12",
      "year": 2017,
      "bill": "origin",
      "taught": true,
      "bonus": false,
      "whatExisted": "Attention worked, but it was bolted onto a recurrent network that still had to process tokens one at a time.",
      "problem": "Recurrence made training sequential, so it could not use the parallelism the hardware had.",
      "mechanism": "Drop the recurrence entirely. Project each token to a query, key and value; score every query against every key; scale by the square root of the head dimension; mask the future; softmax; take the weighted sum of values.",
      "whatItFixed": "Training parallelised across the whole sequence at once, and every token could reach every other token in one step.",
      "newTradeoff": "It sends two bills that nothing before it sent: scores grow with the square of the sequence length, and generation must keep every past key and value in memory.",
      "buys": "Exact, global, parallel mixing - every token sees every other token, with no approximation anywhere.",
      "givesUp": "Quadratic compute and a cache that grows without limit. Everything after this on the timeline is somebody paying less of one of those two.",
      "whenToChoose": "Short contexts, and as the baseline any alternative has to beat. It is not obsolete; it is exact, and exactness is what the rest of the list trades away.",
      "glyph": {
        "kind": "field",
        "params": {
          "causal": true
        },
        "scale": "illustrative",
        "source": "The full causal triangle — the reference every other field glyph is drawn against. Exact by construction."
      },
      "source": {
        "kind": "paper",
        "title": "Attention Is All You Need",
        "url": "https://arxiv.org/abs/1706.03762",
        "arxiv": "1706.03762",
        "quoted": "[v1] Mon, 12 Jun 2017 17:57:34 UTC (1,102 KB)",
        "verifiedOn": "2026-09-01",
        "note": "The course transcript dates this as 'invented in 2018 and 17'. It is June 2017."
      }
    },
    {
      "key": "sparse_attention",
      "name": "Sparse (factorised) attention",
      "aka": [
        "Sparse Transformer",
        "strided attention",
        "top-k attention"
      ],
      "date": "2019-04-23",
      "year": 2019,
      "bill": "compute",
      "taught": true,
      "bonus": false,
      "whatExisted": "Dense attention over every pair of positions, at quadratic cost.",
      "problem": "Most of that attention matrix carries almost no weight, so most of the compute buys almost nothing.",
      "mechanism": "Attend over a fixed sparse pattern instead of all pairs - strided and local factorisations that together still connect any two positions in a few hops.",
      "whatItFixed": "Cost dropped from quadratic toward n-root-n, making far longer sequences reachable at the same budget.",
      "newTradeoff": "The pattern is chosen in advance, so a genuinely important long-range pair that the pattern does not connect is simply unavailable - and a learned top-k variant still has to score the candidates before it can rank them.",
      "buys": "A large constant-factor reduction in attention compute, with softmax and its normalisation intact.",
      "givesUp": "Exactness. The model can no longer reach every position directly, and which pairs it loses is a design decision rather than a learned one.",
      "whenToChoose": "Long sequences with structure you understand - images, audio, code - where a fixed pattern plausibly covers the dependencies that matter.",
      "glyph": {
        "kind": "field",
        "params": {
          "causal": true,
          "local": 2,
          "stride": 4
        },
        "scale": "schematic",
        "source": "Strided plus local factorisation. The paper gives O(n sqrt n); the specific stride and local width here are ours."
      },
      "source": {
        "kind": "paper",
        "title": "Generating Long Sequences with Sparse Transformers",
        "url": "https://arxiv.org/abs/1904.10509",
        "arxiv": "1904.10509",
        "quoted": "[v1] Tue, 23 Apr 2019 19:29:47 UTC (4,004 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Child, Gray, Radford, Sutskever. The earliest cost-reduction entry on this timeline - it predates MQA by about six months."
      }
    },
    {
      "key": "mqa",
      "name": "Multi-query attention (MQA)",
      "aka": [],
      "date": "2019-11-06",
      "year": 2019,
      "bill": "cache",
      "taught": true,
      "bonus": false,
      "whatExisted": "Multi-head attention, where every query head has its own key and value head.",
      "problem": "During generation the model reloads the whole KV cache for every single token, so decoding is bound by memory bandwidth rather than arithmetic.",
      "mechanism": "Keep all the query heads, but give them one shared key head and one shared value head.",
      "whatItFixed": "The cache shrank by the number of heads - eight times smaller at eight heads - and decoding stopped waiting on memory.",
      "newTradeoff": "Every query head now reads the same keys and values, so the heads lose the ability to attend to genuinely different things, and quality can fall.",
      "buys": "The largest cache reduction available from head sharing, and a matching speedup in generation.",
      "givesUp": "Head diversity, and with it some model quality - the paper reports the degradation rather than hiding it.",
      "whenToChoose": "Generation-heavy serving where memory bandwidth is the binding constraint and a small quality cost is acceptable.",
      "glyph": {
        "kind": "stack",
        "params": {
          "kv": 1,
          "of": 8
        },
        "scale": "illustrative",
        "source": "One key/value head for all query heads, by definition. Head count 8 is the session's own yardstick."
      },
      "source": {
        "kind": "paper",
        "title": "Fast Transformer Decoding: One Write-Head is All You Need",
        "url": "https://arxiv.org/abs/1911.02150",
        "arxiv": "1911.02150",
        "quoted": "[v1] Wed, 6 Nov 2019 00:19:05 UTC (10 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Single author (Noam Shazeer), single version."
      }
    },
    {
      "key": "reformer",
      "name": "Reformer (LSH attention)",
      "aka": [],
      "date": "2020-01-13",
      "year": 2020,
      "bill": "compute",
      "taught": false,
      "bonus": true,
      "whatExisted": "Sparse attention with a hand-designed pattern.",
      "problem": "A fixed pattern cannot adapt to the data; the pairs that matter are not always the pairs a designer picked.",
      "mechanism": "Hash queries and keys into buckets with locality-sensitive hashing, and attend only within a bucket - so tokens that would have scored highly land together without computing the scores first.",
      "whatItFixed": "Sparsity became content-dependent rather than positional, at n-log-n cost.",
      "newTradeoff": "Hashing is probabilistic, so a relevant pair can miss each other by luck; and the scheme needs several hash rounds plus shared query-key projections to work, which constrains the architecture.",
      "buys": "Learned, content-aware sparsity without scoring every pair.",
      "givesUp": "Determinism and simplicity - and in practice the constants were high enough that it saw little production use.",
      "whenToChoose": "Rarely today. It earns its place on the timeline as the moment the field tried to learn the sparsity pattern instead of designing it.",
      "glyph": {
        "kind": "field",
        "params": {
          "causal": true,
          "permuted": true,
          "blocks": 3
        },
        "scale": "schematic",
        "source": "Block-diagonal on a reordered sequence, with the reordering drawn above it. Buckets come from hashing the content, so which cells are live depends on the data and not on position; a fixed pattern here would be a lie a reader cannot detect."
      },
      "source": {
        "kind": "paper",
        "title": "Reformer: The Efficient Transformer",
        "url": "https://arxiv.org/abs/2001.04451",
        "arxiv": "2001.04451",
        "quoted": "[v1] Mon, 13 Jan 2020 18:38:28 UTC (421 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Kitaev, Kaiser, Levskaya. Included as a bonus because it dates the field's first attempt to make sparsity *learned* rather than fixed."
      }
    },
    {
      "key": "sliding_window",
      "name": "Sliding-window attention",
      "aka": [
        "local attention",
        "Longformer window"
      ],
      "date": "2020-04-10",
      "year": 2020,
      "bill": "both",
      "taught": false,
      "bonus": false,
      "whatExisted": "Dense attention, or sparsity with a globally designed pattern.",
      "problem": "Long documents were unreachable at quadratic cost, and most linguistic dependencies are local anyway.",
      "mechanism": "Each token attends only to a fixed window of neighbours, with a few designated tokens attending globally; stacking layers lets information travel further than one window.",
      "whatItFixed": "Cost became linear in sequence length, and the KV cache became bounded rather than growing forever.",
      "newTradeoff": "Anything outside the window is reachable only through several layers of indirection, and a fact that must be recalled verbatim from far away can be lost entirely.",
      "buys": "Linear cost and a cache that stops growing - the only entry here that bounds both bills with one idea.",
      "givesUp": "Direct long-range access. Retrieval across the whole context becomes a function of depth rather than a guarantee.",
      "whenToChoose": "Long inputs whose important dependencies really are local, or as one component of a hybrid that pairs it with something global.",
      "glyph": {
        "kind": "field",
        "params": {
          "causal": true,
          "window": 4
        },
        "scale": "schematic",
        "source": "A band of recent positions. Window width is ours; the papers use several."
      },
      "source": {
        "kind": "paper",
        "title": "Longformer: The Long-Document Transformer",
        "url": "https://arxiv.org/abs/2004.05150",
        "arxiv": "2004.05150",
        "quoted": "[v1] Fri, 10 Apr 2020 17:54:09 UTC (228 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Longformer names and introduces the mechanism. Mistral 7B (arXiv:2310.06825, v1 10 Oct 2023) popularised it in a decoder LLM three and a half years later; that is a popularisation, not an origin. Neither is the first use of local attention - Sparse Transformers already used local factorisations in 2019."
      }
    },
    {
      "key": "linear_attention",
      "name": "Linear attention",
      "aka": [
        "Transformers are RNNs",
        "kernel attention"
      ],
      "date": "2020-06-29",
      "year": 2020,
      "bill": "both",
      "taught": true,
      "bonus": false,
      "whatExisted": "Softmax attention, exact and quadratic, keeping every past key.",
      "problem": "The softmax is what forces you to keep every key: because it normalises across all of them, no partial sum can be computed in advance.",
      "mechanism": "Replace the exponential with a feature map so the score factorises. Then the sum over past tokens regroups into a single running state matrix, and each new query multiplies that state instead of visiting the history.",
      "whatItFixed": "Compute became linear in sequence length, and the cache became a fixed-size state - the same size after a million tokens as after ten.",
      "newTradeoff": "Four things go at once: weights are no longer positive, they no longer sum to one, keys no longer compete with each other, and there is no fresh query-specific distribution over the exact old keys. Memories interfere, and unnormalised scores can grow.",
      "buys": "Constant memory and linear time, with a state that never grows.",
      "givesUp": "Exact recall. The state is a lossy summary, and what it lost is not recoverable.",
      "whenToChoose": "Very long streams where a bounded state is a hard requirement, and where approximate recall of the distant past is acceptable.",
      "glyph": {
        "kind": "state",
        "params": {
          "write": "add"
        },
        "scale": "schematic",
        "source": "A fixed-size running state, the same size at any context. Deliberately NOT a diagonal, which would wrongly suggest a token attends only to itself. State dimensions are ours."
      },
      "source": {
        "kind": "paper",
        "title": "Transformers are RNNs: Fast Autoregressive Transformers with Linear Attention",
        "url": "https://arxiv.org/abs/2006.16236",
        "arxiv": "2006.16236",
        "quoted": "[v1] Mon, 29 Jun 2020 17:55:38 UTC (1,626 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Katharopoulos, Vyas, Pappas, Fleuret. Cite v1, not the ICML 2020 conference date."
      }
    },
    {
      "key": "delta_rule",
      "name": "The delta rule",
      "aka": [
        "fast weight programmers",
        "DeltaNet"
      ],
      "date": "2021-02-22",
      "year": 2021,
      "bill": "both",
      "taught": true,
      "bonus": false,
      "whatExisted": "Linear attention with an add-only state: each new key-value pair is added to the running matrix.",
      "problem": "Adding never removes. If a key's value should change from 40 to 55, an add-only write leaves 40 + 55 = 95, and the old contribution is carried forward forever.",
      "mechanism": "Read what the state currently returns for this key, compute the difference from what it should return, and write only that difference.",
      "whatItFixed": "The state can now be updated rather than only appended to, so a linear model can correct itself instead of accumulating interference.",
      "newTradeoff": "The update is sequential by construction - each write depends on the read before it - which made it hard to train efficiently until the parallelisation work three years later.",
      "buys": "A fixed-size state that can actually be edited, removing linear attention's worst failure mode.",
      "givesUp": "The simple parallel form of plain linear attention, and it still has no exact record of the past.",
      "whenToChoose": "Whenever you want linear attention's economics but the task involves overwriting facts rather than only accumulating them.",
      "glyph": {
        "kind": "state",
        "params": {
          "write": "add+correct"
        },
        "scale": "schematic",
        "source": "The same fixed state, written by reading first and applying only the difference."
      },
      "source": {
        "kind": "paper",
        "title": "Linear Transformers Are Secretly Fast Weight Programmers",
        "url": "https://arxiv.org/abs/2102.11174",
        "arxiv": "2102.11174",
        "quoted": "[v1] Mon, 22 Feb 2021 16:51:38 UTC (1,548 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Schlag, Irie, Schmidhuber. The id prefix 2102 is February 2021 and v1 is the 22nd - do not read the id as a day."
      }
    },
    {
      "key": "rope",
      "name": "RoPE (rotary position embedding)",
      "aka": [],
      "date": "2021-04-20",
      "year": 2021,
      "bill": "position",
      "taught": true,
      "bonus": false,
      "whatExisted": "Position added to the token embedding once, before the first layer, as an absolute value.",
      "problem": "What attention actually needs is relative distance, and an absolute vector added at the input is a roundabout way of supplying it - it also has to survive every layer unchanged.",
      "mechanism": "Rotate each pair of dimensions in the query and key by an angle proportional to the token's position. The dot product of two rotated vectors then depends only on the difference of their positions.",
      "whatItFixed": "Relative position became a property of the attention score itself rather than a signal added to the input, and different dimension pairs rotate at different rates to carry distance at several scales.",
      "newTradeoff": "The rotation keeps turning past the trained length. Somewhere beyond the context the model saw, a very distant pair has rotated so far that the relationship degrades - which is what every extension method after this is trying to repair.",
      "buys": "Clean relative position, no parameters, and a form that composes with efficient attention kernels.",
      "givesUp": "Reliable behaviour outside the trained range - defined everywhere, trustworthy only where it was trained.",
      "whenToChoose": "Almost every decoder-only model today. It is the default, and the entries after it are about extending it rather than replacing it.",
      "glyph": {
        "kind": "field",
        "params": {
          "causal": true,
          "graded": "relative"
        },
        "scale": "schematic",
        "source": "A graded field constant along each diagonal, oscillating with the gap under a slow decay envelope, because the score is a sum of cosines of the gap times theta. Frequency and envelope are illustrative; the oscillation is the mechanism."
      },
      "source": {
        "kind": "paper",
        "title": "RoFormer: Enhanced Transformer with Rotary Position Embedding",
        "url": "https://arxiv.org/abs/2104.09864",
        "arxiv": "2104.09864",
        "quoted": "[v1] Tue, 20 Apr 2021 09:54:06 UTC (91 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Verified twice independently."
      }
    },
    {
      "key": "alibi",
      "name": "ALiBi (attention with linear biases)",
      "aka": [],
      "date": "2021-08-27",
      "year": 2021,
      "bill": "position",
      "taught": false,
      "bonus": false,
      "whatExisted": "Positional information encoded into the token or query-key representation, which stops behaving past the trained length.",
      "problem": "Everybody wanted to train short and run long, and no encoding then in use survived the transition.",
      "mechanism": "Add no positional embedding at all. Instead subtract a penalty from each attention score in proportion to the distance between the two tokens, with a different slope per head.",
      "whatItFixed": "Extrapolation became the default rather than a repair: a linear penalty is defined and sensible at any distance, so a model trained at one length degrades gently at longer ones.",
      "newTradeoff": "The penalty is a fixed monotonic prior that says nearer is always more relevant. A task needing a specific far-away token fights that prior, and unlike a learned scheme there is no way for the model to override it.",
      "buys": "Length extrapolation with no extra parameters and almost no compute.",
      "givesUp": "The ability to attend strongly to something distant, and any positional structure more expressive than 'closer is better'.",
      "whenToChoose": "When train-short-run-long matters more than exact long-range recall, and the task is largely local.",
      "glyph": {
        "kind": "field",
        "params": {
          "causal": true,
          "graded": "linear"
        },
        "scale": "schematic",
        "source": "A linear penalty growing with distance, subtracted before softmax. Per-head slopes exist in the paper; the one drawn is illustrative."
      },
      "source": {
        "kind": "paper",
        "title": "Train Short, Test Long: Attention with Linear Biases Enables Input Length Extrapolation",
        "url": "https://arxiv.org/abs/2108.12409",
        "arxiv": "2108.12409",
        "quoted": "[v1] Fri, 27 Aug 2021 17:35:06 UTC (187 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Ofir Press et al. v2 is the ICLR 2022 revision."
      }
    },
    {
      "key": "flashattention",
      "name": "FlashAttention",
      "aka": [],
      "date": "2022-05-27",
      "year": 2022,
      "bill": "compute",
      "taught": false,
      "bonus": true,
      "whatExisted": "Two branches of work: exact attention that was too slow, and approximate attention that gave up exactness to be fast.",
      "problem": "Both branches assumed the cost was arithmetic. It was not - it was memory traffic, moving the attention matrix to and from high-bandwidth memory.",
      "mechanism": "Never materialise the full attention matrix. Tile the computation, keep tiles in fast on-chip memory, and use a running softmax so the result is exact without ever writing the intermediate.",
      "whatItFixed": "Attention got several times faster and used far less memory, with a bit-for-bit exact result - no approximation anywhere.",
      "newTradeoff": "The saving is in memory movement, not arithmetic, so the asymptotic cost is still quadratic; and the gain comes from hardware-specific kernels that must be rewritten for each new accelerator.",
      "buys": "A large constant-factor speedup and a big memory saving, while staying exact.",
      "givesUp": "Nothing mathematically - which is why it is on this list as the exception. What it costs is portability: it is a kernel, not an idea you can express in a few lines of framework code.",
      "whenToChoose": "Always, where a kernel exists for your hardware. It is the reason exact attention stayed competitive long after the approximations arrived.",
      "glyph": {
        "kind": "field",
        "params": {
          "causal": true,
          "tiled": true
        },
        "scale": "illustrative",
        "source": "Byte-identical to the standard-attention field, because FlashAttention is EXACT — it changes memory traffic, not one score. The only difference drawn is the tiling overlay."
      },
      "source": {
        "kind": "paper",
        "title": "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
        "url": "https://arxiv.org/abs/2205.14135",
        "arxiv": "2205.14135",
        "quoted": "[v1] Fri, 27 May 2022 17:53:09 UTC (1,325 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Dao, Fu, Ermon, Rudra, Re. FlashAttention-2 is a separate paper with a separate id, not verified here."
      }
    },
    {
      "key": "gqa",
      "name": "Grouped-query attention (GQA)",
      "aka": [],
      "date": "2023-05-22",
      "year": 2023,
      "bill": "cache",
      "taught": true,
      "bonus": false,
      "whatExisted": "A binary choice between multi-head attention's large cache and multi-query attention's quality loss.",
      "problem": "MQA saved the most memory and cost the most quality; nobody had asked what the points in between looked like.",
      "mechanism": "Put the query heads into groups and give each group its own key and value head - so the number of KV heads is a dial between one and the number of query heads.",
      "whatItFixed": "Most of MQA's memory saving became available at a fraction of its quality cost. At the session's yardstick, two KV heads against eight is exactly a quarter of the cache.",
      "newTradeoff": "It moves along the same line rather than leaving it: the cache still grows linearly with context, so GQA makes long context cheaper without making it affordable.",
      "buys": "A tunable trade between cache size and head diversity, and a way to convert an existing multi-head checkpoint rather than retrain.",
      "givesUp": "Some head diversity still, and the underlying linear growth in context length is untouched.",
      "whenToChoose": "Almost any production decoder today - it is the practical default. Not a solution to long context on its own.",
      "glyph": {
        "kind": "stack",
        "params": {
          "kv": 2,
          "of": 8
        },
        "scale": "illustrative",
        "source": "Query heads in groups sharing a key/value head. 2 of 8 is the session's own worked example."
      },
      "source": {
        "kind": "paper",
        "title": "GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints",
        "url": "https://arxiv.org/abs/2305.13245",
        "arxiv": "2305.13245",
        "quoted": "[v1] Mon, 22 May 2023 17:16:38 UTC (140 KB)",
        "verifiedOn": "2026-09-01",
        "note": "EMNLP 2023 corresponds to v2/v3; v1 is the first appearance."
      }
    },
    {
      "key": "ntk_aware",
      "name": "NTK-aware scaled RoPE",
      "aka": [],
      "date": "2023-06-29",
      "year": 2023,
      "bill": "position",
      "taught": false,
      "bonus": false,
      "whatExisted": "RoPE, working well inside its trained context and degrading beyond it. The obvious repair was position interpolation - squeeze the positions so a longer context fits the trained range.",
      "problem": "Interpolating every frequency equally crushes the high-frequency dimensions, which is where fine-grained local distance lives - so the model gets longer context and worse local resolution.",
      "mechanism": "Scale the frequencies unevenly instead: change the low frequencies, which carry long-range structure, and leave the high frequencies that carry local detail nearly alone.",
      "whatItFixed": "Context extended several times over with little quality loss and, notably, without any fine-tuning at all.",
      "newTradeoff": "It is a heuristic reparameterisation with no training behind it, so the gain is bounded and it stops helping well before the extreme lengths later methods reach.",
      "buys": "A large context extension for free - no training, no data, a few lines of change.",
      "givesUp": "Principled grounding and headroom; it is a patch on a mismatch rather than a fix for it.",
      "whenToChoose": "When you need more context from an existing checkpoint today and cannot afford to train anything.",
      "glyph": {
        "kind": "bands",
        "params": {
          "rows": 6,
          "stretch": "low"
        },
        "scale": "schematic",
        "source": "Low-frequency bands stretched, high-frequency bands left nearly alone. Which bands and by how much is illustrative."
      },
      "source": {
        "kind": "post",
        "title": "NTK-Aware Scaled RoPE allows LLaMA models to have extended (8k+) context size without any fine-tuning and minimal perplexity degradation.",
        "url": "https://www.reddit.com/r/LocalLLaMA/comments/14lz7j5/ntkaware_scaled_rope_allows_llama_models_to_have/",
        "arxiv": null,
        "quoted": "created-timestamp=\"2023-06-29T08:21:29.413000+0000\"",
        "verifiedOn": "2026-09-01",
        "note": "There is no paper. This is a Reddit post by user bloc97, and the date is Reddit's own machine-readable created-timestamp field. reddit.com refused our requests, so the field was read from a Wayback Machine raw capture taken 2023-06-29 08:58 UTC rather than from the live page - a reader wanting the live source needs a browser. The first peer-reviewable write-up is the YaRN paper, which cites this post. Note 08:21 UTC is still 28 June in US time zones, which is why secondary sources disagree by a day."
      }
    },
    {
      "key": "yarn",
      "name": "YaRN",
      "aka": [],
      "date": "2023-08-31",
      "year": 2023,
      "bill": "position",
      "taught": false,
      "bonus": false,
      "whatExisted": "Position interpolation and the NTK-aware heuristic, both applied uniformly across the whole embedding.",
      "problem": "Neither treated the frequency bands according to what they actually do, and both left quality on the table at large extension factors.",
      "mechanism": "Split the frequencies into bands by how many full rotations they complete inside the trained window - interpolate the ones that wrapped many times, leave the ones that did not, and blend in between - plus a temperature correction to the attention softmax.",
      "whatItFixed": "Much larger extension factors became reachable, with far less fine-tuning data than earlier methods needed.",
      "newTradeoff": "It still needs some fine-tuning to reach its best results, and it inherits the assumption that the trained rotary structure is worth preserving at all - an assumption DroPE later attacks directly.",
      "buys": "The strongest RoPE extension of its generation, at a small fraction of the training cost.",
      "givesUp": "The zero-training property of the pure heuristic, and it adds hyperparameters that need setting per model.",
      "whenToChoose": "When you have an existing RoPE model, need a large context extension, and can afford a short fine-tune.",
      "glyph": {
        "kind": "bands",
        "params": {
          "rows": 6,
          "stretch": "banded"
        },
        "scale": "schematic",
        "source": "Frequencies split into bands and treated differently by band. The split points are illustrative."
      },
      "source": {
        "kind": "paper",
        "title": "YaRN: Efficient Context Window Extension of Large Language Models",
        "url": "https://arxiv.org/abs/2309.00071",
        "arxiv": "2309.00071",
        "quoted": "[v1] Thu, 31 Aug 2023 18:18:07 UTC (42 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Often cited as September 2023 from the 2309 id prefix; v1 is 31 August. This paper is also the citable source for the NTK-aware method above."
      }
    },
    {
      "key": "attention_sinks",
      "name": "Attention sinks / StreamingLLM",
      "aka": [],
      "date": "2023-09-29",
      "year": 2023,
      "bill": "cache",
      "taught": false,
      "bonus": false,
      "whatExisted": "Windowed attention, which bounds the cache by evicting the oldest tokens.",
      "problem": "Evicting the very first tokens made models collapse, and nobody knew why. It turned out that softmax must put its weight somewhere, so models learn to dump surplus attention onto the first few tokens - which are therefore load-bearing despite carrying no meaning.",
      "mechanism": "Keep a handful of initial tokens permanently in the cache as a place for that surplus attention to go, and slide the window over everything after them.",
      "whatItFixed": "Streaming generation over inputs far longer than the trained window became stable, with a cache of fixed size.",
      "newTradeoff": "It stabilises the model without extending it: everything evicted is genuinely gone, so this buys unbounded generation, not unbounded memory.",
      "buys": "Indefinite streaming at constant memory, from an existing checkpoint, with no training.",
      "givesUp": "Any access to the middle of a long history - which makes it wrong for tasks that need recall rather than continuation.",
      "whenToChoose": "Long-running conversation or streaming where recent context is what matters and the distant past can be forgotten.",
      "glyph": {
        "kind": "field",
        "params": {
          "causal": true,
          "window": 4,
          "sinks": 4
        },
        "scale": "schematic",
        "source": "A sliding window plus the first few positions held permanently — literally the union of two earlier glyphs. Sink count is illustrative."
      },
      "source": {
        "kind": "paper",
        "title": "Efficient Streaming Language Models with Attention Sinks",
        "url": "https://arxiv.org/abs/2309.17453",
        "arxiv": "2309.17453",
        "quoted": "[v1] Fri, 29 Sep 2023 17:59:56 UTC (9,548 KB)",
        "verifiedOn": "2026-09-01",
        "note": "The 'attention sink' is the observation; StreamingLLM is the method built on it - they are not synonyms. v1 predates Mistral 7B's v1 by eleven days, which reverses the usual telling of this period."
      }
    },
    {
      "key": "mamba",
      "name": "Mamba (selective state space)",
      "aka": [],
      "date": "2023-12-01",
      "year": 2023,
      "bill": "both",
      "taught": false,
      "bonus": true,
      "whatExisted": "Linear attention and state space models, both offering constant state but both mixing information in a way that does not depend on the content.",
      "problem": "A fixed recurrence cannot choose what to remember, so it compresses everything equally - and most of a sequence is not worth remembering.",
      "mechanism": "Make the state space parameters functions of the input, so the model can decide per token whether to store, ignore or forget, with a hardware-aware scan to keep it fast.",
      "whatItFixed": "A constant-state model became selective, closing much of the quality gap to attention while keeping linear time and a bounded cache.",
      "newTradeoff": "The state is still a fixed-size summary, so exact recall of an arbitrary earlier token is not available - which is why the strongest systems pair it with a few attention layers rather than replacing them.",
      "buys": "Linear time, constant memory, and content-dependent selection.",
      "givesUp": "Exact retrieval, and the simplicity of a single uniform layer type in practice.",
      "whenToChoose": "Very long sequences where throughput dominates, usually interleaved with attention layers rather than used alone.",
      "glyph": {
        "kind": "state",
        "params": {
          "write": "select"
        },
        "scale": "schematic",
        "source": "A fixed state whose write is input-dependent: store, ignore or forget per token."
      },
      "source": {
        "kind": "paper",
        "title": "Mamba: Linear-Time Sequence Modeling with Selective State Spaces",
        "url": "https://arxiv.org/abs/2312.00752",
        "arxiv": "2312.00752",
        "quoted": "[v1] Fri, 1 Dec 2023 18:01:34 UTC (1,264 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Gu and Dao. Mamba-2 is a separate paper with a separate id, not verified here. Included as a bonus because Gated DeltaNet's own subtitle is 'Improving Mamba2 with Delta Rule' - the recurrent thread runs through it."
      }
    },
    {
      "key": "mla",
      "name": "Multi-head latent attention (MLA)",
      "aka": [],
      "date": "2024-05-07",
      "year": 2024,
      "bill": "cache",
      "taught": false,
      "bonus": false,
      "whatExisted": "Head sharing - MQA and GQA - which reduces the cache by storing fewer heads.",
      "problem": "Head sharing pays for memory with head diversity, and it still stores full-width keys and values for every position.",
      "mechanism": "Store neither. Project the keys and values down to a small shared latent vector per position, cache that, and reconstruct the per-head keys and values on the fly when attending.",
      "whatItFixed": "The cache shrank far more than head sharing allows, while keeping the heads distinct - the paper reports a 93.3% reduction against its own baseline.",
      "newTradeoff": "Reconstruction is extra arithmetic at every step, the latent width is a new capacity bottleneck, and it interacts awkwardly with RoPE - which is why the design carries a separate small set of dimensions just for position.",
      "buys": "A large cache reduction without giving up head diversity.",
      "givesUp": "Simplicity and some compute; and it must be trained in from the start rather than converted from a checkpoint.",
      "whenToChoose": "Large-scale serving where the KV cache is the binding constraint and you control pretraining.",
      "glyph": {
        "kind": "stack",
        "params": {
          "kv": 1,
          "of": 8,
          "latent": true
        },
        "scale": "illustrative",
        "source": "Keys and values are not stored per head at all; a narrow shared latent is stored and re-expanded. The paper reports a 93.3% cache reduction against its own baseline."
      },
      "source": {
        "kind": "paper",
        "title": "DeepSeek-V2: A Strong, Economical, and Efficient Mixture-of-Experts Language Model",
        "url": "https://arxiv.org/abs/2405.04434",
        "arxiv": "2405.04434",
        "quoted": "[v1] Tue, 7 May 2024 15:56:43 UTC (431 KB)",
        "verifiedOn": "2026-09-01",
        "note": "MLA is introduced inside the DeepSeek-V2 model paper; there is no standalone MLA paper. The abstract states the KV cache is reduced by 93.3%."
      }
    },
    {
      "key": "deltanet_parallel",
      "name": "Parallelised DeltaNet",
      "aka": [],
      "date": "2024-06-10",
      "year": 2024,
      "bill": "both",
      "taught": true,
      "bonus": true,
      "whatExisted": "The delta rule, three years old, correct, and slow to train because each update depends on the previous one.",
      "problem": "A sequential recurrence cannot use the parallelism that made transformers trainable, so a good idea stayed impractical at scale.",
      "mechanism": "Reformulate the delta-rule recurrence as a matrix product that can be chunked, so a whole block of tokens is updated in parallel rather than one at a time.",
      "whatItFixed": "Delta-rule models became trainable at competitive scale, which is what moved the idea from a paper into architectures.",
      "newTradeoff": "The chunked form is more complex to implement and reason about, and it does not change what the state can hold - the recall limits of a fixed-size state are untouched.",
      "buys": "Practical training speed for an update rule that was already known to be better.",
      "givesUp": "Implementation simplicity; the arithmetic is no longer something you can read off in a line.",
      "whenToChoose": "Any serious use of the delta rule at scale - this is the version that made it deployable.",
      "glyph": {
        "kind": "state",
        "params": {
          "write": "add+correct",
          "chunked": true
        },
        "scale": "schematic",
        "source": "The delta-rule state, written a chunk at a time so it can be trained in parallel."
      },
      "source": {
        "kind": "paper",
        "title": "Parallelizing Linear Transformers with the Delta Rule over Sequence Length",
        "url": "https://arxiv.org/abs/2406.06484",
        "arxiv": "2406.06484",
        "quoted": "[v1] Mon, 10 Jun 2024 17:24:42 UTC (124 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Yang et al. The course transcript's claim that 'that paper came out in 2024' is correct for this one. The delta rule itself is three years older - see delta_rule."
      }
    },
    {
      "key": "gated_deltanet",
      "name": "Gated DeltaNet",
      "aka": [],
      "date": "2024-12-09",
      "year": 2024,
      "bill": "both",
      "taught": true,
      "bonus": false,
      "whatExisted": "Two separate good ideas: the delta rule, which edits the state precisely, and gating, which lets a model forget wholesale.",
      "problem": "Precise editing alone cannot clear a state that has drifted; wholesale forgetting alone cannot make a targeted correction. Each fails where the other works.",
      "mechanism": "Combine them - a gated decay that can flush the state, plus a delta update that can correct one association without touching the rest.",
      "whatItFixed": "Better recall and length behaviour than either mechanism alone, at the same constant state size.",
      "newTradeoff": "More moving parts and more to tune, and it remains a fixed-size state - better bookkeeping does not become exact memory.",
      "buys": "The strongest linear-recurrent quality of its generation, still at constant memory.",
      "givesUp": "Simplicity, and exact recall remains out of reach - a better-managed fixed state is still a fixed state.",
      "whenToChoose": "As the recurrent half of a hybrid stack, where most layers carry a bounded state and a few attention layers supply exact lookup.",
      "glyph": {
        "kind": "state",
        "params": {
          "write": "add+correct+flush"
        },
        "scale": "schematic",
        "source": "The delta-rule state plus a gate that can clear it wholesale."
      },
      "source": {
        "kind": "paper",
        "title": "Gated Delta Networks: Improving Mamba2 with Delta Rule",
        "url": "https://arxiv.org/abs/2412.06464",
        "arxiv": "2412.06464",
        "quoted": "[v1] Mon, 9 Dec 2024 13:09:04 UTC (261 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Yang, Kautz, Hatamizadeh (NVIDIA). Exactly six months after parallelised DeltaNet."
      }
    },
    {
      "key": "nsa",
      "name": "Native sparse attention (NSA)",
      "aka": [
        "DeepSeek compressed sparse attention",
        "CSA"
      ],
      "date": "2025-02-16",
      "year": 2025,
      "bill": "both",
      "taught": true,
      "bonus": false,
      "whatExisted": "Sparsity applied after the fact to a model trained densely, and cache reduction by storing fewer or narrower heads.",
      "problem": "Sparsity bolted on at inference fights a model that learned to attend densely, and the theoretical savings rarely survived contact with real kernels.",
      "mechanism": "Compress nearby tokens into block summaries, select the most useful blocks with a cheap index, and keep a local window for detail - trained this way from the start, with kernels designed for the access pattern.",
      "whatItFixed": "Sparsity that the model is trained to use, with speedups that show up in wall-clock time rather than only in flop counts, and a cache reduced along positions rather than heads.",
      "newTradeoff": "Compression discards token-level detail permanently, the selector can miss a block that mattered, and the whole design must be committed to before pretraining rather than added later.",
      "buys": "Long context at a cost that is affordable in practice, reducing both bills at once.",
      "givesUp": "Exactness twice over - once in the compression, once in the selection - and any option to change your mind after training.",
      "whenToChoose": "When you are pretraining for very long context and can design the architecture and the kernels together.",
      "glyph": {
        "kind": "field",
        "params": {
          "causal": true,
          "blocks": 3,
          "selected": 2,
          "window": 3
        },
        "scale": "schematic",
        "source": "Compressed blocks plus selected blocks plus a local window. The paper describes a hierarchical strategy; block size, how many are selected and the window are all ours."
      },
      "source": {
        "kind": "paper",
        "title": "Native Sparse Attention: Hardware-Aligned and Natively Trainable Sparse Attention",
        "url": "https://arxiv.org/abs/2502.11089",
        "arxiv": "2502.11089",
        "quoted": "[v1] Sun, 16 Feb 2025 11:53:44 UTC (915 KB)",
        "verifiedOn": "2026-09-01",
        "note": "The paper's own framing is compression plus selection. The session calls it 'compressed sparse attention'; the abstract describes a hierarchical strategy, so do not present two branches as the whole design without reading the body."
      }
    },
    {
      "key": "drope",
      "name": "DroPE",
      "aka": [],
      "date": "2025-12-13",
      "year": 2025,
      "bill": "position",
      "taught": true,
      "bonus": false,
      "whatExisted": "A decade of work adding positional information, then a further generation of work repairing it for longer contexts - interpolation, NTK-aware scaling, YaRN.",
      "problem": "Every repair assumed the rotary structure was worth keeping. But a rotation that has turned tens of thousands of times no longer usefully relates a distant token to an early one, and no rescaling fully fixes that.",
      "mechanism": "Stop repairing it and remove it. Pretrain with positional embeddings, then drop them and continue training briefly at a very low learning rate so the model recalibrates without them.",
      "whatItFixed": "Context extended by a large factor without long-context fine-tuning, on the argument that positional embeddings are a training scaffold rather than a permanent architectural requirement.",
      "newTradeoff": "It requires access to training - this cannot be applied to a checkpoint you can only run - and the loss spikes when the embeddings are removed before it recovers. It is also the newest entry here, with correspondingly less independent replication.",
      "buys": "Very large context extension without the long-context training data every earlier method needed.",
      "givesUp": "The ability to apply it post-hoc, and the comfort of a well-replicated result.",
      "whenToChoose": "When you control pretraining, need context far beyond what you trained on, and cannot afford to train at that length.",
      "glyph": {
        "kind": "bands",
        "params": {
          "rows": 6,
          "emptying": true
        },
        "scale": "schematic",
        "source": "The positional bands being removed after pretraining, which is the mechanism itself."
      },
      "source": {
        "kind": "paper",
        "title": "Extending the Context of Pretrained LLMs by Dropping Their Positional Embeddings",
        "url": "https://arxiv.org/abs/2512.12167",
        "arxiv": "2512.12167",
        "quoted": "[v1] Sat, 13 Dec 2025 04:23:47 UTC (2,135 KB)",
        "verifiedOn": "2026-09-01",
        "note": "Gelberg, Eguchi, Akiba, Cetin (Sakana AI). CAUTION: a different paper, DRoPE with a capital R (arXiv:2503.15029, 'Directional Rotary Position Embedding for Efficient Agent Interaction Modeling', 19 Mar 2025), is an autonomous-driving trajectory paper and is NOT this technique - the course transcript quotes its title while describing this mechanism. The two differ by one capital letter."
      }
    }
  ],
  "counts": {
    "total": 23,
    "mandated": 18,
    "bonus": 5,
    "outsideSession": 11,
    "schematic": 18,
    "glyphKinds": {
      "bands": 5,
      "field": 10,
      "stack": 3,
      "state": 5
    },
    "bills": {
      "origin": 2,
      "position": 7,
      "compute": 3,
      "cache": 4,
      "both": 7
    }
  },
  "periods": [
    {
      "start": 2014,
      "end": 2015,
      "dominant": "origin",
      "counts": {
        "origin": 1
      },
      "mechanisms": [
        "bahdanau_attention"
      ]
    },
    {
      "start": 2016,
      "end": 2017,
      "dominant": "position",
      "counts": {
        "position": 2,
        "origin": 1
      },
      "mechanisms": [
        "learned_absolute",
        "sinusoidal",
        "standard_attention"
      ]
    },
    {
      "start": 2018,
      "end": 2019,
      "dominant": null,
      "counts": {
        "compute": 1,
        "cache": 1
      },
      "mechanisms": [
        "sparse_attention",
        "mqa"
      ]
    },
    {
      "start": 2020,
      "end": 2021,
      "dominant": "both",
      "counts": {
        "compute": 1,
        "both": 3,
        "position": 2
      },
      "mechanisms": [
        "reformer",
        "sliding_window",
        "linear_attention",
        "delta_rule",
        "rope",
        "alibi"
      ]
    },
    {
      "start": 2022,
      "end": 2023,
      "dominant": null,
      "counts": {
        "compute": 1,
        "cache": 2,
        "position": 2,
        "both": 1
      },
      "mechanisms": [
        "flashattention",
        "gqa",
        "ntk_aware",
        "yarn",
        "attention_sinks",
        "mamba"
      ]
    },
    {
      "start": 2024,
      "end": 2025,
      "dominant": "both",
      "counts": {
        "cache": 1,
        "both": 3,
        "position": 1
      },
      "mechanisms": [
        "mla",
        "deltanet_parallel",
        "gated_deltanet",
        "nsa",
        "drope"
      ]
    }
  ],
  "gaps": [
    {
      "before": "bahdanau_attention",
      "after": "learned_absolute",
      "days": 980
    },
    {
      "before": "standard_attention",
      "after": "sparse_attention",
      "days": 680
    },
    {
      "before": "flashattention",
      "after": "gqa",
      "days": 360
    },
    {
      "before": "nsa",
      "after": "drope",
      "days": 300
    },
    {
      "before": "alibi",
      "after": "flashattention",
      "days": 273
    }
  ],
  "quietStretch": {
    "before": "standard_attention",
    "after": "sparse_attention",
    "days": 680
  },
  "yardstick": {
    "layers": 48,
    "kvHeads": 8,
    "queryHeads": 8,
    "headDim": 128,
    "dtype": "bf16",
    "source": "docs/sessions/s8.md — the configuration used throughout the cache section"
  },
  "cache": {
    "contexts": [
      {
        "context": 8192,
        "oneUser": 1610612736,
        "eightUsers": 12884901888
      },
      {
        "context": 32768,
        "oneUser": 6442450944,
        "eightUsers": 51539607552
      },
      {
        "context": 262144,
        "oneUser": 51539607552,
        "eightUsers": 412316860416
      },
      {
        "context": 1000000,
        "oneUser": 196608000000,
        "eightUsers": 1572864000000
      }
    ],
    "sharing": [
      {
        "name": "MHA",
        "kvHeads": 8,
        "note": "one KV head per query head; the largest cache",
        "bytesAt32k": 6442450944,
        "bytesPerToken": 196608,
        "tokensBeforeWall": 406901
      },
      {
        "name": "GQA",
        "kvHeads": 2,
        "note": "query heads share KV heads in groups; the practical default",
        "bytesAt32k": 1610612736,
        "bytesPerToken": 49152,
        "tokensBeforeWall": 1627604
      },
      {
        "name": "MQA",
        "kvHeads": 1,
        "note": "every query head reads one KV head; the smallest cache, most sharing",
        "bytesAt32k": 805306368,
        "bytesPerToken": 24576,
        "tokensBeforeWall": 3255208
      }
    ],
    "acceleratorBytes": 80000000000
  },
  "wells": [
    {
      "numeral": "I",
      "headline": "By the end of the sentence it had forgotten the beginning.",
      "standfirst": "One fixed vector had to carry a whole source sentence. Attention's first form let the decoder look at every input position directly -- and it arrives three years before the architecture everyone now associates it with.",
      "pullQuote": "Attention existed for three years before anyone removed the recurrence around it.",
      "keys": [
        "bahdanau_attention"
      ],
      "from": "2014-09-01",
      "to": "2014-09-01"
    },
    {
      "numeral": "II",
      "headline": "The hardware was parallel and the model was not.",
      "standfirst": "Dropping recurrence bought parallel training and cost the model any idea of order. One paper ships the fix, the architecture, and both of the bills this page is about.",
      "pullQuote": "Everything after this on the timeline is somebody paying less of one of those two.",
      "keys": [
        "learned_absolute",
        "standard_attention",
        "sinusoidal"
      ],
      "from": "2017-05-08",
      "to": "2017-06-12"
    },
    {
      "numeral": "III",
      "headline": "Two bills, two crowds.",
      "standfirst": "The compute bill and the cache bill were attacked by different people for different reasons, and a date-ordered list interleaves them into apparent nonsense. Read as two crowds, the six entries here are two arguments running in parallel.",
      "pullQuote": "It moves along the same line rather than leaving it.",
      "keys": [
        "sparse_attention",
        "reformer",
        "sliding_window",
        "mqa",
        "gqa",
        "mla"
      ],
      "from": "2019-04-23",
      "to": "2024-05-07"
    },
    {
      "numeral": "IV",
      "headline": "We shipped a position scheme in 2021 and spent 1,698 days repairing it.",
      "standfirst": "Rotary embeddings solved relative distance elegantly and left one bomb: run past the trained length and the rotation keeps going. Three repairs follow, and the last one is to delete it.",
      "pullQuote": "Stop repairing it and remove it.",
      "keys": [
        "rope",
        "alibi",
        "ntk_aware",
        "yarn",
        "drope"
      ],
      "from": "2021-04-20",
      "to": "2025-12-13"
    },
    {
      "numeral": "V",
      "headline": "Two things we were wrong about.",
      "standfirst": "Neither of these is an optimisation. Both are discoveries about what was already happening -- one about where the cost actually was, one about what models had quietly been doing with the first few tokens all along.",
      "pullQuote": "Nothing mathematically - which is why it is on this list as the exception.",
      "keys": [
        "flashattention",
        "attention_sinks"
      ],
      "from": "2022-05-27",
      "to": "2023-09-29"
    },
    {
      "numeral": "VI",
      "headline": "Then stop keeping everything.",
      "standfirst": "If the cache is the bill, refuse to hold a cache. Fold the past into a fixed-size state instead -- and pay, every time, in the one way none of these six escapes.",
      "pullQuote": "The state is a lossy summary, and what it lost is not recoverable.",
      "keys": [
        "linear_attention",
        "delta_rule",
        "mamba",
        "deltanet_parallel",
        "gated_deltanet",
        "nsa"
      ],
      "from": "2020-06-29",
      "to": "2025-02-16"
    }
  ],
  "perYear": [
    {
      "year": 2014,
      "count": 1
    },
    {
      "year": 2015,
      "count": 0
    },
    {
      "year": 2016,
      "count": 0
    },
    {
      "year": 2017,
      "count": 3
    },
    {
      "year": 2018,
      "count": 0
    },
    {
      "year": 2019,
      "count": 2
    },
    {
      "year": 2020,
      "count": 3
    },
    {
      "year": 2021,
      "count": 3
    },
    {
      "year": 2022,
      "count": 1
    },
    {
      "year": 2023,
      "count": 5
    },
    {
      "year": 2024,
      "count": 3
    },
    {
      "year": 2025,
      "count": 2
    }
  ],
  "transcriptDiscrepancy": {
    "claimedTB": 1.0,
    "computedBytes": 1572864000000,
    "context": 1000000,
    "users": 8
  }
});
