/* The page, built from the run in data.js.
 *
 * Three rules this file follows:
 *
 *   1. No number is written here. Every figure comes from `M`, generated by
 *      tools/render_results.py from results/upcycle.json and — for the first block's per-expert
 *      loads only — from submission_artifacts/run.log, each row checked against the bundle first.
 *   2. A mechanism figure is not a results chart. The conversion is the central object, so the page
 *      draws it before any curve: copies whose weights add up to one compute the original.
 *   3. A failure goes in the opening tiles. Here it is the speed, which belongs to a reference
 *      implementation and says so wherever it appears.
 *
 * Sections carry `data-role`, so the spine is checkable without pinning any wording. Interactive
 * figures follow docs/EXPLAINER_PATTERN.md: guard() → pure stateFor() → render-only show(), and a
 * `playAll` that paints the end state for print and reduced motion. Adjacent widgets never share a
 * family: Diff (the conversion), Accumulator (the balance), a static chart, Budget (the cost).
 */

const NS = 'http://www.w3.org/2000/svg';
const main = () => document.getElementById('main');

function el(tag, cls, text) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
}

function svg(tag, attrs = {}) {
  const n = document.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, String(v));
  /* **A figure is never drawn smaller than it was designed, because its labels shrink with it.**
   * A `viewBox` scales text along with the drawing, so a label authored at a compliant 11px paints
   * at `11 × rendered ÷ viewBox` — 5px on a phone, where the figure is a quarter of its design
   * width. Nothing in the source says so: every declared size on this page is inside
   * `docs/DESIGN.md`'s 9.5–11px band, and the whole reduction happens in the transform.
   *
   * A diagram cannot reflow the way a paragraph can, so the fix is to stop it shrinking: the floor
   * is the viewBox's own width, and the `figure` around it already scrolls. Set here rather than in
   * a stylesheet because the value is a property of each drawing, and a stylesheet would have to
   * repeat every viewBox — a second copy of a number, which is the copy that drifts. */
  if (tag === 'svg' && attrs.viewBox) {
    const designed = Number(String(attrs.viewBox).trim().split(/\s+/)[2]);
    if (Number.isFinite(designed) && designed > 0) n.style.minWidth = `${designed}px`;
  }
  return n;
}

function svgText(x, y, cls, text) {
  const t = svg('text', { x, y, class: cls });
  t.textContent = text;
  return t;
}

let sectionCount = 0;

/** A section whose eyebrow names its epistemic role, so a reader knows how to weigh it. */
function section(id, role, eyebrow, title, paras, rail) {
  const s = el('section');
  s.id = id;
  s.dataset.role = role;
  sectionCount += 1;
  s.dataset.n = String(sectionCount);
  s.dataset.title = (rail && rail.short) || title;
  if (rail && rail.sub) s.dataset.sub = rail.sub;
  s.append(el('p', 'role', eyebrow), el('h2', null, title));
  for (const p of [].concat(paras || [])) {
    const n = el('p', 'say');
    n.innerHTML = p;
    s.append(n);
  }
  main().append(s);
  return s;
}

let figureCount = 0;

/** A figure whose caption says what to conclude — never a bare label.
 *
 * **The number is counted, not passed.** It used to be an argument, and adding the ship figure at
 * the top of the page gave the page two Figure 1s — the new one and the mechanism plate, both
 * captioned "Figure 1", in the same document. A figure's number is a count of the figures before
 * it, which makes it exactly the kind of number this page derives everywhere else.
 */
function figure(node, caption) {
  figureCount += 1;
  const f = el('figure');
  f.append(node);
  const c = el('figcaption');
  c.innerHTML = `<b>Figure ${figureCount}.</b> ${caption}`;
  f.append(c);
  return f;
}

function table(head, rows, cls) {
  const wrap = el('div', 'tablewrap');
  const t = el('table', cls || 'grid');
  const thead = el('thead');
  const hr = el('tr');
  for (const h of head) {
    const th = el('th');
    th.innerHTML = h;
    hr.append(th);
  }
  thead.append(hr);
  t.append(thead);
  const tb = el('tbody');
  for (const row of rows) {
    const tr = el('tr');
    if (row.__mark) tr.className = row.__mark;
    row.cells.forEach((cell, i) => {
      const td = el('td');
      td.innerHTML = cell === null || cell === undefined ? '—' : cell;
      /* The column head, carried on the cell, so a stacked row on a phone can still say which
       * column each line belongs to. Below 640px the `thead` is hidden and every cell becomes a
       * block, at which point a bare value has lost the only thing that gave it meaning — and in
       * the audit table, whose two columns ARE its argument, that is the whole figure. */
      /* Only when there IS one. A blank header — this page has key/value tables built with `['',
       * '']` — would otherwise set `data-head=""`, which still matches `td[data-head]` and paints
       * an empty labelled line above the value. */
      const label = head[i] === undefined ? '' : String(head[i]).replace(/<[^>]*>/g, '').trim();
      if (label) td.dataset.head = label;
      tr.append(td);
    });
    tb.append(tr);
  }
  t.append(tb);
  wrap.append(t);
  return wrap;
}

const int = (n) => Math.round(n).toLocaleString('en-US');
/* Counts are SPELLED from the data, never typed. A heading or a rail label that states a number
 * is stating a count of its own contents, so typing it is how this page came to be headed "Two
 * commands" over three of them. Ported from exercise 08, which introduced it for the same reason. */
const SPELLED = [
  'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
  'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen',
  'nineteen', 'twenty',
];
const spell = (n) => SPELLED[n] || String(n);
const Spell = (n) => {
  const w = spell(n);
  return w[0].toUpperCase() + w.slice(1);
};

const signed = (n, d = 4) => (n >= 0 ? '+' : '−') + Math.abs(n).toFixed(d);
const pct = (n, d = 1) => `${(n * 100).toFixed(d)}%`;
/* A tiny difference in the form a reader can say aloud: 1.6e-5 rather than 0.0000162. */
const sci = (n) => n.toExponential(1).replace('e-', '×10⁻').replace(/⁻(\d+)$/, (_, d) => `⁻${sup(d)}`);
const SUPER = { 0: '⁰', 1: '¹', 2: '²', 3: '³', 4: '⁴', 5: '⁵', 6: '⁶', 7: '⁷', 8: '⁸', 9: '⁹' };
const sup = (digits) => [...digits].map((d) => SUPER[d]).join('');
/* Step numbers as a reader counts them: "after step 112", where the bundle's own index is 111. The
 * renderer already converts, so this only joins a list. */
const steps = (list) =>
  list.length <= 2 ? list.map(int).join(' and ') : `${list.slice(0, -1).map(int).join(', ')} and ${int(list.at(-1))}`;

/* Every interactive figure registers the function that paints its end state. Print and reduced
 * motion call them all, so a reader who never touches a control still gets the whole argument. */
const PLAY = [];
function playable(wrap) {
  PLAY.push(wrap);
  return wrap;
}

/* A drawing inside an interactive figure scrolls in its own box, so on a phone the controls and
 * the prose under it stay put while only the drawing moves. `docs/DESIGN.md`: the svg's own
 * wrapper needs `overflow-x: auto` AND `min-width: 0`, or its floor propagates up the page. */
function scroller(node) {
  const box = el('div', 'chart-scroll');
  box.append(node);
  return box;
}

const reduced = () =>
  typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;

/* ============================================================== the verdicts
 *
 * **Every sentence that states a result is chosen here, from the data, and nowhere else.** The
 * first version of this page generated its numbers and typed its verdicts — "It does.", "pulls ahead
 * late", "Softmax kept over sigmoid", every tile's colour — so a re-run that came out the other way
 * would have printed new numbers under the old conclusions. This function holds no DOM and no layout,
 * which is what lets `tests/test_moe_page_wording.py` feed it a fabricated, reversed run through
 * Node and assert that the words move with the numbers.
 */
export function wording(M) {
  const c = M.continuity;
  const b = M.balance;
  const cont = M.continuation;
  const rt = M.router_trial;
  const exact = c.holds;
  const pos = cont.end_position; // 'ahead' | 'level' | 'behind', at the precision RESULTS.md reports
  const trailed = cont.behind_steps.length > 0;
  const allUsed = b.end_dead === 0;
  const settled = b.end_violation < 1; // the busiest expert anywhere under twice an even share
  const slower = cont.slowdown > 1;
  const other = Object.keys(rt.final_val).find((name) => name !== rt.choice);
  const cap = (w) => w[0].toUpperCase() + w.slice(1);
  const idleTail =
    b.worst_dead === 0
      ? 'no expert was ever idle'
      : allUsed
        ? `none after step ${int(b.last_idle)}`
        : `${spell(b.end_dead)} still idle at the end`;

  return {
    thesisTitle: exact
      ? 'Nothing changes at the conversion, and that is the point'
      : 'The conversion changes the model, and every comparison inherits it',
    startVerdict: exact
      ? 'It does.'
      : `It does not: the loss moved by ${signed(c.val_difference, 6)}, more than rounding, so every
         comparison below is measured from a different place.`,
    lopsided:
      b.last_twice_share === null
        ? 'the router never put twice an even share on any expert'
        : `the router keeps giving some expert twice an even share or more as late as step ${int(b.last_twice_share)}`,
    finish: { ahead: 'final lead over', level: 'level finish with', behind: 'final deficit against' }[pos],
    marks: {
      start: exact ? 'good' : 'bad',
      idle: allUsed ? (b.worst_dead > 0 ? 'watch' : 'good') : 'bad',
      gap: pos === 'behind' ? 'bad' : 'watch',
      speed: slower ? 'bad' : 'good',
    },
    idleKey: `experts idle in a single step at worst, out of the model's ${int(M.params.experts_stored)}
      — ${idleTail}${allUsed ? '. Every expert kept receiving tokens' : ''}`,
    gapKey:
      `the converted model's validation loss minus the dense control's at the end. Lower is better, so
       ${{
         ahead: 'the converted model finished ahead',
         level: 'the two finished level at the precision reported',
         behind: 'the converted model finished behind',
       }[pos]}${trailed && pos === 'ahead' ? ', after trailing in the middle of the run' : ''}. One
       run each: a measurement of two runs, not a ranking`,
    speedKey: `tokens a second, against the dense model's ${int(cont.tokens_per_second.dense)} —
      <b>${slower ? `${cont.slowdown.toFixed(1)}× slower` : `${(1 / cont.slowdown).toFixed(1)}× faster`}</b>,
      in a reference implementation that runs its experts one after another in a Python loop`,
    expected: [
      exact
        ? { outcome: `<b>held</b> — a difference of ${c.val_difference.toFixed(6)} in validation loss`, mark: 'good' }
        : { outcome: `<b>did not hold</b> — the loss moved by ${signed(c.val_difference, 6)}`, mark: 'bad' },
      allUsed
        ? { outcome: `<b>held</b> — at worst ${spell(b.worst_dead)} idle in one step; ${idleTail}`, mark: 'good' }
        : { outcome: `<b>did not hold</b> — ${idleTail}`, mark: 'bad' },
      {
        ahead: {
          outcome: trailed
            ? `<b>held, narrowly</b> — ${signed(cont.end_gap)} at the end, but behind at
               ${spell(cont.behind_steps.length)} validation checks in the middle, from one run each`
            : `<b>held</b> — ${signed(cont.end_gap)} at the end, from one run each`,
          mark: 'warn',
        },
        level: { outcome: `<b>did not hold</b> — the two ended level at the precision reported`, mark: 'warn' },
        behind: { outcome: `<b>did not hold</b> — ${signed(cont.end_gap)} at the end`, mark: 'bad' },
      }[pos],
      slower
        ? {
            outcome: `<b>held</b> — ${cont.slowdown.toFixed(1)}× slower. A token uses
              ${M.params.active_over_dense.toFixed(2)}× the dense model's parameters, but that count
              includes embeddings and is not a measure of compute, so how much of the gap the extra
              arithmetic explains was not measured`,
            mark: 'bad',
          }
        : { outcome: `<b>did not hold</b> — it ran ${(1 / cont.slowdown).toFixed(1)}× faster`, mark: 'good' },
    ],
    routerRow: `${cap(rt.choice)} kept over ${other} scoring`,
    resultsTitle: `${settled ? 'The router evens out' : 'The router stays lopsided'}, and the converted
      model ${{ ahead: trailed ? 'pulls ahead late' : 'stays ahead', level: 'ends level', behind: 'ends behind' }[pos]}`,
    conclusionTitle: `${exact ? 'An exact start' : 'An inexact start'}, ${settled ? 'a balanced router' : 'a lopsided router'},
      and ${{ ahead: 'a lead too small to rank', level: 'no gap to rank', behind: 'a deficit too small to rank' }[pos]}`,
    conclusion: [
      `Copying a trained layer into experts and rescaling the kept mixing weights to add up to one
       ${exact
         ? 'converts a model without changing it beyond rounding — measured here, not assumed'
         : `should convert a model without changing it, and here it did not: the validation loss moved by ${signed(c.val_difference, 6)}`}.
       ${settled
         ? `From that start ${b.last_twice_share === null ? 'the router stayed close to even' : `the router piled tokens onto a few experts until step ${int(b.last_twice_share)} and then evened out`}`
         : 'The router was still lopsided at the end'}${allUsed && b.last_idle !== null ? `, with no expert idle after step ${int(b.last_idle)}` : ''}.`,
      `${{
        ahead: `The converted model ends ${signed(cont.end_gap)} against an unconverted model given the same training${trailed ? ', after trailing it in the middle' : ''}.`,
        level: 'The converted model ends level with an unconverted model given the same training.',
        behind: `The converted model ends ${signed(cont.end_gap)} behind an unconverted model given the same training.`,
      }[pos]} That is a result about these two runs. Whether it is a result about the design needs
       more than one seed.`,
    ],
    longer: {
      ahead: trailed
        ? "Whether the converted model's late lead grows, holds or closes"
        : "Whether the converted model's lead grows, holds or closes",
      level: 'Whether the two models stay level or part',
      behind: "Whether the converted model's deficit closes",
    }[pos],
    balanceHead: b.fell
      ? `The largest imbalance fell over the run while the bias was adjusting by ${M.config.bias_rate} a
         step.`
      : 'The largest imbalance did not fall over the run.',
  };
}

/* ============================================================== 1 · thesis */

function chapterThesis(M, W) {
  const c = M.continuity;
  const b = M.balance;
  const cont = M.continuation;
  const s = section(
    'thesis',
    'thesis',
    'Converted, not retrained',
    W.thesisTitle,
    [
      `Every claim below rests on one before-and-after. The converted model has to start exactly
       where the dense one stopped, or "it kept learning" is measured from somewhere else.
       <b>${W.startVerdict}</b> What happens next is less tidy: ${W.lopsided}, and the converted
       model's ${W.finish} the dense control is the evidence of a single run.`,
    ],
    { short: 'The claim', sub: 'an exact start, then a single run' }
  );

  const routerNote =
    c.largest_router === c.used_router
      ? `under the ${c.used_router} router the run used`
      : `under the ${c.largest_router} router, which was tried and not used; under the
         ${c.used_router} router the run used it was ${sci(c.used_router_difference)}`;
  const tiles = el('div', 'tiles');
  for (const [v, k, mark] of [
    [
      c.val_difference.toFixed(6),
      `change in validation loss from converting — <b>${c.val_dense.toFixed(6)}</b> before,
       <b>${c.val_upcycled.toFixed(6)}</b> after. The largest change in any next-token score on a fixed
       test batch was ${sci(c.largest_logit_difference)}, ${routerNote}`,
      W.marks.start,
    ],
    [`${int(b.worst_dead)} → ${int(b.end_dead)}`, W.idleKey, W.marks.idle],
    [signed(cont.end_gap), W.gapKey, W.marks.gap],
    [int(cont.tokens_per_second.moe), W.speedKey, W.marks.speed],
  ]) {
    const tile = el('div', `tile ${mark}`);
    const value = el('div', 'tile-v');
    value.innerHTML = v;
    const key = el('div', 'tile-k');
    key.innerHTML = k;
    tile.append(value, key);
    tiles.append(tile);
  }
  s.append(tiles);

  const note = el('p', 'say small');
  note.innerHTML = `The <b>dense control</b> is the unconverted model, trained on exactly the same
    further text in the same order, so a difference between the two is the experts' doing rather
    than more training's.${
      W.marks.speed === 'bad'
        ? ` The red tile is a failure of this implementation rather than of the idea, and it is on the
           first screen deliberately: an optimised mixture of experts does not loop over its experts in
           Python, so this speed says nothing about one.`
        : ''
    }`;
  s.append(note);
}

/* ============================================================== 2 · glossary */

function chapterGlossary(M) {
  const cfg = M.config;
  const p = M.params;
  const b = M.balance;
  const cont = M.continuation;
  const rt = M.router_trial;
  /* Built BEFORE the section, so the heading can count them. */
  const entries = [
    [
      'a dense model',
      `One where every token passes through the same layers. Ours has ${cfg.depth} blocks, each
       ${cfg.width} numbers wide, and ${int(p.dense)} parameters in all.`,
    ],
    [
      'the dense control',
      `The dense model, left unconverted and trained on exactly the same ${int(cont.tokens)} further
       tokens in the same order — so what it gains is what more training buys, without experts.`,
    ],
    [
      'feed-forward layer',
      `The part of each block that works on one token at a time, after attention has mixed in its
       context. It is the part that gets copied: ${int(p.per_expert)} parameters per block.`,
    ],
    [
      'an expert',
      `One copy of a block's feed-forward layer. Each block gets ${cfg.n_experts}, so the converted
       model stores ${int(p.experts_stored)} of them.`,
    ],
    [
      'load',
      `The share of a block's tokens that chose an expert in one step. Each token picks
       ${cfg.top_k}, so a block's loads add up to ${cfg.top_k} and an even split is
       ${b.even_share} each.`,
    ],
    [
      'imbalance',
      `How far a block's busiest expert sits above an even split, counted in even shares: its load
       divided by ${b.even_share}, minus one. 0 is perfectly even; ${b.ceiling} means one expert was
       chosen by every token in its block. The largest over every block ended this run at
       ${b.end_violation.toFixed(3)}.`,
    ],
    [
      'the router',
      `A small layer that scores every expert for every token — ${int(p.router_per_layer)} router
       parameters per block, ${cfg.width} inputs by ${cfg.n_experts} experts. They start small, so
       its scores start nearly equal; but the top scores still decide, and after the first step the
       largest imbalance was already ${b.first_violation.toFixed(2)}.`,
    ],
    [
      'softmax or sigmoid',
      `${Spell(Object.keys(rt.final_val).length)} ways the router can turn raw scores into scores between zero and one: softmax makes the
       experts compete, so a token's scores over all ${cfg.n_experts} add up to one; sigmoid scores
       each expert on its own. Each was tried for ${int(rt.tokens)} tokens, and ${rt.choice} was kept.`,
    ],
    [
      'mixing weights',
      `Each token goes to its ${cfg.top_k} best-scoring experts and pays for those alone. Their scores,
       rescaled to add up to one, are the mixing weights its output is blended by — and the rescaling
       is what makes the conversion exact.`,
    ],
    [
      'upcycling',
      `Converting a trained dense model by copying each feed-forward layer into every expert and
       adding a router. Ours goes from ${int(p.dense)} parameters to ${int(p.total)}.`,
    ],
    [
      'active parameters',
      `What one token actually uses: everything shared, plus ${cfg.top_k} experts per block —
       ${int(p.active)} here, ${pct(p.active_share, 0)} of what the model stores.`,
    ],
    [
      'an idle expert',
      `One that received no tokens at all in a step, so learned nothing from it. Counted across all
       ${int(p.experts_stored)}; the worst step had ${int(b.worst_dead)}.`,
    ],
    [
      'the balancing bias',
      `A number per expert added to its score <b>only when choosing</b>, never to its mixing weight.
       After every step a busy expert's bias drops by ${cfg.bias_rate} and a quiet one's rises by the
       same, with no extra term in the loss.`,
    ],
    [
      'validation loss',
      `How wrong the model's next-token guesses are on text it never trains on: ${int(cfg.val_windows)}
       windows of ${cfg.seq_len} tokens, every ${cfg.val_every} steps. Lower is better; both models
       start at ${cont.start.toFixed(4)}.`,
    ],
    [
      're-warming',
      `Raising the learning rate again before training on: up to ${cont.lr} over the first
       ${cfg.warmup_steps} steps, then down a cosine to ${cont.floor_lr} by step ${int(cont.steps)}.`,
    ],
  ];
  const s = section(
    'glossary',
    'glossary',
    'Before anything else',
    `${Spell(entries.length)} words you need, each with a number from this run`,
    [
      `Read this once and nothing below is jargon. Every entry carries a real figure from the run on
       this page rather than a textbook gloss.`,
    ],
    { short: 'The words', sub: 'each with a figure from the run' }
  );

  const dl = el('dl', 'gloss');
  for (const [term, def] of entries) {
    dl.append(el('dt', null, term));
    const dd = el('dd');
    dd.innerHTML = def;
    dl.append(dd);
  }
  s.append(dl);
}

/* ============================================================== 3 · the problem */

function chapterProblem(M) {
  const p = M.params;
  const cfg = M.config;
  const s = section(
    'problem',
    'problem',
    'The problem',
    'A bigger model usually means starting over',
    [
      `<b>A mixture of experts stores far more parameters than any one token pays for.</b> Each block
       keeps several copies of its feed-forward layer — the experts — and sends each token through
       only a few of them. Here the model stores ${int(p.total)} parameters and each token uses
       ${int(p.active)}: ${cfg.top_k} of the ${cfg.n_experts} experts in each of its ${cfg.depth}
       blocks, plus everything the blocks share.`,
      `Building one normally means a new training run from nothing, and the run already paid for is
       thrown away. Converting a trained model avoids that only if the conversion is <b>exact</b>. If
       it changes what the model computes, even slightly, the new model starts somewhere the old one
       never was and has to earn its way back.`,
      `An exact start is not the end of it. The copies are identical, so if the router keeps sending
       every token to the same few, the rest never receive a gradient and stay copies for good. And
       a model that stores ${p.total_over_dense.toFixed(1)}× the parameters is expected to do better
       per step, so a lower loss proves little unless the unconverted model is given the same
       training too.`,
    ],
    { short: 'The problem', sub: 'what has to hold for this to work' }
  );

  s.append(
    table(
      ['the question', 'where it is answered'],
      [
        { cells: ['Is the start exact?', 'the conversion, drawn in <a href="#mechanism">the next section</a> and measured on the real model'] },
        { cells: ['Do all the experts get used?', 'the balance over training, in <a href="#results">what happened</a>'] },
        { cells: ['Is any gain the experts’, or just more training?', 'the dense control, trained on the same tokens in the same order'] },
        { cells: ['What does it cost?', 'parameters stored, parameters each token uses, and speed'] },
      ]
    )
  );
}

/* ============================================================== 4 · mechanism */

/* -------------------------------------------------------- Figure: the conversion (Diff)
 *
 * Family: Diff (EXPLAINER_PROMPT §10) — "these look equivalent and are not", run in the direction
 * this exercise needs: two blocks that look different (one layer against eight experts and a
 * router) and are the same, PROVIDED the kept mixing weights are rescaled. The reader feeds both the
 * same token, picks any experts, and can switch the rescaling off to see what it prevents.
 *
 * It opens on the rescaled state, the one the model actually runs, so the caption's claim is the
 * first thing drawn. The mixing weights are CONSTRUCTED — a router that scores every expert alike —
 * and the drawing says so beside them; the measured difference sits in the pill.
 */
function conversionFigure(M) {
  const cfg = M.config;
  const c = M.continuity;
  const n = cfg.n_experts;
  const k = cfg.top_k;

  /* 1. CONSTANTS — layout only. Every data value is from M.
   *
   * Stacked, dense block above converted block, rather than side by side: side by side the drawing
   * was 680 units wide, so on a phone the converted block — the half the figure is about — sat
   * behind a horizontal scroll. Stacked it is 300, which a 390px screen shows whole. */
  const W = 300;
  const LEFT = 4;
  const UNIT = 280; // the width the dense output is drawn at; a scale, not a datum
  const GAP = 5;
  const BOXW = (W - 2 * LEFT - (n - 1) * GAP) / n;
  const boxX = (i) => LEFT + i * (BOXW + GAP);
  const TOP2 = 164; // where the converted block begins
  const H = TOP2 + 226;

  /* 3. STATE — the minimum that cannot be derived. */
  let chosen = new Set(Array.from({ length: k }, (_, i) => i));
  let mode = 'rescaled';

  const wrap = el('div', 'dx');
  wrap.setAttribute('role', 'group');
  wrap.setAttribute('aria-label', 'The conversion: a dense block above its converted copy');

  const node = svg('svg', {
    viewBox: `0 0 ${W} ${H}`,
    class: 'chart dxfig',
    role: 'img',
    'aria-label':
      'A dense block and its converted copy fed the same token. A router keeps the best-scoring ' +
      'experts; each is a copy of the dense layer, so the converted output is the dense output ' +
      'times the sum of the mixing weights.',
  });
  node.append(
    svgText(LEFT, 14, 'fig-lab', 'dense block'),
    svg('rect', { x: LEFT, y: 24, width: W - 2 * LEFT, height: 36, rx: 8, class: 'dx-box' }),
    svgText(W / 2, 46, 'dx-t mid', 'feed-forward layer'),
    svg('line', { x1: W / 2, x2: W / 2, y1: 62, y2: 84, class: 'dx-wire' }),
    svg('rect', { x: LEFT, y: 86, width: UNIT, height: 22, rx: 5, class: 'dx-out dense' }),
    svgText(LEFT, 126, 'dx-lab', 'output = dense(x)'),
    svg('line', { x1: LEFT, x2: W - LEFT, y1: TOP2 - 22, y2: TOP2 - 22, class: 'gridline' }),
    svgText(LEFT, TOP2, 'fig-lab', 'converted block'),
    svg('rect', { x: LEFT, y: TOP2 + 10, width: W - 2 * LEFT, height: 26, rx: 6, class: 'dx-box' }),
    svgText(W / 2, TOP2 + 27, 'dx-t mid', `router: keeps the ${spell(k)} best of ${n}`)
  );

  const boxes = [];
  const weights = [];
  for (let i = 0; i < n; i += 1) {
    const r = svg('rect', { x: boxX(i), y: TOP2 + 46, width: BOXW, height: 34, rx: 6, class: 'dx-ex' });
    const t = svgText(boxX(i) + BOXW / 2, TOP2 + 67, 'dx-t mid', `E${i + 1}`);
    const w = svgText(boxX(i) + BOXW / 2, TOP2 + 96, 'dx-w mid', '');
    boxes.push(r);
    weights.push(w);
    node.append(r, t, w);
  }
  const sumText = svgText(LEFT, TOP2 + 132, 'dx-lab', '');
  const ghost = svg('rect', { x: LEFT, y: TOP2 + 142, width: UNIT, height: 22, rx: 5, class: 'dx-ghost' });
  const out = svg('rect', { x: LEFT, y: TOP2 + 142, width: UNIT, height: 22, rx: 5, class: 'dx-out conv' });
  const outText = svgText(LEFT, TOP2 + 182, 'dx-lab', '');
  const verdictText = svgText(LEFT, TOP2 + 206, 'dx-verdict', '');
  node.append(
    svgText(LEFT, TOP2 + 112, 'dx-note', `illustrative mixing weights: all ${n} scored alike`),
    sumText,
    ghost,
    out,
    outText,
    verdictText
  );

  /* The controls. Ordinals rather than hues: eight experts are more things than this palette has
   * colours, so the chosen ones are marked by outline and fill weight, and named E1…E8. */
  const pickRow = el('div', 'dx-row');
  pickRow.append(el('span', 'dx-k', 'experts this token goes to'));
  const pick = el('div', 'tabs dx-pick');
  pick.setAttribute('role', 'group');
  pick.setAttribute('aria-label', 'Experts this token goes to');
  const pickBtns = [];
  for (let i = 0; i < n; i += 1) {
    const btn = el('button', null, `E${i + 1}`);
    btn.type = 'button';
    btn.addEventListener('click', () => {
      const next = new Set(chosen);
      if (next.has(i)) next.delete(i);
      else next.add(i);
      show(next, mode);
    });
    pickBtns.push(btn);
    pick.append(btn);
  }
  pickRow.append(pick);

  const modeRow = el('div', 'dx-row');
  modeRow.append(el('span', 'dx-k', 'the mixing weights are'));
  const modes = el('div', 'tabs');
  modes.setAttribute('role', 'group');
  modes.setAttribute('aria-label', 'How the mixing weights are used');
  const modeBtns = {};
  for (const [key, label] of [
    ['rescaled', 'rescaled to add up to one'],
    ['scored', 'used as scored'],
  ]) {
    const btn = el('button', null, label);
    btn.type = 'button';
    btn.addEventListener('click', () => show(chosen, key));
    modeBtns[key] = btn;
    modes.append(btn);
  }
  modeRow.append(modes);

  const read = el('p', 'dx-read');
  const pill = el('div', 'pill');
  pill.innerHTML = `measured on the real model: validation loss ${c.val_dense.toFixed(6)} →
    ${c.val_upcycled.toFixed(6)} · largest next-token score change ${sci(c.used_router_difference)}
    under the ${c.used_router} router`;

  /* guard() — the precondition. A token goes to exactly k experts; any other selection has no
   * honest output to draw, and drawing one would invent a routing the model never does. */
  const guard = (set) =>
    set.size === k
      ? null
      : {
          note: `A token goes to exactly ${spell(k)} experts in this model, and ${spell(set.size)}
                 ${set.size === 1 ? 'is' : 'are'} chosen. Pick ${spell(k)}.`,
        };

  /* stateFor(set, m) — PURE. Selection and mode → every number the renderer needs. */
  const stateFor = (set, m) => {
    const each = m === 'rescaled' ? cfg.rescaled_share : cfg.uniform_score;
    const sum = each * set.size;
    return { each, sum, same: Math.abs(sum - 1) < 1e-12 };
  };

  /* show(set, m) — RENDER ONLY. */
  function show(set, m) {
    chosen = set;
    mode = m;
    pickBtns.forEach((btn, i) => btn.setAttribute('aria-pressed', String(set.has(i))));
    for (const [key, btn] of Object.entries(modeBtns)) btn.setAttribute('aria-pressed', String(key === m));
    boxes.forEach((r, i) => r.classList.toggle('on', set.has(i)));
    const refused = guard(set);
    if (refused) {
      weights.forEach((w) => (w.textContent = ''));
      sumText.textContent = '';
      out.setAttribute('width', 0);
      outText.textContent = 'no output: a token is never routed like this';
      verdictText.textContent = '';
      read.innerHTML = refused.note;
      wrap.dataset.state = 'refused';
      return;
    }
    const st = stateFor(set, m);
    weights.forEach((w, i) => (w.textContent = set.has(i) ? st.each.toFixed(3) : ''));
    sumText.textContent = `mixing weights add up to ${st.sum.toFixed(3)}`;
    out.setAttribute('width', (UNIT * st.sum).toFixed(1));
    outText.textContent = `output = ${st.sum.toFixed(3)} × dense(x)`;
    verdictText.textContent = st.same ? 'the same output as the dense block' : 'not the dense block';
    verdictText.setAttribute('class', `dx-verdict ${st.same ? 'good' : 'bad'}`);
    wrap.dataset.state = st.same ? 'same' : 'different';
    read.innerHTML = st.same
      ? `<b>Rescaled, the mixing weights add up to one whatever the scores were</b>, so whichever
         ${spell(k)} experts you pick, the block hands back exactly the dense output. That is the
         conversion, and why it cannot change the model.`
      : `<b>In this illustration, used as scored, the mixing weights add up to ${st.sum.toFixed(3)}</b>
         — a router that scores all ${n} experts alike gives each ${cfg.uniform_score}, and only
         ${spell(k)} are kept, so every block's feed-forward output would shrink to
         ${pct(st.sum, 0)} of what it was. This is the case the rescaling exists to prevent; the
         real model rescales.`;
  }

  wrap.playAll = () => show(new Set(Array.from({ length: k }, (_, i) => i)), 'rescaled');
  wrap.append(scroller(node), pickRow, modeRow, read, pill);
  show(chosen, mode);
  const fig = figure(
    playable(wrap),
    `<b>Whichever experts are chosen, the output is the dense model's — once the kept mixing weights
     are rescaled to add up to one.</b> Every expert starts as the same copy, so the choice cannot
     matter; only the sum of the mixing weights can. Switch the rescaling off: a router that rates all
     ${n} experts alike leaves the ${spell(k)} kept ones summing to ${cfg.uniform_kept_sum}, and the
     block's output is cut by that much. The mixing weights drawn are illustrative; the measured difference
     in the real model is in the pill. <b>What would refute it:</b> a validation loss after
     conversion that differed from the dense model's by more than rounding.`
  );
  fig.id = 'fig-conversion';
  return fig;
}

function chapterMechanism(M) {
  const cfg = M.config;
  const c = M.continuity;
  const s = section(
    'mechanism',
    'mechanism',
    'Inside one block',
    'Copies that add up to the original',
    [
      `Take one block's trained feed-forward layer and copy it ${spell(cfg.n_experts)} times. Add a
       router that scores each copy for each token, keep the ${spell(cfg.top_k)} highest, and blend
       their outputs by those scores — the <b>mixing weights</b>. Because every copy is the same
       function, the blend is that function times the sum of the mixing weights, so <b>if the mixing
       weights add up to one, the block computes exactly what it did before</b>.`,
      `That "if" is the whole conversion. Scores spread over all ${cfg.n_experts} experts do not add up
       to one over just the ones kept, so the kept ones are rescaled. Below, the same token goes into
       the dense block and the converted one: pick any experts, and switch the rescaling off to see
       what it prevents.`,
    ],
    { short: 'The conversion', sub: 'copies whose mixing weights add up to one' }
  );

  s.append(conversionFigure(M));

  const others = Object.keys(c.by_router).filter((name) => name !== c.used_router);
  const measured = el('p', 'say');
  measured.innerHTML = `Measured on the real model rather than on this drawing, the validation loss is
    <b>${c.val_dense.toFixed(6)}</b> before the conversion and <b>${c.val_upcycled.toFixed(6)}</b>
    after it. The largest change in any next-token score on a fixed test batch is
    ${sci(c.used_router_difference)} under the ${c.used_router} router the run used${
      others.length
        ? `, and ${others.map((name) => `${sci(c.by_router[name].largest_logit_difference)} under ${name}`).join(', ')}, tried and not used`
        : ''
    }. ${
      c.holds
        ? 'That is rounding — the order in which a computer adds the same numbers — and not a change in what the model knows.'
        : 'That is more than rounding: the converted model does not start where the dense one stopped.'
    }`;
  s.append(measured);

  const drift = el('p', 'say');
  drift.innerHTML = `After the conversion the copies can grow apart, because different tokens reach
    different experts and push their model weights different ways — this run records which experts
    were chosen, not how far apart their model weights moved. The risk is a router that keeps choosing the
    same few, leaving the rest as untouched copies. So each expert carries a bias that is added to its
    score <b>only when choosing</b> — never to its mixing weight, so the output is still blended by the
    real scores — and after every step a busy expert's bias goes down by ${cfg.bias_rate} and a quiet
    one's goes up by the same. There is no extra term in the loss pulling against the language model
    (the scheme is from arXiv:2408.15664).`;
  s.append(drift);
}

/* ============================================================== 5 · method */

function chapterMethod(M) {
  const cfg = M.config;
  const p = M.params;
  const rt = M.router_trial;
  const cont = M.continuation;
  const s = section(
    'method',
    'method',
    'The apparatus',
    'The trained model, converted, then trained on beside itself',
    [
      `Everything starts from the dense model another exercise in this series trained and published,
       loaded by digest so this run is tied to that one. The converted model and the dense control
       then train on <b>the same batches in the same order</b> with the same schedule, which is what
       lets the difference between them be read as the experts' doing.`,
    ],
    { short: 'The apparatus', sub: 'one model, its control, one machine' }
  );

  s.append(
    table(
      ['setting', 'value'],
      [
        {
          cells: [
            'the dense model',
            `${M.dense_origin.source} — ${cfg.depth} blocks, ${cfg.width} wide, ${int(p.dense)}
             parameters`,
          ],
        },
        {
          cells: [
            'the conversion',
            `${cfg.n_experts} experts per block, ${cfg.top_k} per token, a ${cfg.router} router`,
          ],
        },
        {
          cells: [
            'choosing the router',
            `${int(rt.tokens)} tokens each for softmax and sigmoid scoring; the lower validation loss
             is kept`,
          ],
        },
        {
          cells: [
            'training on',
            `${int(cont.tokens)} further tokens for each model, peak learning rate ${cont.lr} —
             ${pct(cfg.continue_lr_fraction, 0)} of the ${cont.dense_peak_lr} the dense model trained
             at`,
          ],
          __mark: 'warn',
        },
        { cells: ['balancing', `bias step ${cfg.bias_rate} after every step, no auxiliary loss`] },
        {
          cells: [
            'measured on',
            `${int(cfg.val_windows)} held-out windows of ${cfg.seq_len} tokens, every
             ${cfg.val_every} steps`,
          ],
        },
        { cells: ['machine', `${M.device} · ${int(M.seconds)} seconds for every run together`] },
      ]
    )
  );

  const note = el('p', 'say');
  note.innerHTML = `<b>The highlighted row is the one that shapes the curves.</b> The dense model had
    finished its schedule at a low learning rate; carrying on there would barely move it, so both
    models are re-warmed to a new peak before decaying again. The validation text is also split in
    half: the router is chosen on the first half, and every other validation figure on this page is
    measured on the second, so the choice cannot flatter the converted model — the only one it is
    applied to.`;
  s.append(note);
}

/* ============================================================== 6 · expected */

const DECISIONS_URL =
  'https://github.com/pankajkr23/llm-pretraining-exercises/blob/main/src/exercises/14-moe/DECISIONS.md';

function chapterExpected(M, W) {
  const s = section(
    'expected',
    'expected',
    'What the design predicts',
    'What should happen, if the design is right',
    [
      `Each line below follows from a decision recorded with the exercise, in its
       <a href="${DECISIONS_URL}">decisions document</a>, which means each could have come out the
       other way. The right-hand column is what the run did.`,
    ],
    { short: 'The predictions', sub: 'what the design commits to' }
  );

  const predictions = [
    'The converted model starts at <b>exactly</b> the dense model’s loss',
    'Every expert keeps receiving tokens, rather than some going unused for good',
    'Storing more parameters, the converted model ends below the dense control',
    'It runs slower than the dense model',
  ];
  s.append(
    table(
      ['prediction', 'outcome'],
      predictions.map((text, i) => ({ cells: [text, W.expected[i].outcome], __mark: W.expected[i].mark }))
    )
  );
}

/* ============================================================== 7 · results */

/* -------------------------------------------------------- Figure: the balance (Accumulator)
 *
 * Family: Accumulator — "this compounds". The balancing bias moves by a fixed step after every
 * training step, so its correction accumulates; the reader steps through training and watches the
 * routing change over hundreds of steps. One predict-before-reveal. The caption does not claim the
 * bias caused the change: there is no run without it, and the learning rate was decaying throughout.
 *
 * Two sources, and the figure keeps them apart. The bars are the FIRST block's per-expert loads,
 * which only the log records, every `log_every` steps. The trace and the idle strip are the bundle's
 * figures over EVERY block at EVERY step. The caption says so; it is the easiest thing here to blur.
 */
function balanceFigure(M, W) {
  const cfg = M.config;
  const b = M.balance;
  const rows = M.layer0;
  const total = M.continuation.steps;
  const n = cfg.n_experts;

  const WD = 480;
  const H = 384;
  const X0 = 84;
  const X1 = 472;
  const slot = (X1 - X0) / n;
  const barW = slot * 0.56;
  /* The load axis runs to the largest load the log records, not to 1: no load reached 1 in the
   * first block, and an axis to 1 left a band above the bars that nothing ever entered. */
  const A = { top: 30, base: 150, max: M.layer0_max_load };
  const T = { top: 222, base: 282 };
  const D = { top: 322, base: 356 };
  const yLoad = (v) => A.base - (v / A.max) * (A.base - A.top);
  const xStep = (s) => X0 + ((s - 1) / (total - 1)) * (X1 - X0);
  const yViol = (v) => T.base - (v / b.ceiling) * (T.base - T.top);

  let at = 0;
  let revealed = false;
  let guess = null;

  const wrap = el('div', 'acc');
  wrap.setAttribute('role', 'group');
  wrap.setAttribute('aria-label', 'The router over training: loads, imbalance and idle experts');

  /* Predict before reveal — the idle strip stays veiled until the reader commits. The answer is in
   * the prose after the figure as well, so a reader who never guesses still gets it. */
  const ask = el('div', 'acc-ask');
  const askP = el('p', 'acc-q');
  askP.innerHTML = `<b>Guess first.</b> Of all ${int(M.params.experts_stored)} experts in the model,
    what is the most that sat <b>idle</b> — no tokens at all — in a single step?`;
  const guessIn = el('input');
  guessIn.type = 'range';
  guessIn.min = '0';
  guessIn.max = String(M.params.experts_stored);
  guessIn.step = '1';
  guessIn.value = '0';
  guessIn.id = 'acc-guess';
  guessIn.setAttribute('aria-label', 'Your guess: the most experts idle in one step');
  const guessOut = el('output', 'acc-gout', '0');
  guessOut.htmlFor = 'acc-guess';
  const revealBtn = el('button', 'acc-reveal', 'Reveal');
  revealBtn.type = 'button';
  const answer = el('p', 'acc-answer');
  const askRow = el('div', 'acc-askrow');
  askRow.append(guessIn, guessOut, revealBtn);
  ask.append(askP, askRow, answer);
  guessIn.addEventListener('input', () => {
    guessOut.textContent = guessIn.value;
  });
  revealBtn.addEventListener('click', () => {
    guess = Number(guessIn.value);
    revealed = true;
    show(at);
  });

  const node = svg('svg', {
    viewBox: `0 0 ${WD} ${H}`,
    class: 'chart accfig',
    role: 'img',
    'aria-label':
      'Per-expert loads in the first block at the chosen step, against an even share; below, the ' +
      'largest imbalance over every block at every step, and the steps that had idle experts.',
  });

  /* Panel A — the first block's loads. Values sit in their own row under the expert names, clear of
   * the dashed even-share line they used to be drawn across. */
  node.append(svgText(X0, 16, 'fig-lab', 'first block only · share of tokens per expert'));
  for (const [v, label] of [
    [0, '0'],
    [b.even_share, `even ${b.even_share}`],
    [A.max, String(A.max)],
  ]) {
    node.append(
      svg('line', { x1: X0, x2: X1, y1: yLoad(v), y2: yLoad(v), class: v === b.even_share ? 'acc-even' : 'gridline' }),
      svgText(X0 - 6, yLoad(v) + 4, 'ax end', label)
    );
  }
  const bars = [];
  const vals = [];
  for (let i = 0; i < n; i += 1) {
    const cx = X0 + slot * i + slot / 2;
    const r = svg('rect', { x: cx - barW / 2, y: A.base, width: barW, height: 0, rx: 3, class: 'acc-bar' });
    const v = svgText(cx, A.base + 30, 'acc-v mid', '');
    bars.push(r);
    vals.push(v);
    node.append(r, v, svgText(cx, A.base + 15, 'ax mid', `E${i + 1}`));
  }

  /* Panel B — the largest imbalance over every block, every step. */
  node.append(svgText(X0, T.top - 12, 'fig-lab', 'every block · largest imbalance at each step'));
  node.append(
    svg('line', { x1: X0, x2: X1, y1: T.base, y2: T.base, class: 'gridline' }),
    svg('line', { x1: X0, x2: X1, y1: T.top, y2: T.top, class: 'gridline' }),
    svgText(X0 - 6, T.base + 4, 'ax end', '0'),
    svgText(X0 - 6, T.top + 4, 'ax end', String(b.ceiling))
  );
  const d = b.violation.map((v, i) => `${i ? 'L' : 'M'}${xStep(i + 1).toFixed(1)},${yViol(v).toFixed(1)}`).join(' ');
  node.append(svg('path', { d, class: 'acc-trace' }));

  /* Panel C — idle experts, every block, every step; veiled until the reader guesses. */
  node.append(svgText(X0, D.top - 12, 'fig-lab', 'every block · experts idle at each step'));
  const strip = svg('g', { class: 'acc-idle' });
  strip.append(svg('line', { x1: X0, x2: X1, y1: D.base, y2: D.base, class: 'gridline' }));
  b.dead.forEach((count, i) => {
    if (!count) return;
    const x = xStep(i + 1);
    const h = (count / b.worst_dead) * (D.base - D.top);
    strip.append(svg('line', { x1: x, x2: x, y1: D.base, y2: D.base - h, class: count === b.worst_dead ? 'acc-tick worst' : 'acc-tick' }));
  });
  const veil = svgText((X0 + X1) / 2, D.base - 10, 'acc-veil mid', 'hidden until you guess, above');
  node.append(strip, veil);
  node.append(
    svgText(X0, H - 6, 'ax', 'step 1'),
    svgText(X1, H - 6, 'ax end', `step ${int(total)}`)
  );
  const cursor = svg('line', { x1: X0, x2: X0, y1: T.top - 6, y2: D.base + 4, class: 'acc-cursor' });
  const dot = svg('circle', { cx: X0, cy: T.base, r: 4, class: 'acc-dot' });
  node.append(cursor, dot);

  /* The scrubber. */
  const ctl = el('div', 'acc-ctl');
  const slider = el('input');
  slider.type = 'range';
  slider.min = '0';
  slider.max = String(rows.length - 1);
  slider.step = '1';
  slider.value = '0';
  slider.id = 'acc-step';
  slider.setAttribute('aria-label', 'Step through training');
  const where = el('output', 'acc-where');
  where.htmlFor = 'acc-step';
  ctl.append(slider, where);
  slider.addEventListener('input', () => show(Number(slider.value)));

  const read = el('div', 'acc-read');

  /* guard() — every row was checked against the bundle by the renderer, so the only refusal left
   * is an index outside the log. */
  const guard = (i) => (i >= 0 && i < rows.length ? null : { note: 'No logged step there.' });

  /* stateFor(i) — PURE. The first block's imbalance is computed exactly as the glossary defines
   * the measure, so the readout and the trace below it are on one scale. */
  const stateFor = (i) => {
    const row = rows[i];
    const busiest = row.loads.indexOf(Math.max(...row.loads));
    return {
      step: row.step,
      loads: row.loads,
      busiest,
      busiestLoad: row.loads[busiest],
      own: row.loads[busiest] / b.even_share - 1,
      violation: b.violation[row.step - 1],
      idle: b.dead[row.step - 1],
      bound: row.step * cfg.bias_rate,
    };
  };

  /* show(i) — RENDER ONLY. */
  function show(i) {
    at = i;
    slider.value = String(i);
    const refused = guard(i);
    if (refused) {
      read.textContent = refused.note;
      return;
    }
    const st = stateFor(i);
    bars.forEach((r, e) => {
      r.setAttribute('y', yLoad(st.loads[e]).toFixed(1));
      r.setAttribute('height', (A.base - yLoad(st.loads[e])).toFixed(1));
      r.classList.toggle('top', e === st.busiest);
      vals[e].textContent = st.loads[e].toFixed(3);
    });
    const x = xStep(st.step);
    cursor.setAttribute('x1', x.toFixed(1));
    cursor.setAttribute('x2', x.toFixed(1));
    dot.setAttribute('cx', x.toFixed(1));
    dot.setAttribute('cy', yViol(st.violation).toFixed(1));
    where.textContent = `after step ${int(st.step)} of ${int(total)}`;
    wrap.classList.toggle('revealed', revealed);
    veil.style.display = revealed ? 'none' : '';
    read.innerHTML = `
      <p><span class="acc-k">first block</span> the busiest expert, <b>E${st.busiest + 1}</b>, was
        chosen by ${st.busiestLoad.toFixed(3)} of its tokens — an imbalance of
        <b>${st.own.toFixed(2)}</b> in this block alone.</p>
      <p><span class="acc-k">every block</span> largest imbalance <b>${st.violation.toFixed(3)}</b> ·
        idle experts <b>${revealed ? int(st.idle) : 'hidden until you guess'}</b></p>
      <p><span class="acc-k">the bias</span> after ${int(st.step)} steps of ${cfg.bias_rate}, no
        expert's bias can have moved more than ${st.bound.toFixed(3)} — a bound, since the run does
        not record the biases themselves.</p>`;
    const where2 = b.worst_dead === 0 ? '' : `, after step${b.worst_dead_steps.length > 1 ? 's' : ''} ${steps(b.worst_dead_steps)}`;
    answer.innerHTML = revealed
      ? `${guess === null ? '' : `You guessed <b>${int(guess)}</b>. `}The most was
         <b class="acc-most">${int(b.worst_dead)}</b>${where2}${
           b.last_idle === null ? '' : b.end_dead === 0 ? `, and none at all after step ${int(b.last_idle)}` : ''
         }.`
      : '';
    revealBtn.disabled = revealed;
  }

  wrap.playAll = () => {
    revealed = true;
    show(rows.length - 1);
  };
  wrap.append(ask, scroller(node), ctl, read);
  show(0);
  const refute =
    b.last_idle === null
      ? 'there were none at all'
      : b.end_dead === 0
        ? `the strip says they stop after step ${int(b.last_idle)}`
        : 'the strip shows them still appearing at the end';
  const fig = figure(
    playable(wrap),
    `<b>${W.balanceHead}</b> That is the two happening together, not one causing the other: there is no
     run without the bias, and the learning rate was decaying all the while. The bars are the
     <b>first block only</b> — the one block whose per-expert loads the training log records, every
     ${cfg.log_every} steps and rounded as the log writes them. The imbalance trace and the idle strip
     are over <b>every block, at every step</b>, from the results file. So a bar chart that looks even
     can sit above a trace that is not: another block can be lopsided while the first one is fine.
     <b>What would refute the balancing:</b> idle experts that keep appearing to the end of the run;
     ${refute}.`
  );
  fig.id = 'fig-balance';
  return fig;
}

/* -------------------------------------------------------- Figure: validation, MoE against dense */

function validationFigure(M) {
  const cont = M.continuation;
  const cv = M.curves;
  const total = cont.steps;
  const W = 480;
  const H = 438;
  const X0 = 50;
  const X1 = 360;
  const xs = (s) => X0 + (s / total) * (X1 - X0);

  const node = svg('svg', {
    viewBox: `0 0 ${W} ${H}`,
    class: 'chart valfig',
    role: 'img',
    'aria-label':
      'Validation loss of the converted model and the dense control over training; below, their ' +
      'training-loss difference on identical batches; below that, the learning rate both followed.',
  });

  /* Panel A — validation. */
  const A = { top: 30, base: 200 };
  const all = cont.val.flatMap((p) => [p.moe, p.dense]);
  const lo = Math.min(...all);
  const hi = Math.max(...all);
  const pad = (hi - lo) * 0.08;
  const ya = (v) => A.base - ((v - (lo - pad)) / (hi - lo + 2 * pad)) * (A.base - A.top);
  node.append(svgText(X0, 16, 'fig-lab', 'validation loss, measured on held-out text'));
  for (const v of [lo, (lo + hi) / 2, hi]) {
    node.append(
      svg('line', { x1: X0, x2: X1, y1: ya(v), y2: ya(v), class: 'gridline' }),
      svgText(X0 - 6, ya(v) + 4, 'ax end', v.toFixed(3))
    );
  }
  const line = (key) => cont.val.map((p, i) => `${i ? 'L' : 'M'}${xs(p.step).toFixed(1)},${ya(p[key]).toFixed(1)}`).join(' ');
  node.append(svg('path', { d: line('dense'), class: 'series dense' }), svg('path', { d: line('moe'), class: 'series moe' }));
  for (const p of cont.val) {
    node.append(
      svg('rect', { x: xs(p.step) - 3.5, y: ya(p.dense) - 3.5, width: 7, height: 7, class: 'mk dense' }),
      svg('circle', { cx: xs(p.step), cy: ya(p.moe), r: 4, class: 'mk moe' })
    );
  }
  const endM = cont.val.at(-1);
  /* End labels placed apart from each other by at least a line, whichever ends higher. */
  const yM = ya(endM.moe);
  const yD = ya(endM.dense);
  const sep = 13;
  const [lm, ld] = yM > yD ? [Math.max(yM, yD + sep), yD] : [yM, Math.max(yD, yM + sep)];
  node.append(
    svgText(X1 + 10, lm + 4, 'ser-lab moe', `converted ${endM.moe.toFixed(4)}`),
    svgText(X1 + 10, ld + 4, 'ser-lab dense', `dense ${endM.dense.toFixed(4)}`),
    svgText(xs(0) + 8, ya(cont.start) + 16, 'ax', `both start at ${cont.start.toFixed(4)}`)
  );

  /* Panel B — the paired difference on training batches. */
  const B = { top: 252, base: 330 };
  const span = Math.max(...cv.paired.map(Math.abs));
  const yb = (v) => (B.top + B.base) / 2 - (v / span) * ((B.base - B.top) / 2);
  node.append(svgText(X0, B.top - 14, 'fig-lab', `converted minus dense, training loss, ${M.config.log_every}-step means`));
  node.append(
    svg('rect', { x: X0, y: B.top, width: X1 - X0, height: (B.base - B.top) / 2, class: 'acc-behind' }),
    svg('line', { x1: X0, x2: X1, y1: yb(0), y2: yb(0), class: 'zero' }),
    svgText(X0 - 6, yb(0) + 4, 'ax end', '0'),
    svgText(X1 + 10, B.top + 12, 'ax', 'converted behind'),
    svgText(X1 + 10, B.base - 2, 'ax', 'converted ahead')
  );
  const pd = cv.paired.map((v, i) => `${i ? 'L' : 'M'}${xs(cv.step[i]).toFixed(1)},${yb(v).toFixed(1)}`).join(' ');
  node.append(svg('path', { d: pd, class: 'series paired' }));

  /* Panel C — the learning rate both arms followed, from the log. */
  const C = { top: 376, base: 410 };
  const peak = Math.max(...cv.lr.map((r) => r.lr));
  const yc = (v) => C.base - (v / peak) * (C.base - C.top);
  node.append(svgText(X0, C.top - 10, 'fig-lab', `learning rate, both models · peak ${cont.lr}`));
  const area =
    `M${xs(0).toFixed(1)},${C.base} ` +
    cv.lr.map((r) => `L${xs(r.step).toFixed(1)},${yc(r.lr).toFixed(1)}`).join(' ') +
    ` L${xs(total).toFixed(1)},${C.base} Z`;
  node.append(svg('path', { d: area, class: 'lr-area' }), svg('line', { x1: X0, x2: X1, y1: C.base, y2: C.base, class: 'gridline' }));
  node.append(svgText(X0, H - 6, 'ax', 'start'), svgText(X1, H - 6, 'ax end', `step ${int(total)}`));

  const rise = cont.both_rise
    ? `<b>Both models get worse before they get better, so the rise belongs to the schedule and not
       to the conversion</b> — the dense control climbs too, to ${cont.dense_peak.toFixed(4)}
       against the converted model's ${cont.moe_peak.toFixed(4)}, as the learning rate is raised
       again.`
    : `<b>The two models do not both rise first</b>, so any early rise is not the schedule's alone.`;
  const level = cont.level_steps.length
    ? ` They are level, at the precision reported, at step${cont.level_steps.length > 1 ? 's' : ''} ${steps(cont.level_steps)}.`
    : '';
  const middle =
    cont.behind_steps.length && cont.ahead_from !== null
      ? `The converted model then trails from step ${int(cont.behind_steps[0])} to
         ${int(cont.behind_steps.at(-1))} and is ahead at every measurement from step
         ${int(cont.ahead_from)}, ending ${signed(cont.end_gap)}.${level}`
      : `The converted model ends ${signed(cont.end_gap)} against the control.${level}`;
  const fig = figure(
    node,
    `${rise} ${middle} The middle panel shows the same comparison on the training batches, where both
     models read identical text, so the batch-to-batch noise cancels. <b>What would refute the
     gain:</b> a spread between seeds as large as the gap itself — which a single run cannot
     measure.`
  );
  fig.id = 'fig-validation';
  return fig;
}

/* -------------------------------------------------------- Figure: what a token pays (Budget)
 *
 * Family: Budget — "you cannot have everything". The model stores every expert; a token draws k of
 * them. The reader moves k and watches what a token pays climb towards what is stored. Only the
 * run's own k was trained and timed: every other k is arithmetic from the counted parameters, drawn
 * hatched, and has no speed at all rather than an invented one.
 */
function costFigure(M) {
  const p = M.params;
  const cfg = M.config;
  const cont = M.continuation;
  const n = cfg.n_experts;
  const chunk = p.per_expert * cfg.depth; // one expert in every block

  const W = 480;
  const H = 312;
  const X0 = 116;
  const X1 = 466;
  const px = (v) => (v / p.total) * (X1 - X0);
  const ROW = { stored: 40, used: 118, dense: 178 };
  const BAR = 30;

  let k = cfg.top_k;

  const wrap = el('div', 'budget');
  wrap.setAttribute('role', 'group');
  wrap.setAttribute('aria-label', 'Parameters stored, parameters a token uses, and speed');

  const node = svg('svg', {
    viewBox: `0 0 ${W} ${H}`,
    class: 'chart budfig',
    role: 'img',
    'aria-label':
      'Parameters the converted model stores, the parameters one token uses at the chosen number ' +
      'of experts, the dense model for comparison, and tokens a second where they were measured.',
  });
  const defs = svg('defs');
  const pat = svg('pattern', { id: 'bud-hatch', width: 6, height: 6, patternUnits: 'userSpaceOnUse', patternTransform: 'rotate(45)' });
  pat.append(svg('rect', { width: 6, height: 6, class: 'hatch-bg' }), svg('line', { x1: 0, y1: 0, x2: 0, y2: 6, class: 'hatch-line' }));
  defs.append(pat);
  node.append(defs);

  const label = (y, text) => svgText(X0 - 10, y + BAR / 2 + 4, 'bud-k end', text);
  node.append(label(ROW.stored, 'stored'), label(ROW.used, 'one token uses'), label(ROW.dense, 'the dense model'));

  /* Stored: shared, then every expert-slot across all blocks. Dividers make the slots countable. */
  const segs = (y, experts, cls) => {
    const g = svg('g');
    g.append(svg('rect', { x: X0, y, width: px(p.shared), height: BAR, class: 'seg shared' }));
    let x = X0 + px(p.shared) + px(p.router_per_layer * cfg.depth);
    for (let e = 0; e < experts; e += 1) {
      g.append(svg('rect', { x, y, width: px(chunk), height: BAR, class: `seg ${cls}` }));
      x += px(chunk);
    }
    return g;
  };
  node.append(segs(ROW.stored, n, 'expert'));
  node.append(svgText(X1, ROW.stored - 6, 'bud-v end', int(p.total)));
  const used = svg('g');
  node.append(used);
  const usedVal = svgText(X0, ROW.used + BAR / 2 + 4, 'bud-v', '');
  node.append(usedVal);
  const denseG = svg('g');
  denseG.append(
    svg('rect', { x: X0, y: ROW.dense, width: px(p.shared), height: BAR, class: 'seg shared' }),
    svg('rect', { x: X0 + px(p.shared), y: ROW.dense, width: px(chunk), height: BAR, class: 'seg dense' })
  );
  node.append(denseG, svgText(X0 + px(p.dense) + 8, ROW.dense + BAR / 2 + 4, 'bud-v', int(p.dense)));
  node.append(
    svgText(X0, ROW.stored + BAR + 14, 'ax', 'shared: attention, embeddings, norms'),
    svgText(X0, ROW.stored + BAR + 28, 'ax', `then one slot per expert, each across all ${cfg.depth} blocks`)
  );

  /* Speed, only where it was measured. */
  const SP = { y: 248, h: 14 };
  const fastest = Math.max(cont.tokens_per_second.dense, cont.tokens_per_second.moe);
  const sx = (v) => (v / fastest) * (X1 - X0) * 0.7;
  node.append(svgText(X0 - 10, SP.y - 2, 'bud-k end', 'tokens a second'));
  node.append(
    svg('rect', { x: X0, y: SP.y - SP.h, width: sx(cont.tokens_per_second.dense), height: SP.h, class: 'seg dense' }),
    svgText(X0 + sx(cont.tokens_per_second.dense) + 6, SP.y - 3, 'bud-v', `dense ${int(cont.tokens_per_second.dense)}`)
  );
  const speed = svg('g');
  node.append(speed);

  const ctl = el('div', 'acc-ctl');
  const slider = el('input');
  slider.type = 'range';
  slider.min = '1';
  slider.max = String(n);
  slider.step = '1';
  slider.value = String(k);
  slider.id = 'bud-k';
  slider.setAttribute('aria-label', 'Experts each token goes to');
  const kOut = el('output', 'acc-where');
  kOut.htmlFor = 'bud-k';
  ctl.append(slider, kOut);
  slider.addEventListener('input', () => show(Number(slider.value)));
  const read = el('p', 'dx-read');

  const guard = (kk) => (kk >= 1 && kk <= n ? null : { note: `k runs from one to ${n}.` });
  const stateFor = (kk) => ({ ...p.active_by_k[kk - 1] });

  function show(kk) {
    k = kk;
    slider.value = String(kk);
    const refused = guard(kk);
    if (refused) {
      read.textContent = refused.note;
      return;
    }
    const st = stateFor(kk);
    used.replaceChildren(segs(ROW.used, kk, st.run ? 'expert' : 'expert hatched'));
    usedVal.textContent = `${int(st.active)}${st.run ? '' : ' · arithmetic'}`;
    /* Beside the bar's end while there is room, above it once the bar fills the row. */
    const end = X0 + px(st.active) + 8;
    /* Estimated from the character count (11px mono is about 0.6em a glyph), because the first
     * call runs before the figure is in the document, where a measured text length is zero. */
    const fits = end + usedVal.textContent.length * 6.8 <= W - 4;
    usedVal.setAttribute('x', fits ? end : X1);
    usedVal.setAttribute('y', fits ? ROW.used + BAR / 2 + 4 : ROW.used - 6);
    usedVal.setAttribute('class', fits ? 'bud-v' : 'bud-v end');
    kOut.textContent = `k = ${kk}${st.run ? ' — the run’s own setting' : ''}`;
    speed.replaceChildren();
    const y2 = SP.y + 22;
    if (st.run) {
      speed.append(
        svg('rect', { x: X0, y: y2 - SP.h, width: sx(cont.tokens_per_second.moe), height: SP.h, class: 'seg expert' }),
        svgText(X0 + sx(cont.tokens_per_second.moe) + 6, y2 - 3, 'bud-v', `converted ${int(cont.tokens_per_second.moe)}`)
      );
    } else {
      speed.append(
        svg('line', { x1: X0, x2: X0 + 60, y1: y2 - 2, y2: y2 - SP.h, class: 'slash' }),
        svgText(X0 + 70, y2 - 3, 'ax', `converted: not run with k = ${kk}, so no speed`)
      );
    }
    wrap.dataset.k = String(kk);
    read.innerHTML = st.run
      ? `<b>At the run's own k, each token uses ${int(st.active)} of the ${int(p.total)} parameters
         stored</b> — ${pct(st.share, 0)} of them, and ${st.over_dense.toFixed(2)}× the dense model's
         ${int(p.dense)}. It ran at ${int(cont.tokens_per_second.moe)} tokens a second against the
         dense model's ${int(cont.tokens_per_second.dense)}.`
      : `At k = ${kk} each token would use ${int(st.active)} parameters — ${pct(st.share, 0)} of what
         is stored, ${st.over_dense.toFixed(2)}× the dense model. <b>That is arithmetic from the
         counted parameters, not a run</b>: drawn hatched, and with no speed, because none was
         measured.`;
  }

  wrap.playAll = () => show(cfg.top_k);
  wrap.append(scroller(node), ctl, read);
  show(k);
  const ratio = cont.slowdown > 1 ? `${cont.slowdown.toFixed(1)}× slower` : `${(1 / cont.slowdown).toFixed(1)}× faster`;
  const fig = figure(
    playable(wrap),
    `<b>What the model stores and what a token pays are different numbers, and the gap is the point
     of experts.</b> The stored bar is fixed at ${int(p.total)}; a token's share grows by one expert-slot
     per step of k and reaches all of it at k = ${n}, where every token pays for everything. At k = 1
     a token costs the dense model plus the routers. Only the run's k = ${cfg.top_k} was trained and
     timed; the rest is drawn hatched. The converted model ran ${ratio} while each token used
     ${p.active_over_dense.toFixed(2)}× the dense model's parameters — but that count includes
     embeddings and is not a measure of compute, and what makes up the speed gap was not measured.
     One known cost is this reference implementation running its experts one after another in a
     Python loop.`
  );
  fig.id = 'fig-cost';
  return fig;
}

function chapterResults(M, W) {
  const b = M.balance;
  const cont = M.continuation;
  const rt = M.router_trial;
  const cv = M.curves;
  const s = section(
    'results',
    'results',
    'What happened',
    W.resultsTitle,
    [
      `Every figure below is read from the run's results file and its training log, and a test
       regenerates the page's data and fails if the tracked copy differs. First the router: does it
       use all its experts, or settle on a favourite few?`,
    ],
    { short: 'What happened', sub: 'balance, loss, and cost' }
  );

  s.append(balanceFigure(M, W));

  /* Each clause is present only when its step exists: a run with no idle step must not print
   * "the last of them step 0". */
  const clauses = [];
  clauses.push(
    b.worst_dead === 0
      ? '<b>The answer to the guess is zero</b>: no expert was ever idle.'
      : `<b>The answer to the guess is ${spell(b.worst_dead)}</b>, after step${b.worst_dead_steps.length > 1 ? 's' : ''}
         ${steps(b.worst_dead_steps)}, out of ${int(M.params.experts_stored)}. Steps with any idle
         expert numbered ${int(b.steps_with_idle)}, the last of them step ${int(b.last_idle)}.`
  );
  if (b.last_at_ceiling !== null) {
    clauses.push(`Early on the router is far from even — at ${int(b.steps_at_ceiling)} steps some
      block's busiest expert was chosen by every one of its tokens, the last time at step
      ${int(b.last_at_ceiling)}.`);
  }
  if (b.last_twice_share !== null) {
    clauses.push(`The busiest expert anywhere last reached twice its share at step
      ${int(b.last_twice_share)}.`);
  }
  clauses.push(`By the end the largest imbalance is ${b.end_violation.toFixed(3)}. In the first block,
    the one the log records, the smallest load at any logged step was ${M.layer0_min_load}${
      M.layer0_min_load > 0 ? ', so no expert there was ever idle at a logged step' : ''
    }.`);
  const bal = el('p', 'say');
  bal.innerHTML = clauses.join(' ');
  s.append(bal);

  s.append(validationFigure(M));

  const val = el('p', 'say');
  val.innerHTML = `<b>The converted model ends ${signed(cont.end_gap)} against the dense control</b>,
    at ${cont.moe_end.toFixed(4)} to ${cont.dense_end.toFixed(4)}${
      cont.most_behind_step === null
        ? ', and was never behind it at a validation check'
        : `, having trailed by as much as ${cont.most_behind.toFixed(4)} at step ${int(cont.most_behind_step)}`
    }. On the training batches the last ${M.config.log_every}-step mean of the difference is
    ${signed(cv.paired_end)}.${
      cont.most_behind_step === null
        ? ''
        : ' Whether the lopsided routing early on is why it trails in the middle, one run cannot say.'
    }`;
  s.append(val);

  s.append(
    table(
      ['router scoring', `validation loss after ${int(rt.tokens)} tokens`],
      Object.entries(rt.final_val).map(([name, v]) => ({
        cells: [name === rt.choice ? `<b>${name}</b> — kept` : name, v.toFixed(4)],
        __mark: name === rt.choice ? 'good' : undefined,
      }))
    )
  );
  const router = el('p', 'say small');
  router.innerHTML = `The router was chosen on a short trial before the main run, by
    ${rt.margin.toFixed(4)}, measured on the half of the validation text kept for choosing. One run
    each and no second seed, so this decides which router this run uses, not which is better.`;
  s.append(router);

  s.append(costFigure(M));
}

/* ============================================================== 8 · negatives */

/** Results weaker than they look, as data, so the section can count them. Findings come first. */
function findingRows(M, W) {
  const rt = M.router_trial;
  const cont = M.continuation;
  const rows = [
    {
      cells: [
        W.routerRow,
        'By how much?',
        `${rt.margin.toFixed(4)} in validation loss, on one short run of ${int(rt.tokens)} tokens each.
         It is a choice of which router to use, not a ranking of the two.`,
      ],
      __mark: 'warn',
    },
  ];
  if (cont.behind_steps.length) {
    rows.push({
      cells: [
        'The converted model behind the dense control mid-run',
        cont.end_position === 'ahead' ? 'Is the final lead safe?' : 'Did it ever recover?',
        `It trailed at ${spell(cont.behind_steps.length)} validation checks, by up to
         ${cont.most_behind.toFixed(4)}${cont.ahead_from === null ? '' : `, and led from step ${int(cont.ahead_from)}`}.
         With one run each and no spread between seeds, the final ${signed(cont.end_gap)} is these
         two runs, not the design.`,
      ],
      __mark: 'warn',
    });
  }
  return rows;
}

/** The mistakes in this exercise's own work, fixed before the run on this page. */
const FIXES = [
  `<b>The router was chosen on the validation text the results are reported on.</b> That could only
   flatter the converted model, the one model the choice applies to. Choosing and reporting now use
   separate halves of the validation text.`,
  `<b>The first run on the GPU crashed.</b> The balancing bias and load counters were created on the
   CPU while the experts moved to the GPU, so routing added a CPU number to GPU scores. It was found
   on the device, not by the tests; a test now holds them to the experts' device, and was watched
   failing against the old code.`,
  `<b>The results text announced "the conversion changes nothing" as fixed wording</b>, so it would
   have said so if the conversion broke. Its verdicts are computed now, and a test renders them both
   ways — as this page's are.`,
];

function chapterNegatives(M, W) {
  const rows = findingRows(M, W);
  const s = section(
    'negatives',
    'negatives',
    'What went wrong, and what did not hold',
    'What did not hold, and what had to be fixed',
    [
      `${Spell(rows.length)} ${rows.length === 1 ? 'result is' : 'results are'} weaker than
       ${rows.length === 1 ? 'it looks' : 'they look'}, and come first. Below them are the
       ${spell(FIXES.length)} mistakes in this exercise's own work that were found and fixed before
       the run on this page.`,
    ],
    { short: 'What went wrong', sub: 'weak results, then fixed mistakes' }
  );

  s.append(table(['the result', 'the question asked of it', 'what it supports'], rows, 'grid prose'));

  const lead = el('p', 'say');
  lead.innerHTML = '<b>Fixed before this run.</b>';
  const ul = el('ul', 'limitlist');
  for (const item of FIXES) {
    const li = el('li');
    li.innerHTML = item;
    ul.append(li);
  }
  s.append(lead, ul);
}

/* ============================================================== 9 · conclusion */

function chapterConclusion(M, W) {
  const s = section(
    'conclusion',
    'conclusion',
    'The verdict',
    W.conclusionTitle,
    W.conclusion,
    { short: 'The verdict', sub: 'what the run establishes' }
  );

  const box = el('div', 'takeaway');
  box.innerHTML = `<b>The part that transfers.</b> Before comparing a converted model with anything,
    check that it starts where the original stopped — the loss before and after, to the last digit.
    Then give the original the same further training, or more parameters will look like a better
    design when they are only more training.`;
  s.append(box);
}

/* ============================================================== 10 · limits */

function chapterLimits(M) {
  const cont = M.continuation;
  const cfg = M.config;
  const items = [
    `<b>One seed, one run each.</b> The gap between the converted model and the control has no spread
     beside it, so its size cannot be ranked against noise.`,
    `<b>${int(cont.tokens)} tokens is a short continuation.</b> The experts start identical and can
     only grow apart as routing sends them different tokens; a longer run could move the comparison
     either way.`,
    `<b>Nothing here measures how far the experts' model weights grew apart</b> — only which experts
     the router chose.`,
    `<b>The router trial is a choice, not a study</b> — one short run per scoring rule.`,
    `<b>The speed is a reference implementation's.</b> Experts run one after another in a Python loop,
     so the ${int(cont.tokens_per_second.moe)} tokens a second says nothing about an optimised kernel.`,
    `<b>The text is the corpus the dense model already trained on</b>, drawn as new random windows.
     The continued model has read ${M.corpus.longest_run_epochs.toFixed(2)} epochs of it in total, so
     some windows overlap text it has seen; both models are affected alike.`,
    `<b>The per-expert loads are the first block's only</b>, every ${cfg.log_every} steps, because that
     is all the training log records. The imbalance and idle counts cover every block at every step.`,
  ];
  const s = section(
    'limits',
    'limits',
    'In the open',
    'What this page cannot tell you',
    [
      `In the open text rather than behind a disclosure, because a limitation a reader has to expand
       is a limitation the page is hiding.`,
    ],
    { short: 'The limits', sub: 'what one run cannot settle' }
  );
  s.classList.add('notice');

  const ul = el('ul', 'limitlist');
  for (const item of items) {
    const li = el('li');
    li.innerHTML = item;
    ul.append(li);
  }
  s.append(ul);
}

/* ============================================================== 11 · next */

function chapterNext(M, W) {
  const cfg = M.config;
  const s = section(
    'next',
    'next',
    'What this opens',
    'What would turn one run into a finding',
    [`Each of these is a run this exercise did not do, and each would change how far the result reaches.`],
    { short: 'What this opens', sub: 'the runs that would settle it' }
  );

  const ul = el('ul', 'limitlist');
  for (const item of [
    `<b>More seeds for both models.</b> The spread between seeds is the noise floor the final gap has
     to clear, and it is the one number this page most needs and does not have.`,
    `<b>A longer continuation.</b> ${W.longer} is exactly what a short run cannot see.`,
    `<b>A sweep over the expert count.</b> ${cfg.n_experts} experts with ${cfg.top_k} per token is one
     setting; how the gain and the cost move with it is untested here.`,
    `<b>Experts computed together instead of in a loop.</b> Only then does a speed figure say anything
     about the design rather than about this implementation.`,
  ]) {
    const li = el('li');
    li.innerHTML = item;
    ul.append(li);
  }
  s.append(ul);
}

/* ============================================================== 12 · reproduce */

function chapterReproduce(M) {
  const prov = M.provenance;
  const env = prov.environment;
  const rows = [
    ['which settings', `<code>${prov.config_fingerprint}</code>`, 'every field of the configuration, hashed'],
    [
      'which code',
      `<code>${prov.code_digest.slice(0, 19)}…</code>`,
      'this exercise and the one whose model and data reader it uses',
    ],
    ['which commit', `<code>${prov.git_sha.slice(0, 12)}</code>`, 'the tree it ran from'],
    [
      'which text',
      `<code>${prov.corpus_digest.slice(0, 19)}…</code>`,
      `${M.corpus.dataset} · ${int(M.corpus.train_tokens)} training tokens`,
    ],
    ['which vocabulary', `<code>${prov.tokenizer_digest.slice(0, 19)}…</code>`, 'the frozen tokenizer every count is in'],
    [
      'which dense model',
      `<code>${prov.dense_checkpoint_digest.slice(0, 19)}…</code>`,
      `${M.dense_origin.source}, and the digests of its published results`,
    ],
    [
      'which machine',
      `${env.platform.split('-').slice(0, 2).join(' ')} · ${env.device}`,
      `python ${env.python} · torch ${env.torch}`,
    ],
  ];

  const s = section(
    'reproduce',
    'reproduce',
    'Every figure and its parent',
    `${Spell(rows.length)} things recorded so that any of this can be checked`,
    [
      `A number nobody can regenerate is not evidence. Every figure on this page is read from one
       tracked results file and one tracked training log, and the results file carries the block
       below; writing it without its provenance <b>raises</b> rather than warns.`,
      `<b>The dense model is an input like any other.</b> Its digest is recorded, so this run is tied to
       the exact model weights it converted, and a different starting model would show up as a different
       number here.`,
    ],
    { short: 'The index', sub: 'what produced every number here' }
  );

  s.append(
    table(
      ['question', 'answer', 'what it covers'],
      rows.map((r) => ({ cells: [r[0], r[1], r[2]] })),
      'grid'
    )
  );

  const p = el('p', 'say small');
  p.innerHTML = `Digests are shown truncated to fit; the file carries them at full length, which is
    the point — a prefix cannot be checked. The commands that regenerate all of this are in the
    exercise's own README, beside the code they run.
    <a href="https://github.com/pankajkr23/llm-pretraining-exercises/tree/main/src/exercises/14-moe">Code,
    tests and the full write-up</a>.`;
  s.append(p);
}

/* ============================================================== rail + footer */

function buildRail(root) {
  const rail = document.getElementById('rail');
  if (!rail) return;
  rail.replaceChildren();
  const inner = el('div', 'rail-inner');
  const head = el('div', 'rail-head');
  head.append(el('div', 'rail-title', 'On this page'));
  inner.append(head);
  const list = el('div', 'rail-list');
  const links = new Map();
  for (const sec of root.querySelectorAll('section')) {
    if (!sec.dataset.title) continue;
    const link = el('a', 'rail-link');
    link.href = `#${sec.id}`;
    const body = el('span', 'rail-body');
    body.append(el('span', 'rail-t', sec.dataset.title));
    if (sec.dataset.sub) body.append(el('span', 'rail-sub', sec.dataset.sub));
    link.append(el('span', 'rail-n', sec.dataset.n), body);
    list.append(link);
    links.set(sec.id, link);
  }
  inner.append(list);
  rail.append(inner);
  markPosition(root, links);
}

/* Registered from the code that has already appended the sections: an IntersectionObserver on a
 * detached node never fires and reports nothing, which is how three of exercise 08's plates
 * shipped without ever animating. */
function markPosition(root, links) {
  const sections = [...root.querySelectorAll('section')].filter((s) => links.has(s.id));
  if (!sections.length || typeof IntersectionObserver !== 'function') return;

  const visible = new Set();
  const observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) visible.add(entry.target.id);
        else visible.delete(entry.target.id);
      }
      const current = sections.find((s) => visible.has(s.id));
      for (const [id, link] of links) {
        link.classList.toggle('on', Boolean(current) && id === current.id);
      }
    },
    { rootMargin: '-10% 0px -70% 0px', threshold: 0 }
  );
  for (const s of sections) observer.observe(s);
}

function buildFooter() {
  const f = document.getElementById('foot');
  if (!f) return;
  const p = el('p', 'say small');
  p.innerHTML =
    'Written for whoever arrives first: the argument is in plain words, and every number behind it ' +
    'is regenerated by the commands in the repository, beside the code they run. ' +
    '<a href="https://github.com/pankajkr23/llm-pretraining-exercises/tree/main/src/exercises/14-moe">Code, tests and the full write-up</a>.';
  f.append(p);
}

export function buildPage(M) {
  const W = wording(M);
  chapterThesis(M, W);
  chapterGlossary(M);
  chapterProblem(M);
  chapterMechanism(M);
  chapterMethod(M);
  chapterExpected(M, W);
  chapterResults(M, W);
  chapterNegatives(M, W);
  chapterConclusion(M, W);
  chapterLimits(M);
  chapterNext(M, W);
  chapterReproduce(M);
  buildRail(main());
  buildFooter();

  /* Print and reduced motion get every figure's end state, painted. */
  const playAll = () => PLAY.forEach((w) => w.playAll());
  if (reduced()) playAll();
  window.addEventListener('beforeprint', playAll);
}
