"""Refuse a commit that changes too much at once, unless someone says why in the message.

**The goal is not small commits. It is commits you can reason about one at a time** — read the
diff, understand the one decision it encodes, and revert it on its own if it turns out wrong. Size
is a proxy for that, and like every proxy it can be optimised against: one wide commit touching a
single concern is easier to review than four narrow ones that only work together.

So this refuses a wide commit **by default** and lets one through when the message records the
reason. The point is to make breadth a decision somebody made rather than something that happened.

**Why an escape hatch rather than a hard cap.** A hard cap fights the thing it is meant to protect.
Landing a `PreToolUse` hook means shipping the hook, the module it imports and the test together:
split across three commits, the first two do not import, so `git bisect` lands on a tree that fails
for a reason unrelated to what is being bisected. That is exactly the property atomic commits exist
to give you. The rule this repo already follows is the reconciliation — **small batch is the means,
independent revertibility is the end** — so breadth is allowed and has to be argued for.

Run by pre-commit at the `commit-msg` stage, which is the only stage that sees both the staged diff
and the message.

    Wide-change: the hook, the ledger it imports and its guard cannot land separately

`CHANGELOG.md` is not counted. Every user-facing change is required to update it in the same change,
so charging for it would spend the budget on a file the conventions already mandate.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

#: How many files one commit may touch before it has to explain itself.
#:
#: Twenty, raised from ten, itself raised from an initial three. It is a prompt to ask "is this one
#: decision or several?", not a measurement of anything — and the trailer exists because the honest
#: answer is sometimes "one decision, seventeen files".
#:
#: **Raised because it was reaching for the trailer on work that genuinely was one decision.**
#: Removing a dead module vendored six times is one decision applied six times; so is deleting two
#: more from the four exercises that never imported them. That commit came to 17 files and 2,739
#: lines and every way of splitting it left either a red tree or an unguarded one, because the
#: guard added alongside fails on any vendored file a page does not reference. A limit that turns
#: the escape hatch into the normal path has stopped asking a question and started charging a toll.
#:
#: **Raised again to 30, this time because the limit was shaping the pull requests rather than the
#: commits.** A run that merged twenty-seven changes ended by opening four pull requests for four
#: guards, three of them carrying a single real file and three files of bookkeeping apiece. The
#: reviewer's question — *"why is this not one pull request?"* — was the right one: they were one
#: story, and a 20-file ceiling read as a target rather than a bound.
#:
#: A story-sized change here runs to roughly thirty files: eight vendored copies renamed and eleven
#: pages relinked is one decision applied nineteen times, not nineteen decisions.
#:
#: Lower it again when the work turns incremental. A limit nobody ever reaches is not doing
#: anything — and one everybody bypasses is doing less.
MAX_FILES = 30

#: How many added-plus-removed lines before the same question is asked. Five thousand, from 500:
#: a deletion of dead code is mostly lines and hardly any decision, and the old figure counted the
#: 2,578 removed lines as though each were a judgement someone should defend.
MAX_LINES = 5000

#: Files that do not count toward either limit, with the reason each is exempt.
#:
#: Nothing generated and nothing mandatory should consume a budget meant for *decisions*. A commit
#: is not harder to review because the changelog entry it is required to carry sits beside it.
NOT_COUNTED: dict[str, str] = {
    "CHANGELOG.md": "every user-facing change must update it in the same change, so charging for "
    "it would spend the budget on a file the conventions already mandate",
    "uv.lock": "generated by uv from pyproject.toml, never hand-edited, and routinely enormous",
}

#: The trailer that records why a commit is wide. The reason has to carry weight, because a trailer
#: reading `Wide-change: needed` is the same as no trailer at all.
_TRAILER = re.compile(r"^Wide-change:\s*(?P<reason>.+)$", re.MULTILINE)
MIN_REASON_WORDS = 6


def staged_changes() -> tuple[list[str], int]:
    """Every staged file that counts, and the added-plus-removed line total.

    Returns:
        `(paths, lines)` — paths relative to the repo root, `NOT_COUNTED` entries removed.
    """
    done = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "diff", "--cached", "--numstat"],
        capture_output=True,
        text=True,
        check=False,
    )
    paths: list[str] = []
    lines = 0
    for row in done.stdout.splitlines():
        parts = row.split("\t")
        if len(parts) != 3:
            continue
        added, removed, path = parts
        if path in NOT_COUNTED:
            continue
        paths.append(path)
        # `-` is git's marker for a binary file, which has no line count to add.
        lines += sum(int(n) for n in (added, removed) if n.isdigit())
    return paths, lines


def stated_reason(message: str) -> str | None:
    """The `Wide-change:` reason, if the message carries one with enough words in it."""
    found = _TRAILER.search(message)
    if not found:
        return None
    reason = found.group("reason").strip()
    return reason if len(reason.split()) >= MIN_REASON_WORDS else None


def verdict(paths: list[str], lines: int, message: str) -> str | None:
    """The refusal for this commit, or None to let it through.

    Args:
        paths: Staged paths that count.
        lines: Added plus removed lines across them.
        message: The full commit message.

    Returns:
        A message to refuse with, or None.
    """
    over_files = len(paths) > MAX_FILES
    over_lines = lines > MAX_LINES
    if not (over_files or over_lines):
        return None
    if stated_reason(message) is not None:
        return None

    breach = []
    if over_files:
        breach.append(f"{len(paths)} files (limit {MAX_FILES})")
    if over_lines:
        breach.append(f"{lines} changed lines (limit {MAX_LINES})")
    listing = "\n  ".join(sorted(paths))
    return (
        f"This commit changes {' and '.join(breach)}.\n\n"
        f"  {listing}\n\n"
        "Split it, so each commit carries one decision and can be reverted on its own.\n"
        "If it genuinely cannot be split — a hook and the module it imports do not work\n"
        "apart, and separating them would make `git bisect` land on a broken tree — say so\n"
        "in the message and it will be allowed:\n\n"
        f"    Wide-change: <why this cannot be split, at least {MIN_REASON_WORDS} words>\n\n"
        f"Not counted toward the limits: {', '.join(sorted(NOT_COUNTED))}."
    )


def main() -> int:
    """Read the message file pre-commit passes, and refuse or allow. Returns an exit code."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("message_file", help="the file pre-commit's commit-msg stage passes in")
    args = parser.parse_args()

    message = Path(args.message_file).read_text(encoding="utf-8")
    # A merge or a revert is assembled by git, not written by anyone, and its breadth is a property
    # of the branches rather than a decision someone is making now.
    if message.startswith(("Merge ", "Revert ")):
        return 0

    refusal = verdict(*staged_changes(), message)
    if refusal is None:
        return 0
    print(refusal, file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
