/* The page, built from the four result bundles in data.js.
 *
 * Three rules this file follows:
 *
 *   1. No measured number is written here. Every figure comes from `M`, generated by
 *      tools/render_results.py from results/*.json with the same functions RESULTS.md is rendered
 *      with — so a ratio, a gap or a speed verdict cannot differ between the two documents.
 *   2. A mechanism figure is not a results chart. The central object is the backward pass walking
 *      down a stack it no longer holds, so the page draws that walk; the results figures come after.
 *   3. A failure goes in the opening tiles. The rule the method treats as its main one was refused
 *      by this exercise's own gate, and that tile is red.
 *
 * The update rules are written as coefficients — A on the state two layers back, B on the current
 * one, C on the block's update — which is how `reversible/stack.py` implements all of them as one
 * shape. Those symbols are definitions, not measurements, so they are the only digits typed here.
 *
 * Sections carry `data-role`, so the spine is checkable without pinning any wording.
 */

const NS = 'http://www.w3.org/2000/svg';
const main = () => document.getElementById('main');

function el(tag, cls, text) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
}

function svg(tag, attrs = {}) {
  const n = document.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, String(v));
  /* **A figure is never drawn smaller than it was designed, because its labels shrink with it.**
   * A `viewBox` scales text along with the drawing, so a label authored at a compliant 11px paints
   * at `11 × rendered ÷ viewBox` — 5px on a phone, where the figure is a quarter of its design
   * width. Nothing in the source says so: every declared size on this page is inside
   * `docs/DESIGN.md`'s 9.5–11px band, and the whole reduction happens in the transform.
   *
   * A diagram cannot reflow the way a paragraph can, so the fix is to stop it shrinking: the floor
   * is the viewBox's own width, and the `figure` around it already scrolls. Set here rather than in
   * a stylesheet because the value is a property of each drawing, and a stylesheet would have to
   * repeat every viewBox — a second copy of a number, which is the copy that drifts. */
  if (tag === 'svg' && attrs.viewBox) {
    const designed = Number(String(attrs.viewBox).trim().split(/\s+/)[2]);
    if (Number.isFinite(designed) && designed > 0) n.style.minWidth = `${designed}px`;
  }
  return n;
}

function svgText(x, y, cls, text) {
  const t = svg('text', { x, y, class: cls });
  t.textContent = text;
  return t;
}

let sectionCount = 0;
let figureCount = 0;

/** A section whose eyebrow names its epistemic role, so a reader knows how to weigh it. */
function section(id, role, eyebrow, title, paras, rail) {
  const s = el('section');
  s.id = id;
  s.dataset.role = role;
  sectionCount += 1;
  s.dataset.n = String(sectionCount);
  s.dataset.title = (rail && rail.short) || title;
  if (rail && rail.sub) s.dataset.sub = rail.sub;
  s.append(el('p', 'role', eyebrow), el('h2', null, title));
  for (const p of [].concat(paras || [])) {
    const n = el('p', 'say');
    n.innerHTML = p;
    s.append(n);
  }
  main().append(s);
  return s;
}

/** A figure whose caption says what to conclude — never a bare label.
 *
 * **The number is counted, not passed.** A figure's number is a count of the figures before it,
 * which makes it exactly the kind of number this page derives everywhere else. Ported from
 * exercise 09, which shipped two figures both captioned "Figure 1" before it counted them.
 */
function figure(node, caption) {
  figureCount += 1;
  const f = el('figure');
  f.append(node);
  const c = el('figcaption');
  c.innerHTML = `<b>Figure ${figureCount}.</b> ${caption}`;
  f.append(c);
  return f;
}

function table(head, rows, cls) {
  const wrap = el('div', 'tablewrap');
  const t = el('table', cls || 'grid');
  const thead = el('thead');
  const hr = el('tr');
  for (const h of head) {
    const th = el('th');
    th.innerHTML = h;
    hr.append(th);
  }
  thead.append(hr);
  t.append(thead);
  const tb = el('tbody');
  for (const row of rows) {
    const tr = el('tr');
    if (row.__mark) tr.className = row.__mark;
    row.cells.forEach((cell, i) => {
      const td = el('td');
      td.innerHTML = cell === null || cell === undefined ? '—' : cell;
      /* The column head, carried on the cell, so a stacked row on a phone can still say which
       * column each line belongs to. Only when there IS one: a blank header would set
       * `data-head=""`, which still matches `td[data-head]` and paints an empty labelled line. */
      const label = head[i] === undefined ? '' : String(head[i]).replace(/<[^>]*>/g, '').trim();
      if (label) td.dataset.head = label;
      tr.append(td);
    });
    tb.append(tr);
  }
  t.append(tb);
  wrap.append(t);
  return wrap;
}

const int = (n) => Math.round(n).toLocaleString('en-US');
/* Counts are SPELLED from the data, never typed. A heading or a rail label that states a number
 * is stating a count of its own contents, so typing it is how a page comes to be headed "Two
 * commands" over three of them. Ported from exercise 08, which introduced it for the same reason. */
const SPELLED = [
  'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
  'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen',
  'nineteen', 'twenty',
];
const spell = (n) => SPELLED[n] || String(n);
const Spell = (n) => {
  const w = spell(n);
  return w[0].toUpperCase() + w.slice(1);
};

const signed = (n, d = 4) => (n >= 0 ? '+' : '−') + Math.abs(n).toFixed(d);
const pct = (n, d = 1) => `${(n * 100).toFixed(d)}%`;

/* How many decimals a measurement's own noise floor will support: quote a digit only when the
 * spread is smaller than that digit's place value. Ported from exercise 09. */
const decimalsFor = (spread) =>
  spread > 0 ? Math.min(4, Math.max(0, Math.floor(-Math.log10(spread)))) : 4;

/** A ratio quoted to the precision its own spread earns, never finer. */
const ratio = (value, spread) => `${value.toFixed(decimalsFor(spread))}×`;

/* The units this page reports memory in. Binary, as the bundles count them. */
const mib = (bytes) =>
  (bytes / 2 ** 20).toLocaleString('en-US', { minimumFractionDigits: 1, maximumFractionDigits: 1 });
const gib = (bytes) => (bytes / 2 ** 30).toFixed(1);

/* A small relative error, as a percentage with two significant figures — 0.0053% and 5.4% on one
 * scale, so a reader can set every candidate against the 1% gate without converting exponents. */
const pctSig = (x) => `${Number((x * 100).toPrecision(2))}%`;

/* State labels. `p⁽ℓ⁾` is the state entering block ℓ + 1; the superscript is built from the index
 * so a figure can label any depth the run used. */
const SUP = {
  '-': '⁻', '−': '⁻', '+': '⁺',
  0: '⁰', 1: '¹', 2: '²', 3: '³', 4: '⁴', 5: '⁵', 6: '⁶', 7: '⁷', 8: '⁸', 9: '⁹',
};
/* A character with no superscript form — the ℓ in p⁽ℓ⁺¹⁾ — is kept as it is, inside the raised
 * brackets, which is how the exercise's README writes it. Dropping it printed `p⁽⁺¹⁾`. */
const sup = (n) => [...String(n)].map((c) => SUP[c] ?? c).join('');
const p = (n) => `p⁽${sup(n)}⁾`;

/* The rules as the code holds them: three coefficients each. Definitions, not results. The
 * ordinary residual block is the same shape with A = 0, which is the whole reason it cannot be
 * undone — and why the blend at a = 0 is refused by `Rule.make`. */
const RULES = {
  ordinary: { A: '0', B: '1', C: '1' },
  midpoint: { A: '1', B: '0', C: '2h' },
  blend: { A: 'a', B: '1−a', C: 'h' },
  leapfrog: { A: '−1', B: '2', C: 'h²' },
};

/** The inverse of a rule, instantiated at block `k`: the state two below, from the two above. */
function undo(rule, k) {
  const top = p(k);
  const mid = p(k - 1);
  if (rule === 'midpoint') return `${p(k - 2)} = ${top} − 2h·f(${mid})`;
  if (rule === 'blend') return `${p(k - 2)} = (${top} − (1 − a)·${mid} − h·f(${mid})) / a`;
  return `${p(k - 2)} = 2·${mid} − ${top} + h²·f(${mid})`;
}

/* Every interactive figure registers its end state here. Print and reduced motion both paint it,
 * because a reader who cannot or will not move a control still gets the whole argument. */
const PLAY = [];

const chosenTrial = (M) =>
  M.trials.rules.find((r) => r.rule === M.trials.choice.rule && r.h === M.trials.choice.h);
const refused = (M) => M.trials.rules.filter((r) => !r.eligible);
const eligible = (M) => M.trials.rules.filter((r) => r.eligible && r.agreement);
const baselineTrial = (M) => M.trials.baseline.find((b) => b.lr === M.trials.best_lr);
const bestRefused = (M) =>
  refused(M).reduce((a, b) => (a === null || b.final_val < a.final_val ? b : a), null);

/* ============================================================== 1 · thesis */

function chapterThesis(M) {
  const F = M.fixed;
  const X = M.max_batch;
  const blend = bestRefused(M);
  const s = section(
    'thesis',
    'thesis',
    'Memory traded for compute',
    'Keep the top of the stack, rebuild the rest — and check the rebuild',
    [
      `The same ${int(F.baseline.parameters)}-parameter model, trained as an ordinary stack and as
       a reversible one on the same ${int(F.baseline.tokens)} tokens. <b>The green tiles are what
       the method promises, the amber one is what it cost in loss, and the red one is what this
       exercise refused to accept</b> — the reason the page exists in the form it does.`,
    ],
    { short: 'The claim', sub: 'what reversing a network buys and costs' }
  );

  const tiles = el('div', 'tiles');
  for (const [v, k, mark] of [
    [
      `${F.kept_ratio.toFixed(1)}×`,
      `fewer bytes kept for the backward pass at the same batch of ${F.batch} —
       ${mib(F.reversible.saved_bytes)} MiB against ${mib(F.baseline.saved_bytes)} MiB`,
      'good',
    ],
    [
      `${int(X.baseline.measured_max_batch)} → ${int(X.reversible.measured_max_batch)}`,
      `sequences in one training step under the same ${X.budget_gib} GiB cap, found by running real
       steps until one ran out of memory — ${X.batch_ratio.toFixed(1)}× as many`,
      'good',
    ],
    [
      signed(F.loss_gap, 3),
      `validation loss, reversible minus ordinary, after the full run at the same batch. One seed
       each, so this is reported and not ranked`,
      'watch',
    ],
    [
      pctSig(blend.agreement.gradient_error),
      `how far the <b>blend</b> rule's rebuilt gradients were from the true ones at h = ${blend.h},
       its best-scoring setting. Every blend setting was over the ${pct(M.trials.tolerance, 0)} gate
       and refused`,
      'bad',
    ],
  ]) {
    const tile = el('div', `tile ${mark}`);
    const value = el('div', 'tile-v');
    value.innerHTML = v;
    const key = el('div', 'tile-k');
    key.innerHTML = k;
    tile.append(value, key);
    tiles.append(tile);
  }
  s.append(tiles);

  const chosen = chosenTrial(M);
  const note = el('p', 'say small');
  note.innerHTML = `The red tile did not change which rule was used — ${chosen.rule} at h =
    ${chosen.h} scored ${chosen.final_val.toFixed(4)} against the best blend's
    ${blend.final_val.toFixed(4)} anyway. It is first because it is the check that would have
    caught a run training on gradients a few percent wrong while its loss curve looked perfectly
    normal.`;
  s.append(note);
}

/* ============================================================== 2 · glossary */

function chapterGlossary(M) {
  const P = M.preset;
  const F = M.fixed;
  const X = M.max_batch;
  const T = M.trials;
  /* Built BEFORE the section, so the heading can count them. */
  const entries = [
    [
      'forward and backward',
      `The <b>forward pass</b> runs text through the model's ${P.depth} blocks to a guess; the
       <b>backward pass</b> walks the same blocks in reverse to work out how each of the
       ${int(F.baseline.parameters)} weights should change. To do that it needs the input every
       block saw on the way forward.`,
    ],
    [
      'kept for backward',
      `Whatever the forward pass leaves in memory for the backward pass to read. The ordinary model
       here adds ${int(X.baseline.saved_bytes_per_sample)} bytes of it for every extra
       ${P.seq_len}-token sequence in a batch.`,
    ],
    [
      'the state',
      `The vector each position carries from block to block — ${P.width} numbers wide here. This
       page writes ${p('ℓ')} for the state after ℓ blocks.`,
    ],
    [
      'a reversible rule',
      `An update that can be run backwards: given the two states above, it returns the one below.
       This run tried ${spell(P.trial_rules.length)} — ${P.trial_rules.join(', ')} — each for
       ${int(T.tokens_per_trial)} tokens at every step size.`,
    ],
    [
      'step size h',
      `How far one block moves the state. Each rule was tried at h = ${P.trial_h.join(', ')}; the
       long runs use ${T.choice.rule} at h = ${T.choice.h}.`,
    ],
    [
      'gradient error',
      `How far rebuilding moved the gradients from the ones ordinary training computes, as a share
       of their size. The chosen rule's: ${pctSig(F.agreement.init.gradient_error)} before
       training, ${pctSig(F.agreement.trained.gradient_error)} after.`,
    ],
    [
      'the gate',
      `A candidate whose gradient error is above ${pct(T.tolerance, 0)} on its starting weights is
       still trained and shown, but can never be chosen. It refused
       ${spell(Object.keys(T.ineligible).length)} of the ${spell(T.rules.length)} candidates.`,
    ],
    [
      'the largest batch',
      `The most sequences one training step can take under a ${X.budget_gib} GiB memory cap, found
       on the GPU by running real steps until one fails: ${int(X.baseline.measured_max_batch)} for
       the ordinary model, ${int(X.reversible.measured_max_batch)} for the reversible one.`,
    ],
    [
      'validation loss',
      `How wrong the model's guesses are on text it never trained on — lower is better. Every
       reported value is measured on one half of the held-out text, the other half being used only
       to choose. The ordinary model ends at ${F.baseline.final_val.toFixed(4)}.`,
    ],
    [
      "the machine's spread",
      `The same model at ${spell(T.baseline.length)} learning rates ran
       ${M.throughput_floor.toFixed(2)}× apart in tokens per second on this machine. A speed gap
       smaller than that says nothing about the models.`,
    ],
  ];
  const s = section(
    'glossary',
    'glossary',
    'Before anything else',
    `${Spell(entries.length)} words you need, each carrying a number from this run`,
    [
      `Read this once and nothing below is jargon. Every entry carries a real figure from the runs
       on this page rather than a textbook gloss.`,
    ],
    { short: 'The words', sub: 'terms, each with our own figure' }
  );

  const dl = el('dl', 'gloss');
  for (const [term, def] of entries) {
    dl.append(el('dt', null, term));
    const dd = el('dd');
    dd.innerHTML = def;
    dl.append(dd);
  }
  s.append(dl);
}

/* ============================================================== 3 · the problem */

function chapterProblem(M) {
  const F = M.fixed;
  const X = M.max_batch;
  const s = section(
    'problem',
    'problem',
    'The problem',
    'An ordinary block cannot give its input back',
    [
      `To work out how a weight should change, the backward pass needs the exact input the block
       saw on the way forward. So an ordinary transformer keeps every block's working tensors until
       the backward pass comes back for them — <b>and that pile grows with the depth and with the
       batch.</b>`,
      `Here, at a batch of ${F.batch}, it is ${mib(F.baseline.saved_bytes)} MiB. The weights, their
       gradients and the optimiser's running averages together take ${mib(X.baseline.state_bytes)}
       MiB. <b>It is the activations, not the model, that run out of room</b> — each further
       sequence in the batch adds another ${mib(X.baseline.saved_bytes_per_sample)} MiB.`,
      `Why not recompute the input instead of keeping it? An ordinary block adds its update to the
       state it was given: ${p('ℓ+1')} = ${p('ℓ')} + f(${p('ℓ')}). To get ${p('ℓ')} back from
       ${p('ℓ+1')} you would need f(${p('ℓ')}) — which needs the very state you are trying to
       recover. There is no way round it, so the input is stored.`,
    ],
    { short: 'The problem', sub: 'activations, not weights, fill memory' }
  );
  return s;
}

/* ============================================================== 4 · mechanism */

/* Figure 1 — the backward pass, walked block by block. Inspector: the reader moves the position
 * and every slot answers the same questions for the block they are on. */
function walkFigure(M) {
  /* 1. CONSTANTS — from the run. */
  const L = M.preset.depth;
  const rule = M.trials.choice.rule;
  const X = M.max_batch;
  const rows = [];
  for (let n = L; n >= -1; n -= 1) rows.push(n);

  /* 2. PURE HELPERS. */
  const W = 248;
  const rowH = 24;
  const top = 30;
  const H = top + rows.length * rowH + 12;
  const y = (n) => top + rows.indexOf(n) * rowH;

  /* 3. STATE — the minimum that cannot be derived. j = how many blocks the backward pass has
   * undone: 0 is the moment the forward pass ends, L is the bottom of the stack. */
  let current = 0;

  const wrap = el('div', 'walk');
  wrap.setAttribute('role', 'group');
  wrap.setAttribute('aria-label', 'The backward pass of a reversible stack, block by block');

  const ctl = el('div', 'walk-ctl');
  const label = el('label', null, 'Where the backward pass is');
  label.htmlFor = 'walk-pos';
  const range = el('input');
  range.type = 'range';
  range.id = 'walk-pos';
  range.min = '0';
  range.max = String(L);
  range.step = '1';
  range.value = '0';
  const out = el('output', 'walk-out');
  out.htmlFor = 'walk-pos';
  ctl.append(label, range, out);

  const body = el('div', 'walk-body');
  const stack = svg('svg', {
    viewBox: `0 0 ${W} ${H}`,
    class: 'walkfig',
    role: 'img',
    'aria-label':
      'The stack of states from the top down. The two held in memory are filled; the rest are ' +
      'outlines until the backward pass rebuilds them',
  });
  const BX = 38;
  const BW = 96;
  stack.append(
    svgText(BX + BW / 2, 18, 'w-head mid', 'state'),
    svgText(W - 8, 18, 'w-head end', 'in memory?')
  );
  const marks = new Map();
  for (const n of rows) {
    const g = svg('g', { class: 'w-row' });
    const box = svg('rect', { x: BX, y: y(n), width: BW, height: rowH - 6, rx: 5, class: 'w-box' });
    const name = svgText(BX + BW / 2, y(n) + 13, 'w-name mid', n === -1 ? `${p(-1)} · seed` : p(n));
    const tag = svgText(W - 8, y(n) + 13, 'w-tag end', '');
    g.append(box, name, tag);
    stack.append(g);
    marks.set(n, { g, tag });
  }
  /* The re-run, drawn as a hook from the state the block runs on to the state it rebuilds. It sits
   * in the left margin, which nothing else uses, so it can never cross a label. */
  const arrow = svg('path', { class: 'w-arrow', d: '' });
  const arrowHead = svg('path', { class: 'w-arrow-head', d: '' });
  stack.append(arrow, arrowHead);

  const slots = el('dl', 'walk-slots');
  const slot = (k) => {
    const dt = el('dt', null, k);
    const dd = el('dd');
    slots.append(dt, dd);
    return dd;
  };
  const sHeld = slot('in memory');
  const sRerun = slot('re-runs');
  const sRebuild = slot('rebuilds');
  const sNote = slot('what to notice');

  /* The bytes this walk costs per sequence: the same at every position, which is the point. */
  const bytes = el('div', 'walk-bytes');
  const most = X.baseline.derived_bytes_per_sample;
  const bar = (who, value, parts) => {
    const row = el('div', 'wb-row');
    row.append(el('span', 'wb-who', who));
    const track = el('span', 'wb-track');
    for (const [cls, v] of parts) {
      const seg = el('span', `wb-seg ${cls}`);
      seg.style.width = `${(100 * v) / most}%`;
      track.append(seg);
    }
    row.append(track, el('span', 'wb-v', `${int(value)} bytes`));
    return row;
  };
  bytes.append(
    el('div', 'wb-title', 'held for the backward pass, per sequence, at any position'),
    bar('ordinary', X.baseline.derived_bytes_per_sample, [['base', X.baseline.derived_bytes_per_sample]]),
    bar('reversible', X.reversible.derived_bytes_per_sample, [
      ['kept', X.reversible.saved_bytes_per_sample],
      ['rerun', X.reversible.backward_working_bytes_per_sample],
    ])
  );

  body.append(stack, slots);
  wrap.append(ctl, body, bytes);

  /* guard() — the precondition. A position outside the stack has no honest answer. */
  const guard = (j) => (j < 0 || j > L || !Number.isInteger(j) ? { note: 'no such block' } : null);

  /* stateFor(j) — PURE. Position → which states are held, which block is re-run, what it rebuilds.
   * Block k (1…L) made p⁽ᵏ⁾ from p⁽ᵏ⁻²⁾ and p⁽ᵏ⁻¹⁾, so undoing it re-runs f on p⁽ᵏ⁻¹⁾ and
   * returns p⁽ᵏ⁻²⁾; afterwards p⁽ᵏ⁾ is no longer needed. */
  const stateFor = (j) => {
    if (j === 0) return { held: [L - 1, L], k: null, rebuilt: null, released: null };
    const k = L - j + 1;
    return { held: [k - 2, k - 1], k, rebuilt: k - 2, released: k };
  };

  const statusOf = (n, st, j) => {
    if (n === st.rebuilt) return ['rebuilt', 'rebuilt now'];
    if (st.held.includes(n)) return ['held', 'kept'];
    if (j > 0 && n > st.held[1]) return ['done', 'used, freed'];
    return ['gone', 'not in memory'];
  };

  /* show(j) — RENDER ONLY. */
  const show = (j) => {
    if (guard(j)) return;
    current = j;
    range.value = String(j);
    const st = stateFor(j);
    wrap.dataset.pos = String(j);
    for (const [n, { g, tag }] of marks) {
      const [cls, words] = statusOf(n, st, j);
      g.setAttribute('class', `w-row ${cls}`);
      tag.textContent = words;
    }
    sHeld.textContent = `${p(st.held[1])} and ${p(st.held[0])}`;
    if (st.k === null) {
      out.textContent = 'the forward pass has just ended';
      sRerun.textContent = 'nothing yet';
      sRebuild.textContent = 'nothing yet';
      sNote.textContent = `Only the top ${spell(st.held.length)} states survive the forward pass.
        Every state below them was thrown away as soon as the next one was computed.`;
      arrow.setAttribute('d', '');
      arrowHead.setAttribute('d', '');
      return;
    }
    out.textContent = `undoing block ${st.k} of ${L}`;
    sRerun.textContent = `block ${st.k}, on ${p(st.k - 1)}`;
    sRebuild.textContent = undo(rule, st.k);
    sNote.textContent =
      st.rebuilt === -1
        ? `The last rebuild returns the seed — the copy of ${p(0)} the stack started from, since a
           two-step rule needs two states to begin. Every state has been visited once, and no more
           than ${spell(st.held.length)} were ever held at a time.`
        : `${p(st.released)} has done its job and is freed. The memory held is the same as at the
           top of the stack: two states and the one block being re-run.`;
    const x0 = BX - 3;
    const yFrom = y(st.k - 1) + 9;
    const yTo = y(st.k - 2) + 9;
    arrow.setAttribute('d', `M ${x0} ${yFrom} C ${x0 - 30} ${yFrom}, ${x0 - 30} ${yTo}, ${x0 - 6} ${yTo}`);
    arrowHead.setAttribute('d', `M ${x0} ${yTo} l -7 -4 l 0 8 z`);
  };

  range.addEventListener('input', () => show(Number(range.value)));
  wrap.playAll = () => show(L);
  PLAY.push(wrap.playAll);
  show(current);

  return figure(
    wrap,
    `<b>Two states and one block, wherever the walk is.</b> Move the position down the stack: the
     filled pair slides with it, the state below is rebuilt from the two above and the block between
     them, and the state above is freed. The bars underneath do not move, which is the argument —
     the reversible model holds ${int(X.reversible.derived_bytes_per_sample)} bytes per sequence at
     every position, against ${int(X.baseline.derived_bytes_per_sample)} for the ordinary one. A
     position where a third state had to be kept would refute it.`
  );
}

/* Figure 2 — the rules as coefficients. Static: there is nothing to compare by moving. Drawn at a
 * phone's width, with each row's verdict on its own line under the boxes, so nothing that carries
 * the argument sits past the right edge of a small screen. */
function rulesFigure(M) {
  const a = M.preset.blend_a;
  const chosen = M.trials.choice.rule;
  const order = ['ordinary', ...M.preset.trial_rules];
  const W = 248;
  const rowH = 70;
  const top = 34;
  const H = top + order.length * rowH;
  const BOX = 42;
  const cols = [86, 132, 178];
  const node = svg('svg', {
    viewBox: `0 0 ${W} ${H}`,
    class: 'rulefig',
    role: 'img',
    'aria-label':
      'Each rule as three coefficients. The ordinary block has A equal to zero and cannot be undone; ' +
      'the blend divides by a at every layer; midpoint and leapfrog divide by one',
  });
  ['A', 'B', 'C'].forEach((head, k) => node.append(svgText(cols[k] + BOX / 2, 20, 'r-head mid', head)));

  order.forEach((name, i) => {
    const y0 = top + i * rowH;
    const coef = RULES[name];
    const isChosen = name === chosen;
    if (isChosen) {
      node.append(svg('rect', { x: 2, y: y0 - 6, width: W - 4, height: rowH - 4, rx: 9, class: 'r-chosen' }));
    }
    node.append(svgText(8, y0 + 20, `r-name${isChosen ? ' strong' : ''}`, name));
    const sub = isChosen ? 'chosen' : name === 'ordinary' ? 'the baseline' : '';
    if (sub) node.append(svgText(8, y0 + 35, 'r-sub', sub));
    cols.forEach((x, k) => {
      const value = [coef.A, coef.B, coef.C][k];
      const bad = name === 'ordinary' && k === 0;
      const watch = name === 'blend' && k === 0;
      node.append(
        svg('rect', {
          x,
          y: y0,
          width: BOX,
          height: 28,
          rx: 6,
          class: `r-box${bad ? ' bad' : ''}${watch ? ' watch' : ''}`,
        }),
        svgText(x + BOX / 2, y0 + 19, 'r-v mid', value)
      );
    });
    let verdict;
    let cls = 'r-out';
    /* Words, not a ÷ sign: at this size the sign read as a plus in every theme. */
    if (name === 'ordinary') {
      verdict = 'A = 0: cannot be undone';
      cls += ' bad';
    } else if (name === 'blend') {
      verdict = `divides by a = ${a}: ×${1 / a} a layer`;
      cls += ' watch';
    } else {
      verdict = `divides by ${coef.A}: nothing grows`;
    }
    node.append(svgText(8, y0 + 52, cls, verdict));
  });
  return figure(
    node,
    `<b>Every rule is p⁽ℓ⁺¹⁾ = A·p⁽ℓ⁻¹⁾ + B·p⁽ℓ⁾ + C·f(p⁽ℓ⁾), and undoing it divides by A</b> — the
     weight on the state two layers back; B weighs the current state and C the block's update. The
     ordinary block is the row with A = 0, which is why it has to store its inputs. Midpoint and
     leapfrog divide by one in size, so undoing them adds no amplification of its own. The blend
     divides by a = ${a} at every layer, so rounding error can grow roughly ${1 / a}× per layer on
     the way down — which predicts, before any training, that it is the rule whose rebuilt
     gradients will drift. The trials figure below is the measurement.`
  );
}

function chapterMechanism(M) {
  const s = section(
    'mechanism',
    'mechanism',
    'The trick, taken apart',
    'A rule that runs backwards needs only the top of the stack',
    [
      `A reversible rule moves the state forward using the <i>two</i> states before it rather than
       one. Each block adds its update to a mix of ${p('ℓ−1')} and ${p('ℓ')}, and evaluates its
       function f at the middle one: ${p('ℓ+1')} = A·${p('ℓ−1')} + B·${p('ℓ')} + C·f(${p('ℓ')}).`,
      `Solve that for ${p('ℓ−1')}: <b>every term on the right is something the backward pass
       already holds.</b> So the forward pass keeps only the two states at the top and discards the
       rest. The backward pass walks down, re-runs each block once on the state it has, rebuilds the
       state below, and backpropagates through what it just ran. The price is one extra forward
       pass per block; the pay-off is that memory for activations stops depending on the depth.`,
      `The rules come from Gal et al., <i>Reversing Large Language Models for Efficient Training
       and Fine-Tuning</i> (arXiv:2512.02056); this page writes them all in one coefficient form,
       the way the code implements them.`,
    ],
    { short: 'The mechanism', sub: 'the backward pass, walked down' }
  );
  s.append(walkFigure(M));
  s.append(rulesFigure(M));

  const note = el('p', 'say');
  note.innerHTML = `The seeding is our own choice, not part of the method: a two-step rule needs two
    starting states, and this stack starts from two copies of the embedding output, so the first
    block takes an ordinary step. And no block may contain randomness — re-running a block that drew
    a fresh dropout mask would rebuild the wrong state, silently.`;
  s.append(note);
}

/* ============================================================== 5 · method */

function chapterMethod(M) {
  const P = M.preset;
  const T = M.trials;
  const F = M.fixed;
  const X = M.max_batch;
  const R = M.max_run;
  const env = M.provenance.fixed_batch.environment;
  const s = section(
    'method',
    'method',
    'The apparatus',
    'One small model, one GPU, one memory cap',
    [
      `${Spell(Object.keys(M.provenance).length)} experiments, run in order, each recorded in its
       own result file. <b>The rule is chosen before
       either long run starts</b>, on short trials scored on one half of the held-out text; every
       loss this page reports is measured on the other half, so the choice cannot flatter the
       result it is later judged by.`,
    ],
    { short: 'The apparatus', sub: 'model, data, and the experiments' }
  );

  s.append(
    table(
      ['part', 'what it is'],
      [
        {
          cells: [
            'model',
            `a decoder ${P.width} wide and ${P.depth} blocks deep — ${int(F.baseline.parameters)}
             parameters, the same count in both variants`,
          ],
        },
        {
          cells: [
            'text',
            `${M.corpus.dataset}, ${int(M.corpus.train_tokens)} training tokens; each long run reads
             ${int(F.baseline.tokens)} of them, ${M.epochs.fixed_batch.toFixed(2)} of a pass`,
          ],
        },
        {
          cells: [
            'trials',
            `every rule at every step size, ${int(T.tokens_per_trial)} tokens each at the ordinary
             model's best rate of ${T.best_lr}, chosen first from ${P.trial_lrs.join(', ')}`,
          ],
        },
        {
          cells: [
            'the gate',
            `each candidate's rebuilt gradients measured against stored ones on its starting
             weights, on the GPU, in the run's own precision; above ${pct(T.tolerance, 0)} it
             cannot be chosen`,
          ],
          __mark: 'warn',
        },
        {
          cells: [
            'same batch',
            `ordinary and reversible from the same starting weights, batch ${F.batch}, rate
             ${F.lr}, ${int(F.baseline.steps)} steps each`,
          ],
        },
        {
          cells: [
            'largest batch',
            `real training steps under a hard ${X.budget_gib} GiB cap, doubling then bisecting
             until one runs out of memory; the search stops at ${int(X.ceiling)}`,
          ],
        },
        {
          cells: [
            'near the largest',
            `the reversible model at ${pct(R.run_fraction, 0)} of the ${int(R.largest_found)} found
             — batch ${R.batch} — after a ${R.check_steps}-step check of the rate at
             ${R.lr_checks.map((c) => `${c.multiplier}×`).join(', ')}`,
          ],
        },
        {
          cells: ['machine', `an Apple GPU through ${env.device}, torch ${env.torch}`],
        },
      ]
    )
  );

  const note = el('p', 'say');
  note.innerHTML = `<b>Memory is measured two ways.</b> Bytes kept for backward are counted exactly,
    on any device, by hooks that see every tensor the forward pass saves. The largest batch is found
    by trying it: the GPU's own memory cap either holds a real training step or raises. The run near
    the largest batch backs off to ${pct(R.run_fraction, 0)} of it, because memory outside the
    framework's own tensors varies from one process to the next.`;
  s.append(note);
}

/* ============================================================== 6 · expected */

function chapterExpected(M) {
  const F = M.fixed;
  const X = M.max_batch;
  const R = M.max_run;
  const ok = eligible(M);
  const worstOk = Math.max(...ok.map((r) => r.agreement.gradient_error));
  const bad = refused(M).map((r) => r.agreement.gradient_error);
  const s = section(
    'expected',
    'expected',
    'Promises, then measurements',
    'What the method promises, set against the run',
    [
      `Each row is a claim the method makes about itself — plus, last, a hope a reader is likely to
       bring to it. Set down before the results so a finding cannot be mistaken for a story told
       backwards.`,
    ],
    { short: 'The promises', sub: 'claimed, then checked' }
  );

  s.append(
    table(
      ['the claim', 'what this run measured'],
      [
        {
          cells: [
            'Far fewer bytes kept for the backward pass',
            `<b>held</b> — ${F.kept_ratio.toFixed(1)}× fewer at the same batch`,
          ],
          __mark: 'good',
        },
        {
          cells: [
            'A larger batch in the same memory',
            `<b>held</b> — ${int(X.baseline.measured_max_batch)} → ${int(X.reversible.measured_max_batch)}
             sequences in ${X.budget_gib} GiB`,
          ],
          __mark: 'good',
        },
        {
          cells: [
            'Rebuilt gradients are the true gradients',
            `<b>held for midpoint and leapfrog</b> (worst ${pctSig(worstOk)}), <b>failed for the
             blend</b> (${pctSig(Math.min(...bad))} to ${pctSig(Math.max(...bad))})`,
          ],
          __mark: 'bad',
        },
        {
          cells: [
            'One extra forward pass per block costs speed',
            `<b>unresolved</b> — ${pct(Math.abs(F.speed_change), 0)} fewer tokens per second, a gap
             inside the machine's own spread`,
          ],
          __mark: 'warn',
        },
        {
          cells: [
            'The hope: the bigger batch trains as far on the same tokens',
            `<b>did not hold</b> — ${signed(R.loss_gap, 2)} validation loss with
             ${R.step_ratio.toFixed(1)}× fewer steps`,
          ],
          __mark: 'bad',
        },
      ]
    )
  );
}

/* ============================================================== 7 · results */

/* Figure 3 — the trials, and the gate. Adversary: the reader tries to choose a rule; the blend is
 * refused by name, with its own measured error. */
function trialsFigure(M) {
  const T = M.trials;
  const tol = T.tolerance;
  const base = baselineTrial(M);
  const END = bestRefused(M);

  const all = [...T.rules.map((r) => r.curve.loss), ...T.baseline.map((b) => b.curve.loss)].flat();
  const lo = Math.min(...all);
  const hi = Math.max(...all);
  const SW = 120;
  const SH = 36;
  const spark = (curve, cls, name) => {
    /* Stretched to its cell rather than scaled: a sparkline's aspect carries nothing, and scaling
     * one up to a wide cell made it a third of the panel's height. */
    const node = svg('svg', {
      viewBox: `0 0 ${SW} ${SH}`,
      preserveAspectRatio: 'none',
      class: `spark ${cls}`,
      role: 'img',
      'aria-label': `training loss of ${name} over its trial`,
    });
    const n = curve.loss.length;
    const d = curve.loss
      .map((v, i) => `${i ? 'L' : 'M'}${((i / (n - 1)) * (SW - 4) + 2).toFixed(1)},${(2 + ((hi - v) / (hi - lo)) * (SH - 4)).toFixed(1)}`)
      .join(' ');
    node.append(svg('path', { d, class: 'spark-line' }));
    return node;
  };

  let selected = END.rule + END.h;

  const wrap = el('div', 'trials');
  wrap.setAttribute('role', 'group');
  wrap.setAttribute('aria-label', 'Every reversible candidate; choose one to see what the gate says');

  const groups = el('div', 'tgroups');
  const cells = new Map();
  for (const rule of M.preset.trial_rules) {
    const g = el('div', 'tgroup');
    const head = el('div', 'tgroup-h');
    head.innerHTML = `<b>${rule}</b> <span class="dim">A = ${RULES[rule].A}</span>`;
    const grid = el('div', 'tgrid');
    for (const r of T.rules.filter((x) => x.rule === rule)) {
      const isChosen = r.rule === T.choice.rule && r.h === T.choice.h;
      const btn = el('button', `tcell${r.eligible ? '' : ' refused'}${isChosen ? ' chosen' : ''}`);
      btn.type = 'button';
      btn.setAttribute('aria-pressed', 'false');
      const top = el('span', 'tc-top');
      top.innerHTML = `<span class="tc-h">h = ${r.h}</span><span class="tc-tag">${
        r.eligible ? (isChosen ? 'chosen' : 'eligible') : 'refused'
      }</span>`;
      const loss = el('span', 'tc-loss', r.final_val === null ? 'diverged' : r.final_val.toFixed(4));
      const err = el('span', 'tc-err', `gradients ${pctSig(r.agreement.gradient_error)} off`);
      btn.append(top, spark(r.curve, r.eligible ? (isChosen ? 'chosen' : '') : 'refused', `${rule} at h = ${r.h}`), loss, err);
      btn.addEventListener('click', () => show(r.rule + r.h));
      grid.append(btn);
      cells.set(r.rule + r.h, { btn, r });
    }
    g.append(head, grid);
    groups.append(g);
  }

  /* The gate meter: every candidate's error on one log axis against the gate. Rows are rules, so
   * nine marks never need nine colours. Drawn at a phone's width, with each rule named above its
   * row rather than beside it: at 640 wide the gate and every blend mark sat past the right edge of
   * a 390px screen, behind a scroll — the figure's whole point, hidden. */
  const W = 248;
  const H = 168;
  const L0 = 10;
  const R0 = W - 10;
  const errs = T.rules.map((r) => r.agreement.gradient_error);
  const e0 = Math.floor(Math.log10(Math.min(...errs)));
  const e1 = Math.ceil(Math.log10(Math.max(...errs, tol)));
  const gx = (e) => L0 + ((Math.log10(e) - e0) / (e1 - e0)) * (R0 - L0);
  const rowY = (i) => 52 + i * 38;
  const meter = svg('svg', {
    viewBox: `0 0 ${W} ${H}`,
    class: 'gatefig',
    role: 'img',
    'aria-label': `Gradient error of every candidate on a logarithmic scale, against the gate at ${pct(tol, 0)}`,
  });
  for (let e = e0; e <= e1; e += 1) {
    const v = 10 ** e;
    const anchor = e === e0 ? 'ax' : e === e1 ? 'ax end' : 'ax mid';
    meter.append(svg('line', { x1: gx(v), x2: gx(v), y1: 26, y2: H - 22, class: 'gridline' }));
    /* Every other decade is labelled: at a phone's width adjacent labels touch. The gate's own
     * decade is named by the gate label. */
    if ((e - e0) % 2 === 0) meter.append(svgText(gx(v), H - 6, anchor, pctSig(v)));
  }
  meter.append(
    svg('rect', { x: gx(tol), y: 22, width: R0 - gx(tol), height: H - 44, class: 'gate-zone' }),
    svg('line', { x1: gx(tol), x2: gx(tol), y1: 18, y2: H - 22, class: 'gate-line' }),
    svgText(gx(tol) - 4, 14, 'gate-lab end', `gate · ${pct(tol, 0)}`)
  );
  const dots = new Map();
  M.preset.trial_rules.forEach((rule, i) => {
    meter.append(svgText(L0, rowY(i) - 11, 'ax strong', rule));
    for (const r of T.rules.filter((x) => x.rule === rule)) {
      const isChosen = r.rule === T.choice.rule && r.h === T.choice.h;
      const dot = svg('circle', {
        cx: gx(r.agreement.gradient_error),
        cy: rowY(i),
        r: 6,
        class: `gdot${r.eligible ? '' : ' refused'}${isChosen ? ' chosen' : ''}`,
      });
      meter.append(dot);
      dots.set(r.rule + r.h, dot);
    }
  });
  const pick = svgText(0, 0, 'gpick', '');
  meter.append(pick);

  const verdict = el('div', 'tverdict');
  verdict.setAttribute('aria-live', 'polite');

  /* guard() — a candidate with no agreement measurement has nothing for the gate to read. */
  const guard = (key) => {
    const c = cells.get(key);
    if (!c) return { note: 'no such candidate' };
    if (!c.r.agreement) return { note: `${c.r.rule} at h = ${c.r.h} has no measured agreement` };
    return null;
  };

  /* stateFor(key) — PURE. Candidate → what the gate decides and why. */
  const stateFor = (key) => {
    const r = cells.get(key).r;
    const isChosen = r.rule === T.choice.rule && r.h === T.choice.h;
    const e = r.agreement.gradient_error;
    return {
      r,
      e,
      state: !r.eligible ? 'refused' : isChosen ? 'chosen' : 'eligible',
      times: e / tol,
    };
  };

  /* show(key) — RENDER ONLY. */
  const show = (key) => {
    const no = guard(key);
    if (no) {
      verdict.textContent = no.note;
      return;
    }
    selected = key;
    const st = stateFor(key);
    wrap.dataset.state = st.state;
    wrap.dataset.selected = key;
    for (const [k, { btn }] of cells) {
      btn.setAttribute('aria-pressed', String(k === key));
      btn.classList.toggle('on', k === key);
    }
    for (const [k, dot] of dots) dot.classList.toggle('on', k === key);
    const dot = dots.get(key);
    const cx = Number(dot.getAttribute('cx'));
    pick.setAttribute('x', String(cx));
    pick.setAttribute('y', String(Number(dot.getAttribute('cy')) + 21));
    pick.setAttribute('text-anchor', cx > W - 40 ? 'end' : cx < L0 + 30 ? 'start' : 'middle');
    pick.textContent = pctSig(st.e);
    const name = `${st.r.rule} at h = ${st.r.h}`;
    const loss = st.r.final_val === null ? 'diverged' : st.r.final_val.toFixed(4);
    const against =
      st.r.final_val === null
        ? ''
        : `, ${st.r.final_val < base.final_val ? 'lower' : 'higher'} than the ordinary model's
           ${base.final_val.toFixed(4)} at the same rate`;
    if (st.state === 'refused') {
      verdict.className = 'tverdict bad';
      verdict.innerHTML = `<span class="fig-verdict hit">refused</span> ${name} scored
        ${loss}${against} — and its rebuilt
        gradients were <b>${pctSig(st.e)}</b> away from the true ones, ${st.times.toFixed(1)}× the
        gate. It was trained and is shown, but a run using it would be learning from gradients that
        are not the ones it reports.`;
    } else if (st.state === 'chosen') {
      const best = Math.min(...eligible(M).map((r) => r.final_val ?? Infinity));
      verdict.className = 'tverdict good';
      verdict.innerHTML = `<span class="fig-verdict">chosen</span> ${name} scored ${loss}${against}${
        st.r.final_val === best ? ', the lowest of every eligible candidate' : ''
      }. Its rebuilt gradients were ${pctSig(st.e)} from the true ones —
        ${(tol / st.e).toFixed(0)}× inside the gate.`;
    } else {
      verdict.className = 'tverdict';
      verdict.innerHTML = `<span class="fig-verdict">eligible</span> ${name} scored ${loss}; its rebuilt gradients were
        ${pctSig(st.e)} from the true ones, inside the gate. It lost on loss, not on correctness.`;
    }
  };

  wrap.playAll = () => show(END.rule + END.h);
  PLAY.push(wrap.playAll);
  wrap.append(groups, meter, verdict);
  show(selected);

  const errsRefused = refused(M).map((r) => r.agreement.gradient_error);
  const worstOk = Math.max(...eligible(M).map((r) => r.agreement.gradient_error));
  return figure(
    wrap,
    `<b>Try to choose the blend: the gate refuses every setting of it.</b> Each panel is one short
     trial — its training loss, its final validation loss, and how far its rebuilt gradients were
     from stored ones. The strip below puts all ${spell(T.rules.length)} errors on one scale: the
     blend's sit at ${pctSig(Math.min(...errsRefused))} to ${pctSig(Math.max(...errsRefused))},
     beyond the ${pct(tol, 0)} line, while the worst midpoint or leapfrog setting is
     ${Math.floor(tol / worstOk)}× inside it. The blend's losses look ordinary, which is the danger
     — nothing in a loss curve says the gradients behind it are wrong.`
  );
}

/* Figure 4 — the memory budget. Budget: a fixed pool, two ways of spending it. The reader slides
 * the batch, sees the derived cost fill the bar, and is asked to predict the measured edge first. */
function budgetFigure(M) {
  const X = M.max_batch;
  const budget = X.budget_bytes;
  const V = [
    { key: 'baseline', name: 'ordinary', v: X.baseline },
    { key: 'reversible', name: 'reversible', v: X.reversible },
  ];
  const ceiling = X.ceiling;

  /* Two panels at a phone's width, side by side where there is room. One 720-wide drawing put the
   * measured markers and the cap past the right edge of a 390px screen, behind a scroll. */
  const W = 248;
  const L0 = 8;
  const R0 = W - 8;
  /* The byte axis runs to twice the budget so an overfull bar is visibly overfull, then clips. */
  const span = budget * 2;
  const bx = (bytes) => L0 + (Math.min(bytes, span) / span) * (R0 - L0);
  const lx = (b) => L0 + (Math.log(b) / Math.log(ceiling)) * (R0 - L0);
  const barY = (i) => 58 + i * 52;
  const BH = 176;
  const axY = (i) => 60 + i * 64;
  const AH = 198;
  /* A label centred on its mark unless that would run off either edge. */
  const anchorFor = (x, text) => {
    const half = text.length * 3.4;
    if (x - half < 2) return 'start';
    if (x + half > W - 2) return 'end';
    return 'middle';
  };

  /* Opens at the batch the long runs used, so the first thing drawn is a configuration that ran. */
  let batch = M.fixed.batch;
  let revealed = false;
  let guess = null;

  const wrap = el('div', 'budget');
  wrap.setAttribute('role', 'group');
  wrap.setAttribute('aria-label', 'The memory budget, filled by a batch of your choosing');

  const ask = el('p', 'b-ask');
  ask.innerHTML = `<b>Before you reveal:</b> slide the batch to where you think the reversible
    model ran out of ${X.budget_gib} GiB on the real GPU.`;

  const ctl = el('div', 'walk-ctl');
  const label = el('label', null, 'Batch, in sequences');
  label.htmlFor = 'budget-batch';
  const range = el('input');
  range.type = 'range';
  range.id = 'budget-batch';
  range.min = '0';
  range.max = '1000';
  range.step = '1';
  const out = el('output', 'walk-out');
  out.htmlFor = 'budget-batch';
  const reveal = el('button', 'btn', 'Pin my guess and reveal');
  reveal.type = 'button';
  reveal.setAttribute('aria-pressed', 'false');
  ctl.append(label, range, out, reveal);

  const node = svg('svg', {
    viewBox: `0 0 ${W} ${BH}`,
    class: 'budgetfig',
    role: 'img',
    'aria-label': 'Two bars of memory against the budget at the chosen batch, one per model',
  });
  node.append(svgText(L0, 14, 'fig-lab', 'memory at this batch'));
  node.append(
    svg('line', { x1: bx(budget), x2: bx(budget), y1: 24, y2: barY(1) + 26, class: 'budget-line' }),
    svgText(bx(budget) + 4, 32, 'ax strong', `cap · ${X.budget_gib} GiB`)
  );
  const bars = V.map((d, i) => {
    node.append(svgText(L0, barY(i) - 7, 'ax strong', d.name));
    node.append(svg('rect', { x: L0, y: barY(i), width: R0 - L0, height: 20, rx: 4, class: 'b-track' }));
    const state = svg('rect', { x: L0, y: barY(i), width: bx(d.v.state_bytes) - L0, height: 20, class: 'b-state' });
    const act = svg('rect', { x: bx(d.v.state_bytes), y: barY(i), width: 0, height: 20, class: `b-act ${d.key}` });
    const over = svg('rect', { x: bx(budget), y: barY(i), width: 0, height: 20, class: 'b-over' });
    const val = svgText(R0, barY(i) - 7, 'ax end', '');
    node.append(state, act, over, val);
    return { act, over, val, d };
  });
  node.append(
    svgText(L0, barY(1) + 42, 'b-key', 'grey: weights, gradients, optimiser state'),
    svgText(L0, barY(1) + 57, 'b-key', 'colour: what the batch adds')
  );

  /* The batch axis, log scale, with each variant's derived and measured largest batch. */
  const axis = svg('svg', {
    viewBox: `0 0 ${W} ${AH}`,
    class: 'budgetfig',
    role: 'img',
    'aria-label':
      "Each model's derived and measured largest batch on a logarithmic axis, with the batch chosen",
  });
  axis.append(svgText(L0, 14, 'fig-lab', 'largest batch · log scale'));
  /* Drawn first, so the marks and their labels paint over it rather than under it. */
  const cursor = svg('line', { x1: 0, x2: 0, y1: axY(0) - 16, y2: axY(1) + 8, class: 'b-cursor' });
  axis.append(cursor);
  const tickBatches = [];
  for (let b = 1; b <= ceiling; b *= 4) tickBatches.push(b);
  const markers = V.map((d, i) => {
    axis.append(svg('line', { x1: L0, x2: R0, y1: axY(i), y2: axY(i), class: 'gridline' }));
    axis.append(svgText(L0, axY(i) - 22, 'ax strong', d.name));
    for (const b of tickBatches) axis.append(svg('line', { x1: lx(b), x2: lx(b), y1: axY(i) - 3, y2: axY(i) + 3, class: 'tick' }));
    const dx = lx(d.v.derived_max_batch);
    const dText = `derived ${int(d.v.derived_max_batch)}`;
    const dLab = svgText(dx, axY(i) - 10, 'ax', dText);
    dLab.setAttribute('text-anchor', anchorFor(dx, dText));
    axis.append(svg('circle', { cx: dx, cy: axY(i), r: 6, class: 'm-derived' }), dLab);
    const mx = lx(d.v.measured_max_batch);
    const mText = `measured ${int(d.v.measured_max_batch)}`;
    const meas = svg('g', { class: 'm-measured' });
    const mLab = svgText(mx, axY(i) + 20, 'ax strong', mText);
    mLab.setAttribute('text-anchor', anchorFor(mx, mText));
    meas.append(svg('circle', { cx: mx, cy: axY(i), r: 6 }), mLab);
    /* Not placed at the measured position: a placeholder there would give the answer away. */
    const hidden = svgText(R0, axY(i) + 20, 'ax end m-hidden', 'measured: hidden');
    axis.append(meas, hidden);
    return { meas, hidden };
  });
  for (const b of tickBatches.filter((_, k) => k % 2 === 0)) {
    const t = svgText(lx(b), AH - 6, 'ax', int(b));
    t.setAttribute('text-anchor', anchorFor(lx(b), int(b)));
    axis.append(t);
  }
  const ghost = svg('path', { d: '', class: 'b-ghost' });
  const ghostLab = svgText(0, 0, 'ax mid b-ghost-lab', '');
  axis.append(ghost, ghostLab);
  const panels = el('div', 'budget-panels');
  panels.append(node, axis);

  const read = el('p', 'b-read');
  read.setAttribute('aria-live', 'polite');

  const toBatch = (v) => Math.max(1, Math.round(Math.exp((Number(v) / 1000) * Math.log(ceiling))));
  const toSlider = (b) => String(Math.round((Math.log(b) / Math.log(ceiling)) * 1000));

  /* guard() — a batch the search never tried has no measured answer to compare against. */
  const guard = (b) => (b < 1 || b > ceiling ? { note: `the search never went beyond ${int(ceiling)}` } : null);

  /* stateFor(b) — PURE. Batch → bytes each variant needs and whether the derived count fits. */
  const stateFor = (b) =>
    V.map((d) => {
      const need = d.v.state_bytes + b * d.v.derived_bytes_per_sample;
      return { d, need, fits: need <= budget, act: b * d.v.derived_bytes_per_sample };
    });

  /* show(b) — RENDER ONLY. */
  const show = (b) => {
    const no = guard(b);
    if (no) {
      read.textContent = no.note;
      return;
    }
    batch = b;
    range.value = toSlider(b);
    out.textContent = `${int(b)}`;
    const st = stateFor(b);
    st.forEach((s, i) => {
      const { act, over, val } = bars[i];
      const start = bx(s.d.v.state_bytes);
      act.setAttribute('width', String(Math.max(0, bx(Math.min(s.need, budget)) - start)));
      over.setAttribute('width', String(Math.max(0, bx(s.need) - bx(budget))));
      val.textContent = `${gib(s.need)} GiB${s.need > span ? ' →' : ''}${s.fits ? '' : ' · over'}`;
      val.setAttribute('class', `ax end${s.fits ? '' : ' warn'}`);
    });
    cursor.setAttribute('x1', String(lx(b)));
    cursor.setAttribute('x2', String(lx(b)));
    wrap.classList.toggle('revealed', revealed);
    reveal.setAttribute('aria-pressed', String(revealed));
    for (const m of markers) {
      m.meas.style.display = revealed ? '' : 'none';
      m.hidden.style.display = revealed ? 'none' : '';
    }
    if (revealed && guess !== null) {
      const gx = lx(guess);
      const gy = axY(1);
      ghost.setAttribute('d', `M ${gx} ${gy - 12} L ${gx} ${gy + 28}`);
      ghostLab.setAttribute('x', String(Math.min(Math.max(gx, L0 + 96), R0 - 96)));
      ghostLab.setAttribute('y', String(gy + 44));
      const actual = X.reversible.measured_max_batch;
      const r = guess > actual ? guess / actual : actual / guess;
      ghostLab.textContent = `your guess ${int(guess)} · ${r < 1.05 ? 'on the mark' : `${r.toFixed(1)}× ${guess > actual ? 'high' : 'low'}`}`;
    } else {
      ghost.setAttribute('d', '');
      ghostLab.textContent = '';
    }
    const [o, r] = st;
    read.innerHTML = `At <b>${int(b)}</b> sequences the derived count needs ${gib(o.need)} GiB for the
      ordinary model and ${gib(r.need)} GiB for the reversible one, against a cap of
      ${X.budget_gib} GiB. ${
        revealed
          ? `On the GPU, the ordinary model's real limit was ${int(X.baseline.measured_max_batch)}
             and the reversible one's ${int(X.reversible.measured_max_batch)} —
             ${pct(X.baseline.measured_share, 0)} and ${pct(X.reversible.measured_share, 0)} of what
             the count predicts.`
          : 'The measured limits stay hidden until you reveal them.'
      }`;
  };

  range.addEventListener('input', () => show(toBatch(range.value)));
  reveal.addEventListener('click', () => {
    guess = batch;
    revealed = true;
    show(batch);
  });
  wrap.playAll = () => {
    revealed = true;
    show(X.reversible.measured_max_batch);
  };
  PLAY.push(wrap.playAll);

  /* The standing limitation — true whatever batch is drawn, so it never changes with the control. */
  const rail = el('div', 'fig-rail');
  rail.innerHTML = `<b>Hollow means derived.</b> A derived limit is a count of bytes the run measured,
    not a step the GPU took; only the solid markers are measurements.`;
  wrap.append(ask, ctl, panels, read, rail);
  show(batch);

  return figure(
    wrap,
    `<b>The bar is arithmetic; the measured marker is the GPU.</b> The derived limit is where the
     ${mib(X.baseline.state_bytes)} MiB of weights, gradients and optimiser state, plus the batch's
     measured cost per sequence, reach the cap: ${int(X.baseline.derived_max_batch)} and
     ${int(X.reversible.derived_max_batch)}. Real
     steps ran out sooner — at ${pct(X.baseline.measured_share, 0)} and
     ${pct(X.reversible.measured_share, 0)} of those — because the count leaves out gradient
     buffers, the allocator's fragmentation and kernel workspaces, for both models. That is why the
     measured batch is the headline and the derived one is drawn hollow.`
  );
}

/* Figure 5 — the long runs. Static: three curves, read by eye. Drawn at a phone's width with the
 * end values in a narrow right gutter: at 720 wide the gutter, which carries the result, was the
 * part a phone could not see. */
function curvesFigure(M) {
  const F = M.fixed;
  const R = M.max_run;
  const series = [
    { key: 'base', name: ['ordinary', `batch ${F.batch}`], c: F.curves.baseline, v: F.validation.baseline, end: F.baseline.final_val },
    { key: 'rev', name: ['reversible', `batch ${F.batch}`], c: F.curves.reversible, v: F.validation.reversible, end: F.reversible.final_val },
    { key: 'big', name: ['reversible', `batch ${R.batch}`], c: R.curve, v: R.validation, end: R.run.final_val },
  ];
  const W = 248;
  const H = 292;
  const L0 = 28;
  const R0 = 158;
  const T0 = 34;
  const B0 = H - 38;
  const allEnds = series.flatMap((s) => [...s.v.loss, ...s.c.loss.slice(-20)]);
  const lo = Math.floor(Math.min(...allEnds) * 2) / 2;
  const hi = lo + 3;
  const maxTok = Math.max(...series.flatMap((s) => s.c.tokens));
  const x = (t) => L0 + (t / maxTok) * (R0 - L0);
  /* Not clamped: a value above the axis leaves through the top edge, cut by the clip below. Clamping
   * drew every early loss as a flat line along the ceiling, which reads as a plateau that never
   * happened. */
  const y = (v) => T0 + ((hi - v) / (hi - lo)) * (B0 - T0);
  const allStartAbove = series.every((s) => s.c.loss[0] > hi);

  const node = svg('svg', {
    viewBox: `0 0 ${W} ${H}`,
    class: 'curvefig',
    role: 'img',
    'aria-label':
      'Training loss against tokens for the ordinary and reversible runs at the same batch, and the ' +
      'reversible run at its large batch, with validation losses as marks',
  });
  for (let v = lo; v <= hi + 1e-9; v += 0.5) {
    node.append(
      svg('line', { x1: L0, x2: R0, y1: y(v), y2: y(v), class: 'gridline' }),
      svgText(L0 - 5, y(v) + 4, 'ax end', v.toFixed(1))
    );
  }
  /* Three ticks — start, middle, end — because at a phone's width a fourth ran into its neighbour. */
  for (let k = 0; k <= 2; k += 1) {
    const t = (maxTok * k) / 2;
    const anchor = k === 0 ? 'ax' : k === 2 ? 'ax end' : 'ax mid';
    node.append(
      svg('line', { x1: x(t), x2: x(t), y1: B0, y2: B0 + 4, class: 'gridline' }),
      svgText(x(t), B0 + 16, anchor, `${(t / 1e6).toFixed(0)}M`)
    );
  }
  node.append(svgText((L0 + R0) / 2, H - 4, 'ax mid', 'tokens trained'));
  node.append(svgText(4, 16, 'ax', `loss, axis cut at ${hi.toFixed(1)}`));

  const defs = svg('defs');
  const clip = svg('clipPath', { id: 'curve-clip' });
  clip.append(svg('rect', { x: L0, y: T0, width: R0 - L0 + 5, height: B0 - T0 }));
  defs.append(clip);
  const plot = svg('g', { 'clip-path': 'url(#curve-clip)' });
  node.append(defs, plot);
  for (const s of series) {
    const d = s.c.tokens.map((t, i) => `${i ? 'L' : 'M'}${x(t).toFixed(1)},${y(s.c.loss[i]).toFixed(1)}`).join(' ');
    plot.append(svg('path', { d, class: `series ${s.key}` }));
    s.v.tokens.forEach((t, i) => {
      plot.append(svg('circle', { cx: x(t), cy: y(s.v.loss[i]), r: 3.5, class: `vmark ${s.key}` }));
    });
  }
  /* End labels in the right gutter, pushed apart so two close values never overprint, then lifted
   * as a block if the lowest would run off the bottom. */
  const GAP = 40;
  const labels = series.map((s) => ({ s, at: y(s.end) })).sort((a, b) => a.at - b.at);
  for (let i = 1; i < labels.length; i += 1) {
    if (labels[i].at - labels[i - 1].at < GAP) labels[i].at = labels[i - 1].at + GAP;
  }
  const overrun = labels[labels.length - 1].at + 28 - (H - 4);
  if (overrun > 0) for (const l of labels) l.at -= overrun;
  for (const { s, at } of labels) {
    node.append(
      svg('line', { x1: x(maxTok) + 3, x2: R0 + 8, y1: y(s.end), y2: at - 4, class: `lead ${s.key}` }),
      svgText(R0 + 11, at, `end-v ${s.key}`, s.end.toFixed(4)),
      svgText(R0 + 11, at + 13, 'ax', s.name[0]),
      svgText(R0 + 11, at + 26, 'ax', s.name[1])
    );
  }

  return figure(
    node,
    `<b>At the same batch the two curves are hard to tell apart; at the large batch they are not.</b>
     Lines are training loss — each point the mean of about
     ${Math.round(F.curves.baseline.per_point * F.curves.baseline.logged_every)} steps — and the marks
     are validation losses on held-out text${
       allStartAbove ? `; every run starts above the ${hi.toFixed(1)} the axis is cut at` : ''
     }. The reversible run at batch ${F.batch} ends ${signed(F.loss_gap, 4)} from the ordinary one,
     a gap one seed cannot rank. The run at batch ${R.batch} saw the same tokens in
     ${R.step_ratio.toFixed(1)}× fewer steps and ends ${signed(R.loss_gap, 2)} behind. Had that curve
     caught up by the last token, there would be no gap to explain; it does not, and
     <a href="#negatives">the audit trail</a> says what that does and does not show.`
  );
}

function chapterResults(M) {
  const F = M.fixed;
  const X = M.max_batch;
  const chosen = chosenTrial(M);
  const s = section(
    'results',
    'results',
    'What happened',
    'Less memory, a bigger batch, and a gate that did its job',
    [
      `<b>First the choice.</b> ${Spell(M.trials.rules.length)} candidates trained for the same short
       run. The gate looked at each one's rebuilt gradients before its loss counted for anything.`,
    ],
    { short: 'The results', sub: 'the choice, the memory, the long runs' }
  );
  s.append(trialsFigure(M));

  const mem = el('p', 'say');
  mem.innerHTML = `<b>Then the memory.</b> With ${chosen.rule} at h = ${chosen.h} the reversible
    model keeps ${mib(F.reversible.saved_bytes)} MiB for the backward pass where the ordinary model
    keeps ${mib(F.baseline.saved_bytes)} MiB — <b>${F.kept_ratio.toFixed(1)}× fewer</b> — and in a fixed
    ${X.budget_gib} GiB the batch it can train at grows from ${int(X.baseline.measured_max_batch)} to
    ${int(X.reversible.measured_max_batch)}.`;
  s.append(mem);
  s.append(budgetFigure(M));

  const runs = el('p', 'say');
  runs.innerHTML = `<b>Then the long runs.</b> Both models trained from the same starting weights
    on the same ${int(F.baseline.tokens)} tokens. The reversible model's rebuilt gradients were
    checked against stored ones at both ends of its run: ${pctSig(F.agreement.init.gradient_error)}
    apart on the starting weights and ${pctSig(F.agreement.trained.gradient_error)} on the trained
    ones.`;
  s.append(runs);
  s.append(
    table(
      ['at batch ' + F.batch, 'ordinary', 'reversible'],
      [
        { cells: ['final validation loss', F.baseline.final_val.toFixed(4), F.reversible.final_val.toFixed(4)] },
        { cells: ['kept for backward', `${mib(F.baseline.saved_bytes)} MiB`, `${mib(F.reversible.saved_bytes)} MiB`], __mark: 'good' },
        {
          cells: ['GPU memory after a forward pass, sampled', `${mib(F.baseline.allocated_max_sample)} MiB`, `${mib(F.reversible.allocated_max_sample)} MiB`],
        },
        { cells: ['tokens per second', int(F.baseline.tokens_per_second), int(F.reversible.tokens_per_second)], __mark: 'warn' },
        { cells: ['wall time of the timed steps', `${int(F.baseline.seconds)} s`, `${int(F.reversible.seconds)} s`] },
      ]
    )
  );
  s.append(curvesFigure(M));
}

/* ============================================================== 8 · negatives */

function chapterNegatives(M) {
  const F = M.fixed;
  const R = M.max_run;
  const X = M.max_batch;
  const speedRatio = F.baseline.tokens_per_second / F.reversible.tokens_per_second;
  const fewer = (change) => `${pct(Math.abs(change), 0)} ${change < 0 ? 'fewer' : 'more'}`;
  const rows = [
    {
      cells: [
        `<b>The large batch trained less far</b>`,
        `${signed(R.loss_gap, 4)} validation loss against the ordinary model at batch ${F.batch},
         with ${int(R.run.steps)} steps instead of ${int(F.baseline.steps)}. Fewer, larger steps at
         an unscaled rate is the explanation on offer, and it is untested: a run with the rate
         scaled to the batch would test it, and none was made.`,
      ],
      __mark: 'bad',
    },
    ...(R.lr_multiplier_at_edge
      ? [
          {
            cells: [
              '<b>The rate check stopped at the edge of its grid</b>',
              `Over ${R.check_steps} steps it chose ${R.lr_multiplier}× the fixed-batch rate — the
               ${R.lr_multiplier_at_edge} multiplier it tried — so a
               ${R.lr_multiplier_at_edge === 'smallest' ? 'lower' : 'higher'} one might have done
               better. It is a best-of-grid, not an optimum.`,
            ],
            __mark: 'warn',
          },
        ]
      : []),
    {
      cells: [
        "<b>The speed gap is inside the machine's own noise</b>",
        `The reversible model ran ${fewer(F.speed_change)} tokens per second at the same batch, and
         ${fewer(R.speed_change)} at batch ${R.batch}. The same ordinary model varied
         ${M.throughput_floor.toFixed(2)}× across its own trials, so at the precision that spread
         allows, their ratio is ${ratio(speedRatio, M.throughput_floor - 1)}. The extra forward pass
         is expected to cost time; on this machine the measured gap does not rank them.`,
      ],
      __mark: 'warn',
    },
    {
      cells: [
        '<b>The derived batch was optimistic, unevenly</b>',
        `The count of kept bytes predicted ${int(X.baseline.derived_max_batch)} and
         ${int(X.reversible.derived_max_batch)}; the GPU held ${pct(X.baseline.measured_share, 0)}
         and ${pct(X.reversible.measured_share, 0)} of that. What it leaves out costs the reversible
         model a larger share of its batch, so its derived figure is not a stand-in for measuring.`,
      ],
    },
    {
      cells: [
        '<b>The measurement leaked memory</b>',
        `Counting what a forward pass keeps handed each saved tensor back to the graph, which tied the
         reversible blocks into a cycle the garbage collector could not break. Each run in the capped
         process left a graph behind, taking memory from the very search that was measuring it. It
         was found, fixed and given a test before the published search ran.`,
      ],
    },
    {
      cells: [
        '<b>The first full attempt died minutes in</b>',
        `Checking the rebuilt gradients converted them to a number format the Apple GPU does not
         support. Every test ran on the CPU and could not see it, so a short run on the GPU now comes
         before every full one.`,
      ],
    },
  ];
  const s = section(
    'negatives',
    'negatives',
    'The audit trail',
    'What did not work, or did not settle',
    [
      `Some of these are results that went the wrong way and some are mistakes in the apparatus,
       caught before publishing. <b>Both kinds are here</b>, because a page that only reports what
       worked has not earned the results it shows.`,
    ],
    { short: 'The negatives', sub: 'what failed, what stayed open' }
  );
  s.append(table(['finding', 'what it means'], rows, 'grid prose'));
}

/* ============================================================== 9 · conclusion */

function chapterConclusion(M) {
  const F = M.fixed;
  const X = M.max_batch;
  const s = section(
    'conclusion',
    'conclusion',
    'The verdict',
    'Trade memory for compute — then measure the trade',
    [
      `Rebuilding activations instead of storing them works as promised on memory:
       ${F.kept_ratio.toFixed(1)}× fewer bytes kept and ${X.batch_ratio.toFixed(1)}× the batch in the
       same cap, with a final loss ${signed(F.loss_gap, 3)} from the ordinary model's — a gap a
       single seed per run cannot rank.`,
      `<b>It does not come for free on correctness.</b> A rule whose inverse divides by a number
       smaller than one at every layer magnifies rounding on the way down, and in this model's own
       precision that was enough to move the blend's gradients by
       ${pctSig(Math.min(...refused(M).map((r) => r.agreement.gradient_error)))} to
       ${pctSig(Math.max(...refused(M).map((r) => r.agreement.gradient_error)))}. Nothing in its
       loss showed it.`,
    ],
    { short: 'The verdict', sub: 'what to carry away' }
  );
  const box = el('div', 'takeaway');
  box.innerHTML = `<b>The check worth copying.</b> Before trusting a reversible run, compare its
    rebuilt gradients with stored ones on the run's own device, precision and depth — and refuse a
    rule that fails, before its loss can make the case for it. A test in high precision on a small
    model passes for every rule here, including the one that failed.`;
  s.append(box);
}

/* ============================================================== 10 · limits */

function chapterLimits(M) {
  const X = M.max_batch;
  const P = M.preset;
  /* Built before the section, so nothing above it has to count them. */
  const items = [
    `<b>One seed per long run.</b> Each was trained once and no seed-to-seed spread was measured,
     so a difference in final loss is reported, not ranked.`,
    `<b>The large-batch run is compared with the ordinary model at its fixed batch</b> of
     ${M.fixed.batch}, not at the ordinary model's own largest batch, which would have cost another
     full run.`,
    `<b>The derived batch leaves memory out</b> — gradient buffers, the allocator's fragmentation
     and kernel workspaces, for both variants — which is why the measured batch is the headline.`,
    `<b>Apple's GPU keeps no peak-memory counter.</b> The largest batch is measured directly, but
     "GPU memory after a forward pass" is a sample, not a peak. The exact, device-independent
     number is the bytes kept for backward.`,
    `<b>The ${X.budget_gib} GiB cap is ours</b>, chosen so the search is reproducible; the device
     itself offered this process ${gib(X.device_limit_bytes)} GiB. The ratio between variants is the
     part that transfers, not the batch sizes.`,
    `<b>The model is small and shallow</b> — ${P.depth} blocks. The saving grows with depth, so a
     deeper model would show more of it; the per-sequence bytes are reported so it can be
     estimated, not so it should be.`,
    `<b>The step size and the blend weight were chosen on short runs.</b> A rule that trained well
     for ${int(M.trials.tokens_per_trial)} tokens could still drift over a much longer run; the long
     runs' curves are kept so that would be visible.`,
    `<b>How the method seeds its first step is not stated where it is published</b>; starting from
     two copies of the embedding output is this exercise's choice.`,
  ];
  const s = section(
    'limits',
    'limits',
    'In the open',
    'What this run cannot establish',
    [
      `In the open text rather than behind a disclosure, because a limitation a reader has to expand
       is a limitation the page is hiding.`,
    ],
    { short: 'The limits', sub: 'what one machine and one seed cannot settle' }
  );
  s.classList.add('notice');
  const ul = el('ul', 'limitlist');
  for (const item of items) {
    const li = el('li');
    li.innerHTML = item;
    ul.append(li);
  }
  s.append(ul);
}

/* ============================================================== 11 · next */

function chapterNext(M) {
  const R = M.max_run;
  const s = section(
    'next',
    'next',
    'What this opens',
    'What would settle the open questions',
    [
      `Each of these is a run this exercise chose not to make, and each would turn an open line in
       the audit trail into a measurement.`,
    ],
    { short: 'What this opens', sub: 'the runs that would answer what is open' }
  );
  const ul = el('ul', 'nextlist');
  for (const item of [
    `<b>Scale the rate with the batch.</b> The run at batch ${R.batch} kept the fixed-batch rate
     after a short check that chose the edge of its grid. A run whose rate grows with the batch
     would show whether the loss gap belongs to the steps or to the stack.`,
    `<b>Give the ordinary model its own largest batch.</b> Comparing both models at their own
     limits, rather than one at its limit and one at a fixed batch, is the comparison a practitioner
     actually faces.`,
    `<b>Go deeper.</b> The ordinary model's activation memory grows with depth and the reversible
     one's does not, so a deeper model should show a wider gap than this ${spell(M.preset.depth)}-block
     one does — a prediction, not a measurement.`,
    `<b>Rescue the blend, or retire it.</b> A blend weight closer to one, or the inversion done in
     higher precision, could shrink the amplification that disqualified it. Either change would
     have to pass the same gate before its loss counted.`,
  ]) {
    const li = el('li');
    li.innerHTML = item;
    ul.append(li);
  }
  s.append(ul);
}

/* ============================================================== 12 · reproduce */

function chapterReproduce(M) {
  const prov = M.provenance;
  const tasks = Object.keys(prov);
  const first = prov[tasks[0]];
  const env = first.environment;
  const same = (field) => tasks.every((t) => prov[t][field] === first[field]);
  const cut = (v) => `<code>${v.slice(0, 19)}…</code>`;
  const each = (field, fmt) =>
    same(field) ? fmt(first[field]) : tasks.map((t) => `${t}: ${fmt(prov[t][field])}`).join('<br>');
  const rows = [
    [
      'which settings',
      tasks.map((t) => `${t}: <code>${prov[t].config_fingerprint}</code>`).join('<br>'),
      'every field of the configuration, hashed — one per experiment, because each names its own task',
    ],
    [
      'which code',
      each('code_digest', cut),
      "this exercise's package and exercise 11's, whose model, data reader and schedules it reuses",
    ],
    ['which commit', each('git_sha', (v) => `<code>${v.slice(0, 12)}</code>`), 'the tree every result came from'],
    ['which text', each('corpus_digest', cut), `${M.corpus.dataset}, ${int(M.corpus.train_tokens)} training tokens`],
    ['which vocabulary', each('tokenizer_digest', cut), "exercise 02's frozen tokenizer"],
    [
      'which machine',
      `${env.platform.split('-').slice(0, 2).join(' ')} · ${env.device}`,
      `python ${env.python} · torch ${env.torch} · ${env.torch_threads} threads`,
    ],
  ];

  const s = section(
    'reproduce',
    'reproduce',
    'Every figure and its parent',
    'Where every number on this page came from',
    [
      `A number nobody can regenerate is not evidence. Every figure here is read from
       ${spell(tasks.length)} tracked result files, and each file carries the block below; the code
       that writes them <b>refuses</b> to write one without it.`,
      `<b>The machine is an input here, not context.</b> The largest batch is a property of one
       GPU's memory under one cap, and the speed verdicts are judged against that machine's own
       spread — so the device is recorded beside every result.`,
    ],
    { short: 'The provenance', sub: 'what produced every number here' }
  );

  s.append(
    table(
      ['question', 'answer', 'what it covers'],
      rows.map((r) => ({ cells: r })),
      'grid'
    )
  );

  const note = el('p', 'say small');
  note.innerHTML = `Digests are shown truncated to fit; the files carry them at full length, which is
    the point — a prefix cannot be checked. The commands that regenerate all of this are in the
    exercise's own README, beside the code they run.
    <a href="https://github.com/pankajkr23/llm-pretraining-exercises/tree/main/src/exercises/13-reversibility">Code,
    tests and the full write-up</a>.`;
  s.append(note);
}

/* ============================================================== rail + footer */

function buildRail(root) {
  const rail = document.getElementById('rail');
  if (!rail) return;
  rail.replaceChildren();
  const inner = el('div', 'rail-inner');
  const head = el('div', 'rail-head');
  head.append(el('div', 'rail-title', 'On this page'));
  inner.append(head);
  const list = el('div', 'rail-list');
  const links = new Map();
  for (const sec of root.querySelectorAll('section')) {
    if (!sec.dataset.title) continue;
    const link = el('a', 'rail-link');
    link.href = `#${sec.id}`;
    const body = el('span', 'rail-body');
    body.append(el('span', 'rail-t', sec.dataset.title));
    if (sec.dataset.sub) body.append(el('span', 'rail-sub', sec.dataset.sub));
    link.append(el('span', 'rail-n', sec.dataset.n), body);
    list.append(link);
    links.set(sec.id, link);
  }
  inner.append(list);
  rail.append(inner);
  markPosition(root, links);
}

/* Registered from the code that has already appended the sections: an IntersectionObserver on a
 * detached node never fires and reports nothing, which is how three of exercise 08's plates
 * shipped without ever animating. */
function markPosition(root, links) {
  const sections = [...root.querySelectorAll('section')].filter((s) => links.has(s.id));
  if (!sections.length || typeof IntersectionObserver !== 'function') return;

  const visible = new Set();
  const observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) visible.add(entry.target.id);
        else visible.delete(entry.target.id);
      }
      const current = sections.find((s) => visible.has(s.id));
      for (const [id, link] of links) {
        link.classList.toggle('on', Boolean(current) && id === current.id);
      }
    },
    { rootMargin: '-10% 0px -70% 0px', threshold: 0 }
  );
  for (const s of sections) observer.observe(s);
}

function buildFooter() {
  const f = document.getElementById('foot');
  if (!f) return;
  const p = el('p', 'say small');
  p.innerHTML =
    'Written for whoever arrives first: the argument is in plain words, and every number behind it ' +
    'is regenerated from tracked result files. ' +
    '<a href="https://github.com/pankajkr23/llm-pretraining-exercises/tree/main/src/exercises/13-reversibility">Code, tests and the full write-up</a>.';
  f.append(p);
}

/* Print and reduced motion both get every interactive figure's end state, painted. */
function paintEndStates() {
  const reduce =
    typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (reduce) for (const play of PLAY) play();
  window.addEventListener('beforeprint', () => {
    for (const play of PLAY) play();
  });
}

export function buildPage(M) {
  chapterThesis(M);
  chapterGlossary(M);
  chapterProblem(M);
  chapterMechanism(M);
  chapterMethod(M);
  chapterExpected(M);
  chapterResults(M);
  chapterNegatives(M);
  chapterConclusion(M);
  chapterLimits(M);
  chapterNext(M);
  chapterReproduce(M);
  buildRail(main());
  buildFooter();
  paintEndStates();
}
