"""Generate `web/data.js` from the tracked catalogue.

    uv run python src/exercises/08-modern-attention-variants/tools/build_web_data.py

`results/mechanisms.json` is the single source for every date, trade-off and citation the page
renders, and `src/attention/` owns everything derived from it — the ordering, the periods, the
gaps, the cache arithmetic. The page reads only what this script emits, so a figure on the site
cannot disagree with the evidence, and the derived findings cannot disagree with the functions the
tests exercise.

Unlike `tools/build_notebook.py`, this file is **tracked**. It is not course material in another
form; it is the build step for a published artifact, and CI has to be able to check the page it
produces.
"""

import json
import sys
from pathlib import Path

EXERCISE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(EXERCISE / "src"))

from attention.cache import (  # noqa: E402
    ACCELERATOR_BYTES,
    kv_cache_bytes,
    sharing_ladder,
    tokens_before_wall,
)
from attention.catalogue import CATALOGUE, MANDATED, load  # noqa: E402
from attention.config import YARDSTICK_CONTEXTS, Yardstick  # noqa: E402
from attention.story import WELLS, span  # noqa: E402
from attention.story import check as check_wells  # noqa: E402
from attention.timeline import (  # noqa: E402
    arc_robustness,
    arc_verdict,
    bills_addressed,
    gaps,
    in_order,
    pressure_by_period,
)

OUT = EXERCISE / "web" / "data.js"

BANNER = """\
// GENERATED by tools/build_web_data.py from results/mechanisms.json — do not edit by hand.
//
// Every date, trade-off and citation on this page comes from the tracked catalogue, and every
// derived figure comes from the same functions the tests exercise. Editing this file directly
// would let the page disagree with the evidence that produced it; regenerate instead:
//
//     uv run python src/exercises/08-modern-attention-variants/tools/build_web_data.py
"""


def payload() -> dict:
    """Everything the page renders, derived here so the page derives nothing."""
    mechanisms = in_order(load())
    check_wells(mechanisms)  # refuse to emit a page that would silently drop a mechanism
    yard = Yardstick()

    verdict = arc_verdict(mechanisms)
    robust = arc_robustness(mechanisms)
    return {
        "mechanisms": [
            {
                "key": m.key,
                "name": m.name,
                "aka": list(m.aka),
                "date": m.date.isoformat(),
                "year": m.date.year,
                "bill": m.bill,
                "taught": m.taught_in_session,
                "bonus": m.bonus,
                "whatExisted": m.what_existed,
                "problem": m.problem,
                "mechanism": m.mechanism,
                "whatItFixed": m.what_it_fixed,
                "newTradeoff": m.new_tradeoff,
                "buys": m.buys,
                "givesUp": m.gives_up,
                "whenToChoose": m.when_to_choose,
                "glyph": {
                    "kind": m.glyph.kind,
                    "params": m.glyph.params,
                    "scale": m.glyph.scale,
                    "source": m.glyph.source,
                    "sizes": m.glyph.sizes,
                },
                "source": {
                    "kind": m.source.kind,
                    "title": m.source.title,
                    "url": m.source.url,
                    "arxiv": m.source.arxiv_id,
                    "quoted": m.source.quoted_date,
                    "verifiedOn": m.source.verified_on.isoformat(),
                    "note": m.source.note,
                },
            }
            for m in mechanisms
        ],
        "counts": {
            "total": len(mechanisms),
            "mandated": len(MANDATED),
            "bonus": sum(m.bonus for m in mechanisms),
            "outsideSession": sum(not m.taught_in_session for m in mechanisms),
            "schematic": sum(m.glyph.scale == "schematic" for m in mechanisms),
            "glyphKinds": {
                k: sum(m.glyph.kind == k for m in mechanisms)
                for k in sorted({m.glyph.kind for m in mechanisms})
            },
            "bills": bills_addressed(mechanisms),
        },
        "periods": [
            {
                "start": p.start,
                "end": p.end,
                "dominant": p.dominant,
                "counts": p.counts,
                "mechanisms": list(p.mechanisms),
            }
            for p in pressure_by_period(mechanisms, window=2)
        ],
        # The arc is an editorial claim from the brief, so the page must not restate it — it must
        # render the result of testing it. Every field here is derived; `chapters.js` asserts none
        # of it. The number it replaces ("holds in 6 of 7 windows") counted windows that produced a
        # winner, not windows whose winner the arc predicted, and the arc does not survive that.
        "arc": {
            "claimed": list(verdict.claimed),
            "observed": list(verdict.observed),
            "decided": verdict.decided,
            "undecided": verdict.undecided,
            "matches": verdict.matches,
            "neverDominates": list(verdict.never_dominates),
            "settlesOn": verdict.settles_on,
            "settlesFrom": verdict.settles_from,
            # What survives moving an arbitrary choice. The buckets start in 2014 because attention
            # does, not because the field changed on that boundary, so every count drawn from them
            # has to be re-run under a different edge before it is quoted.
            "robust": {
                "offsets": list(robust.offsets),
                "sequences": [list(x) for x in robust.sequences],
                "matchesAnywhere": robust.matches_anywhere,
                "cacheNeverDominates": robust.cache_never_dominates,
                "settlesEverywhere": robust.settles_everywhere,
            },
        },
        "gaps": [
            {"before": a, "after": b, "days": d}
            for a, b, d in sorted(gaps(mechanisms), key=lambda t: -t[2])[:5]
        ],
        # The specific stretch the page names, carried explicitly rather than looked up out of the
        # top-five list. It happens to be in that list today; if a new mechanism displaced it, a
        # page searching the list would silently fall back to a *different* gap under the same
        # label -- a wrong number that still reads as a correct sentence.
        "quietStretch": next(
            (
                {"before": a, "after": b, "days": d}
                for a, b, d in gaps(mechanisms)
                if a == "standard_attention"
            ),
            None,
        ),
        "yardstick": {
            "layers": yard.layers,
            "kvHeads": yard.kv_heads,
            "queryHeads": yard.query_heads,
            "headDim": yard.head_dim,
            "dtype": yard.dtype,
            "source": yard.source,
        },
        "cache": {
            "contexts": [
                {
                    "context": ctx,
                    "oneUser": kv_cache_bytes(yard, ctx, batch=1),
                    "eightUsers": kv_cache_bytes(yard, ctx, batch=8),
                }
                for ctx in YARDSTICK_CONTEXTS
            ],
            "sharing": [
                {
                    "name": s.name,
                    "kvHeads": s.kv_heads,
                    "note": s.note,
                    "bytesAt32k": kv_cache_bytes(yard, 32_768, kv_heads=s.kv_heads),
                    "bytesPerToken": kv_cache_bytes(yard, 1, kv_heads=s.kv_heads),
                    "tokensBeforeWall": tokens_before_wall(s, yard),
                }
                for s in sharing_ladder(yard)
            ],
            "acceleratorBytes": ACCELERATOR_BYTES,
        },
        # The session's transcript gives ~1 TB for eight users at 1M tokens; its own formula gives
        # something else. Both travel to the page so it can show the disagreement rather than pick.
        "wells": [
            {
                "numeral": w.numeral,
                "subject": w.subject,
                "headline": w.headline,
                "standfirst": w.standfirst,
                "pullQuote": w.pull_quote,
                "keys": list(w.keys),
                "from": span(w, mechanisms)[0].isoformat(),
                "to": span(w, mechanisms)[1].isoformat(),
            }
            for w in WELLS
        ],
        # The plate's ruler draws one bar per year, and the empty years are the point: three of
        # them have no entry at all. Derived here so a year with nothing in it still gets a slot.
        "perYear": [
            {"year": y, "count": sum(1 for m in mechanisms if m.date.year == y)}
            for y in range(mechanisms[0].date.year, mechanisms[-1].date.year + 1)
        ],
        "transcriptDiscrepancy": {
            "claimedTB": 1.0,
            "computedBytes": kv_cache_bytes(yard, 1_000_000, batch=8),
            "context": 1_000_000,
            "users": 8,
        },
    }


def main() -> int:
    """Write `web/data.js` and report what was written."""
    data = payload()
    body = json.dumps(data, indent=2, ensure_ascii=False)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(f"{BANNER}\nexport const M = Object.freeze({body});\n", encoding="utf-8")
    print(
        f"wrote {OUT.relative_to(EXERCISE)}  ({len(body):,} chars, "
        f"{data['counts']['total']} mechanisms, from {CATALOGUE.name})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
