"""Generate `web/data.js` from the tracked catalogue.

    uv run python src/exercises/08-modern-attention-variants/tools/build_web_data.py

`results/mechanisms.json` is the single source for every date, trade-off and citation the page
renders, and `src/attention/` owns everything derived from it — the ordering, the periods, the
gaps, the cache arithmetic. The page reads only what this script emits, so a figure on the site
cannot disagree with the evidence, and the derived findings cannot disagree with the functions the
tests exercise.

Unlike `tools/build_notebook.py`, this file is **tracked**. It is not course material in another
form; it is the build step for a published artifact, and CI has to be able to check the page it
produces.
"""

import json
import sys
from pathlib import Path

EXERCISE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(EXERCISE / "src"))

from attention.cache import kv_cache_bytes, sharing_ladder  # noqa: E402
from attention.catalogue import CATALOGUE, MANDATED, load  # noqa: E402
from attention.config import YARDSTICK_CONTEXTS, Yardstick  # noqa: E402
from attention.timeline import bills_addressed, gaps, in_order, pressure_by_period  # noqa: E402

OUT = EXERCISE / "web" / "data.js"

BANNER = """\
// GENERATED by tools/build_web_data.py from results/mechanisms.json — do not edit by hand.
//
// Every date, trade-off and citation on this page comes from the tracked catalogue, and every
// derived figure comes from the same functions the tests exercise. Editing this file directly
// would let the page disagree with the evidence that produced it; regenerate instead:
//
//     uv run python src/exercises/08-modern-attention-variants/tools/build_web_data.py
"""


def payload() -> dict:
    """Everything the page renders, derived here so the page derives nothing."""
    mechanisms = in_order(load())
    yard = Yardstick()

    return {
        "mechanisms": [
            {
                "key": m.key,
                "name": m.name,
                "aka": list(m.aka),
                "date": m.date.isoformat(),
                "year": m.date.year,
                "bill": m.bill,
                "taught": m.taught_in_session,
                "bonus": m.bonus,
                "whatExisted": m.what_existed,
                "problem": m.problem,
                "mechanism": m.mechanism,
                "whatItFixed": m.what_it_fixed,
                "newTradeoff": m.new_tradeoff,
                "buys": m.buys,
                "givesUp": m.gives_up,
                "whenToChoose": m.when_to_choose,
                "glyph": {
                    "kind": m.glyph.kind,
                    "params": m.glyph.params,
                    "scale": m.glyph.scale,
                    "source": m.glyph.source,
                },
                "source": {
                    "kind": m.source.kind,
                    "title": m.source.title,
                    "url": m.source.url,
                    "arxiv": m.source.arxiv_id,
                    "quoted": m.source.quoted_date,
                    "verifiedOn": m.source.verified_on.isoformat(),
                    "note": m.source.note,
                },
            }
            for m in mechanisms
        ],
        "counts": {
            "total": len(mechanisms),
            "mandated": len(MANDATED),
            "bonus": sum(m.bonus for m in mechanisms),
            "outsideSession": sum(not m.taught_in_session for m in mechanisms),
            "schematic": sum(m.glyph.scale == "schematic" for m in mechanisms),
            "glyphKinds": {
                k: sum(m.glyph.kind == k for m in mechanisms)
                for k in sorted({m.glyph.kind for m in mechanisms})
            },
            "bills": bills_addressed(mechanisms),
        },
        "periods": [
            {
                "start": p.start,
                "end": p.end,
                "dominant": p.dominant,
                "counts": p.counts,
                "mechanisms": list(p.mechanisms),
            }
            for p in pressure_by_period(mechanisms, window=2)
        ],
        "gaps": [
            {"before": a, "after": b, "days": d}
            for a, b, d in sorted(gaps(mechanisms), key=lambda t: -t[2])[:5]
        ],
        # The specific stretch the page names, carried explicitly rather than looked up out of the
        # top-five list. It happens to be in that list today; if a new mechanism displaced it, a
        # page searching the list would silently fall back to a *different* gap under the same
        # label -- a wrong number that still reads as a correct sentence.
        "quietStretch": next(
            (
                {"before": a, "after": b, "days": d}
                for a, b, d in gaps(mechanisms)
                if a == "standard_attention"
            ),
            None,
        ),
        "yardstick": {
            "layers": yard.layers,
            "kvHeads": yard.kv_heads,
            "queryHeads": yard.query_heads,
            "headDim": yard.head_dim,
            "dtype": yard.dtype,
            "source": yard.source,
        },
        "cache": {
            "contexts": [
                {
                    "context": ctx,
                    "oneUser": kv_cache_bytes(yard, ctx, batch=1),
                    "eightUsers": kv_cache_bytes(yard, ctx, batch=8),
                }
                for ctx in YARDSTICK_CONTEXTS
            ],
            "sharing": [
                {
                    "name": s.name,
                    "kvHeads": s.kv_heads,
                    "note": s.note,
                    "bytesAt32k": kv_cache_bytes(yard, 32_768, kv_heads=s.kv_heads),
                }
                for s in sharing_ladder(yard)
            ],
        },
        # The session's transcript gives ~1 TB for eight users at 1M tokens; its own formula gives
        # something else. Both travel to the page so it can show the disagreement rather than pick.
        "transcriptDiscrepancy": {
            "claimedTB": 1.0,
            "computedBytes": kv_cache_bytes(yard, 1_000_000, batch=8),
            "context": 1_000_000,
            "users": 8,
        },
    }


def main() -> int:
    """Write `web/data.js` and report what was written."""
    data = payload()
    body = json.dumps(data, indent=2, ensure_ascii=False)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(f"{BANNER}\nexport const M = Object.freeze({body});\n", encoding="utf-8")
    print(
        f"wrote {OUT.relative_to(EXERCISE)}  ({len(body):,} chars, "
        f"{data['counts']['total']} mechanisms, from {CATALOGUE.name})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
